"""Hash-chained canonical JSONL recordings for deterministic SDK replay.

The recording contains portable policy requests and pure SDK outputs. It does
not contain, reproduce, or certify a physics-engine trajectory. Canonical JSON
digests are produced by the loaded SDK core. The JSONL transport uses the
public Python binding's sorted, compact, finite JSON encoding so executable
float spellings such as ``0.0`` survive a read/write round trip.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping, Sequence

from python import (
    ABI_GENERATION,
    SDK_VERSION,
    LocomotionCore,
    SELECTED_BALANCED_WAVE_POLICY_ID,
)

HEADER_SCHEMA = "sporespore_canonical_recording_header_v1"
FRAME_SCHEMA = "sporespore_canonical_recording_frame_v1"
FOOTER_SCHEMA = "sporespore_canonical_recording_footer_v1"
POLICY_REQUEST_SCHEMA = "sporespore_balanced_wave_policy_step_request_v1"
HEADER_FIELDS = {
    "schema_version",
    "record_type",
    "recording_id",
    "sdk_version",
    "abi_generation",
    "policy_id",
    "descriptor",
    "descriptor_canonical_sha256",
    "descriptor_sha256",
    "declared_frame_count",
    "previous_record_sha256",
    "world_build_count",
    "physical_acceptance_authority",
    "record_canonical_sha256",
    "record_sha256",
}
FRAME_FIELDS = {
    "schema_version",
    "record_type",
    "frame_index",
    "request",
    "request_canonical_sha256",
    "request_sha256",
    "response",
    "response_canonical_sha256",
    "response_sha256",
    "previous_record_sha256",
    "world_build_count",
    "physical_acceptance_authority",
    "record_canonical_sha256",
    "record_sha256",
}
FOOTER_FIELDS = {
    "schema_version",
    "record_type",
    "recording_id",
    "frame_count",
    "last_frame_record_sha256",
    "previous_record_sha256",
    "integrity_complete",
    "deterministic_replay_executed",
    "physics_trajectory_recorded",
    "world_build_count",
    "physical_acceptance_authority",
    "record_canonical_sha256",
    "record_sha256",
}


class RecordReplayError(RuntimeError):
    """A fail-closed recording integrity or deterministic replay failure."""

    def __init__(self, failure_code: str, detail: str) -> None:
        super().__init__(f"{failure_code}:{detail}")
        self.failure_code = failure_code
        self.detail = detail


def _require(condition: bool, failure_code: str, detail: str) -> None:
    if not condition:
        raise RecordReplayError(failure_code, detail)


def _require_exact_fields(
    value: Mapping[str, Any],
    expected: set[str],
    failure_code: str,
    label: str,
) -> None:
    actual = set(value)
    _require(
        actual == expected,
        failure_code,
        (
            f"{label} fields differ; missing={sorted(expected - actual)} "
            f"unknown={sorted(actual - expected)}"
        ),
    )


def _canonical_receipt(
    core: LocomotionCore,
    value: Any,
) -> dict[str, Any]:
    receipt = core.canonicalize_json(value)
    _require(
        receipt.get("schema_version") == "sporespore_canonical_json_receipt_v1",
        "CANONICAL_RECEIPT_INVALID",
        "core returned an unexpected canonical receipt schema",
    )
    _require(
        receipt.get("world_build_count") == 0
        and receipt.get("physical_acceptance_authority") is False,
        "CANONICAL_RECEIPT_CLAIM_INVALID",
        "pure canonicalization exposed physical authority",
    )
    return receipt


def _canonical_sha256(core: LocomotionCore, value: Any) -> str:
    digest = _canonical_receipt(core, value).get("sha256")
    _require(
        isinstance(digest, str) and digest.startswith("sha256:"),
        "CANONICAL_DIGEST_INVALID",
        "core did not return a SHA-256 identity",
    )
    return digest


def _transport_json(value: Any) -> str:
    """Match the public Python binding's deterministic, lossless encoding."""

    return json.dumps(
        value,
        allow_nan=False,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    )


def _transport_sha256(value: Any) -> str:
    exact_bytes = _transport_json(value).encode("utf-8")
    return f"sha256:{hashlib.sha256(exact_bytes).hexdigest()}"


def _seal_record(
    core: LocomotionCore,
    record: Mapping[str, Any],
) -> dict[str, Any]:
    sealed = dict(record)
    _require(
        "record_sha256" not in sealed and "record_canonical_sha256" not in sealed,
        "RECORD_ALREADY_SEALED",
        "record digests must be generated by the recording writer",
    )
    sealed["record_canonical_sha256"] = _canonical_sha256(core, sealed)
    sealed["record_sha256"] = _transport_sha256(sealed)
    return sealed


def _pure_output_exact(response: Mapping[str, Any]) -> bool:
    actuation = response.get("actuation")
    return (
        response.get("schema_version") == "sporespore_balanced_wave_runtime_v1"
        and isinstance(actuation, Mapping)
        and actuation.get("schema_version") == "sporespore_actuation_frame_v1"
        and actuation.get("world_build_count") == 0
        and actuation.get("physical_acceptance_authority") is False
    )


def recording_sha256(path: str | Path) -> str:
    """Return the SHA-256 identity of the exact retained JSONL bytes."""

    resolved = Path(path).resolve()
    return f"sha256:{hashlib.sha256(resolved.read_bytes()).hexdigest()}"


def write_recording(
    path: str | Path,
    core: LocomotionCore,
    *,
    recording_id: str,
    descriptor: Mapping[str, Any],
    frames: Sequence[Mapping[str, Any]],
    policy_id: str = SELECTED_BALANCED_WAVE_POLICY_ID,
) -> dict[str, Any]:
    """Write one complete recording without overwriting an existing path.

    Each frame must contain exactly a ``request`` and ``response`` mapping.
    The request is the explicit named-policy request submitted to the public
    core, and the response is the pure runtime output returned by that call.
    """

    target = Path(path).resolve()
    _require(
        bool(recording_id.strip()),
        "RECORDING_ID_INVALID",
        "recording_id must be nonempty",
    )
    _require(
        policy_id == SELECTED_BALANCED_WAVE_POLICY_ID,
        "POLICY_NOT_RELEASE_SELECTED",
        f"recording policy is not the selected quadruped policy: {policy_id}",
    )
    _require(
        not target.exists(),
        "RECORDING_PATH_EXISTS",
        f"refusing to overwrite {target}",
    )
    _require(
        target.parent.is_dir(),
        "RECORDING_PARENT_MISSING",
        f"recording parent does not exist: {target.parent}",
    )

    records: list[dict[str, Any]] = []
    previous: str | None = None
    header = _seal_record(
        core,
        {
            "schema_version": HEADER_SCHEMA,
            "record_type": "header",
            "recording_id": recording_id,
            "sdk_version": SDK_VERSION,
            "abi_generation": ABI_GENERATION,
            "policy_id": policy_id,
            "descriptor": dict(descriptor),
            "descriptor_canonical_sha256": _canonical_sha256(
                core,
                descriptor,
            ),
            "descriptor_sha256": _transport_sha256(descriptor),
            "declared_frame_count": len(frames),
            "previous_record_sha256": previous,
            "world_build_count": 0,
            "physical_acceptance_authority": False,
        },
    )
    records.append(header)
    previous = str(header["record_sha256"])

    previous_semantic_step: int | None = None
    previous_next_memory: Mapping[str, Any] | None = None
    for index, frame_value in enumerate(frames):
        frame = dict(frame_value)
        _require(
            set(frame) == {"request", "response"},
            "FRAME_FIELDS_INVALID",
            f"frame {index} must contain exactly request and response",
        )
        request = frame["request"]
        response = frame["response"]
        _require(
            isinstance(request, Mapping) and isinstance(response, Mapping),
            "FRAME_VALUE_INVALID",
            f"frame {index} request and response must be objects",
        )
        _require(
            request.get("schema_version") == POLICY_REQUEST_SCHEMA
            and request.get("policy_id") == policy_id,
            "FRAME_POLICY_REQUEST_INVALID",
            f"frame {index} is not an explicit selected-policy request",
        )
        state = request.get("state")
        actuation = response.get("actuation")
        _require(
            isinstance(state, Mapping)
            and isinstance(actuation, Mapping)
            and isinstance(request.get("memory"), Mapping)
            and isinstance(response.get("next_memory"), Mapping),
            "FRAME_RUNTIME_STRUCTURE_INVALID",
            f"frame {index} runtime state, memory, or output is invalid",
        )
        semantic_step = state.get("semantic_step")
        _require(
            isinstance(semantic_step, int)
            and not isinstance(semantic_step, bool)
            and semantic_step >= 0
            and actuation.get("semantic_step") == semantic_step,
            "FRAME_SEMANTIC_STEP_INVALID",
            f"frame {index} semantic step is invalid",
        )
        if previous_semantic_step is not None:
            _require(
                semantic_step == previous_semantic_step + 1,
                "FRAME_SEMANTIC_STEP_GAP",
                f"frame {index} is not the next semantic step",
            )
            _require(
                _transport_sha256(request["memory"])
                == _transport_sha256(previous_next_memory),
                "FRAME_MEMORY_CHAIN_MISMATCH",
                f"frame {index} does not consume prior next_memory",
            )
        _require(
            _pure_output_exact(response),
            "FRAME_OUTPUT_CLAIM_INVALID",
            f"frame {index} output is not a pure zero-world SDK result",
        )
        sealed = _seal_record(
            core,
            {
                "schema_version": FRAME_SCHEMA,
                "record_type": "frame",
                "frame_index": index,
                "request": dict(request),
                "request_canonical_sha256": _canonical_sha256(
                    core,
                    request,
                ),
                "request_sha256": _transport_sha256(request),
                "response": dict(response),
                "response_canonical_sha256": _canonical_sha256(
                    core,
                    response,
                ),
                "response_sha256": _transport_sha256(response),
                "previous_record_sha256": previous,
                "world_build_count": 0,
                "physical_acceptance_authority": False,
            },
        )
        records.append(sealed)
        previous = str(sealed["record_sha256"])
        previous_semantic_step = semantic_step
        previous_next_memory = response["next_memory"]

    footer = _seal_record(
        core,
        {
            "schema_version": FOOTER_SCHEMA,
            "record_type": "footer",
            "recording_id": recording_id,
            "frame_count": len(frames),
            "last_frame_record_sha256": (
                records[-1]["record_sha256"] if frames else None
            ),
            "previous_record_sha256": previous,
            "integrity_complete": True,
            "deterministic_replay_executed": False,
            "physics_trajectory_recorded": False,
            "world_build_count": 0,
            "physical_acceptance_authority": False,
        },
    )
    records.append(footer)

    exact_bytes = (
        "\n".join(_transport_json(record) for record in records) + "\n"
    ).encode("utf-8")
    target.write_bytes(exact_bytes)
    return {
        "schema_version": "sporespore_recording_write_receipt_v1",
        "recording_path": str(target),
        "recording_sha256": recording_sha256(target),
        "recording_id": recording_id,
        "policy_id": policy_id,
        "frame_count": len(frames),
        "record_count": len(records),
        "integrity_verified": False,
        "deterministic_replay_executed": False,
        "physics_trajectory_recorded": False,
        "world_build_count": 0,
        "physical_acceptance_authority": False,
    }


def _read_records(path: Path) -> list[dict[str, Any]]:
    try:
        raw_lines = path.read_text(encoding="utf-8").splitlines()
    except (OSError, UnicodeError) as error:
        raise RecordReplayError(
            "RECORDING_READ_FAILED",
            str(error),
        ) from error
    _require(raw_lines, "RECORDING_EMPTY", "recording contains no records")
    _require(
        all(line.strip() for line in raw_lines),
        "RECORDING_BLANK_LINE",
        "blank JSONL records are forbidden",
    )
    records: list[dict[str, Any]] = []
    for index, line in enumerate(raw_lines):
        try:
            value = json.loads(line)
        except json.JSONDecodeError as error:
            raise RecordReplayError(
                "RECORDING_JSON_INVALID",
                f"record {index}: {error}",
            ) from error
        _require(
            isinstance(value, dict),
            "RECORDING_RECORD_INVALID",
            f"record {index} is not an object",
        )
        _require(
            line == _transport_json(value),
            "RECORDING_TRANSPORT_NOT_CANONICAL",
            f"record {index} is not sorted compact finite JSON",
        )
        records.append(value)
    return records


def verify_recording(
    path: str | Path,
    core: LocomotionCore,
    *,
    expected_policy_id: str = SELECTED_BALANCED_WAVE_POLICY_ID,
) -> dict[str, Any]:
    """Verify schemas, compatibility, inner digests, and the full hash chain."""

    resolved = Path(path).resolve()
    _require(
        resolved.is_file(),
        "RECORDING_NOT_FOUND",
        f"recording does not exist: {resolved}",
    )
    records = _read_records(resolved)
    _require(
        len(records) >= 2,
        "RECORDING_STRUCTURE_INVALID",
        "recording requires a header and footer",
    )
    header = records[0]
    footer = records[-1]
    frames = records[1:-1]
    _require_exact_fields(
        header,
        HEADER_FIELDS,
        "RECORDING_HEADER_FIELDS_INVALID",
        "header",
    )
    _require_exact_fields(
        footer,
        FOOTER_FIELDS,
        "RECORDING_FOOTER_FIELDS_INVALID",
        "footer",
    )
    _require(
        header.get("schema_version") == HEADER_SCHEMA
        and header.get("record_type") == "header",
        "RECORDING_HEADER_INVALID",
        "first record is not a v1 header",
    )
    _require(
        footer.get("schema_version") == FOOTER_SCHEMA
        and footer.get("record_type") == "footer",
        "RECORDING_FOOTER_INVALID",
        "last record is not a v1 footer",
    )
    _require(
        header.get("sdk_version") == SDK_VERSION,
        "SDK_VERSION_MISMATCH",
        f"recorded={header.get('sdk_version')} loaded={SDK_VERSION}",
    )
    _require(
        header.get("abi_generation") == ABI_GENERATION,
        "ABI_GENERATION_MISMATCH",
        f"recorded={header.get('abi_generation')} loaded={ABI_GENERATION}",
    )
    _require(
        header.get("policy_id") == expected_policy_id,
        "POLICY_ID_MISMATCH",
        f"recorded={header.get('policy_id')} expected={expected_policy_id}",
    )
    _require(
        header.get("descriptor_canonical_sha256")
        == _canonical_sha256(core, header.get("descriptor")),
        "DESCRIPTOR_CANONICAL_DIGEST_MISMATCH",
        "recorded descriptor does not match its canonical digest",
    )
    _require(
        header.get("descriptor_sha256") == _transport_sha256(header.get("descriptor")),
        "DESCRIPTOR_TRANSPORT_DIGEST_MISMATCH",
        "recorded descriptor does not match its exact transport digest",
    )
    _require(
        header.get("declared_frame_count") == len(frames)
        and footer.get("frame_count") == len(frames),
        "FRAME_COUNT_MISMATCH",
        "declared frame count does not match JSONL structure",
    )
    _require(
        footer.get("recording_id") == header.get("recording_id"),
        "RECORDING_ID_MISMATCH",
        "header and footer recording IDs differ",
    )

    previous: str | None = None
    for record_index, record in enumerate(records):
        _require(
            record.get("previous_record_sha256") == previous,
            "RECORD_CHAIN_MISMATCH",
            f"record {record_index} does not reference the previous record",
        )
        _require(
            record.get("world_build_count") == 0
            and record.get("physical_acceptance_authority") is False,
            "RECORD_CLAIM_INVALID",
            f"record {record_index} exposes physical authority",
        )
        claimed = record.get("record_sha256")
        claimed_canonical = record.get("record_canonical_sha256")
        unsealed = dict(record)
        unsealed.pop("record_sha256", None)
        unsealed.pop("record_canonical_sha256", None)
        _require(
            claimed_canonical == _canonical_sha256(core, unsealed),
            "RECORD_CANONICAL_DIGEST_MISMATCH",
            f"record {record_index} canonical digest mismatch",
        )
        transport_record = dict(unsealed)
        transport_record["record_canonical_sha256"] = claimed_canonical
        _require(
            claimed == _transport_sha256(transport_record),
            "RECORD_DIGEST_MISMATCH",
            f"record {record_index} exact transport digest mismatch",
        )
        previous = str(claimed)

    previous_semantic_step: int | None = None
    previous_next_memory: Mapping[str, Any] | None = None
    for frame_index, frame in enumerate(frames):
        _require_exact_fields(
            frame,
            FRAME_FIELDS,
            "RECORDING_FRAME_FIELDS_INVALID",
            f"frame {frame_index}",
        )
        _require(
            frame.get("schema_version") == FRAME_SCHEMA
            and frame.get("record_type") == "frame"
            and frame.get("frame_index") == frame_index,
            "FRAME_ORDER_INVALID",
            f"frame {frame_index} schema, type, or index is invalid",
        )
        request = frame.get("request")
        response = frame.get("response")
        _require(
            isinstance(request, Mapping) and isinstance(response, Mapping),
            "FRAME_VALUE_INVALID",
            f"frame {frame_index} request or response is not an object",
        )
        _require(
            request.get("schema_version") == POLICY_REQUEST_SCHEMA
            and request.get("policy_id") == expected_policy_id,
            "FRAME_POLICY_REQUEST_INVALID",
            f"frame {frame_index} policy request is incompatible",
        )
        state = request.get("state")
        response_actuation = response.get("actuation")
        _require(
            isinstance(state, Mapping)
            and isinstance(response_actuation, Mapping)
            and isinstance(request.get("memory"), Mapping)
            and isinstance(response.get("next_memory"), Mapping),
            "FRAME_RUNTIME_STRUCTURE_INVALID",
            f"frame {frame_index} runtime state, memory, or output is invalid",
        )
        semantic_step = state.get("semantic_step")
        _require(
            isinstance(semantic_step, int)
            and not isinstance(semantic_step, bool)
            and semantic_step >= 0
            and response_actuation.get("semantic_step") == semantic_step,
            "FRAME_SEMANTIC_STEP_INVALID",
            f"frame {frame_index} semantic step is invalid",
        )
        if previous_semantic_step is not None:
            _require(
                semantic_step == previous_semantic_step + 1,
                "FRAME_SEMANTIC_STEP_GAP",
                f"frame {frame_index} is not the next semantic step",
            )
            _require(
                _transport_sha256(request["memory"])
                == _transport_sha256(previous_next_memory),
                "FRAME_MEMORY_CHAIN_MISMATCH",
                f"frame {frame_index} does not consume prior next_memory",
            )
        previous_semantic_step = semantic_step
        previous_next_memory = response["next_memory"]
        _require(
            frame.get("request_canonical_sha256") == _canonical_sha256(core, request),
            "REQUEST_CANONICAL_DIGEST_MISMATCH",
            f"frame {frame_index} request canonical digest mismatch",
        )
        _require(
            frame.get("request_sha256") == _transport_sha256(request),
            "REQUEST_DIGEST_MISMATCH",
            f"frame {frame_index} request transport digest mismatch",
        )
        _require(
            frame.get("response_canonical_sha256") == _canonical_sha256(core, response),
            "RESPONSE_CANONICAL_DIGEST_MISMATCH",
            f"frame {frame_index} response canonical digest mismatch",
        )
        _require(
            frame.get("response_sha256") == _transport_sha256(response),
            "RESPONSE_DIGEST_MISMATCH",
            f"frame {frame_index} response transport digest mismatch",
        )
        _require(
            _pure_output_exact(response),
            "FRAME_OUTPUT_CLAIM_INVALID",
            f"frame {frame_index} output exposes physical authority",
        )

    expected_last_frame = frames[-1].get("record_sha256") if frames else None
    _require(
        footer.get("last_frame_record_sha256") == expected_last_frame,
        "FOOTER_LAST_FRAME_MISMATCH",
        "footer does not identify the final frame",
    )
    _require(
        footer.get("integrity_complete") is True
        and footer.get("deterministic_replay_executed") is False
        and footer.get("physics_trajectory_recorded") is False,
        "FOOTER_CLAIM_INVALID",
        "footer claim boundary is invalid",
    )
    return {
        "schema_version": "sporespore_recording_verification_receipt_v1",
        "recording_path": str(resolved),
        "recording_sha256": recording_sha256(resolved),
        "recording_id": header["recording_id"],
        "policy_id": header["policy_id"],
        "frame_count": len(frames),
        "record_count": len(records),
        "integrity_verified": True,
        "deterministic_replay_executed": False,
        "physics_trajectory_recorded": False,
        "world_build_count": 0,
        "physical_acceptance_authority": False,
        "_frames": frames,
    }


def replay_recording(
    path: str | Path,
    core: LocomotionCore,
    *,
    expected_policy_id: str = SELECTED_BALANCED_WAVE_POLICY_ID,
) -> dict[str, Any]:
    """Re-execute every recorded request and require exact canonical outputs."""

    verified = verify_recording(
        path,
        core,
        expected_policy_id=expected_policy_id,
    )
    frames = verified.pop("_frames")
    replayed_response_sha256: list[str] = []
    replayed_response_canonical_sha256: list[str] = []
    for frame_index, frame in enumerate(frames):
        request = dict(frame["request"])
        response = core.balanced_wave_policy_step(
            expected_policy_id,
            request,
        )
        digest = _transport_sha256(response)
        canonical_digest = _canonical_sha256(core, response)
        _require(
            digest == frame["response_sha256"],
            "REPLAY_OUTPUT_MISMATCH",
            f"frame {frame_index} replay output differs from the recording",
        )
        _require(
            canonical_digest == frame["response_canonical_sha256"],
            "REPLAY_CANONICAL_OUTPUT_MISMATCH",
            (
                f"frame {frame_index} replay output differs under "
                "core canonicalization"
            ),
        )
        _require(
            _pure_output_exact(response),
            "REPLAY_OUTPUT_CLAIM_INVALID",
            f"frame {frame_index} replay exposed physical authority",
        )
        replayed_response_sha256.append(digest)
        replayed_response_canonical_sha256.append(canonical_digest)
    return {
        **verified,
        "schema_version": "sporespore_recording_replay_receipt_v1",
        "deterministic_replay_executed": True,
        "deterministic_replay_exact": True,
        "replayed_response_sha256": replayed_response_sha256,
        "replayed_response_canonical_sha256": (replayed_response_canonical_sha256),
        "physics_trajectory_replayed": False,
        "walking_acceptance": False,
        "physical_acceptance_authority": False,
    }
