class_name LabFailureCodes
extends RefCounted

## Stable, append-only identifiers used by machine-readable lab evidence.
##
## Existing values must never be renamed after an evidence bundle has been
## archived. Add a new value and a migration alias instead.

const SCHEMA_INVALID := "SCHEMA_INVALID"
const JSON_PARSE_FAILED := "JSON_PARSE_FAILED"
const ARTIFACT_MISSING := "ARTIFACT_MISSING"
const ARTIFACT_UNDECLARED := "ARTIFACT_UNDECLARED"
const CHECKSUM_MISMATCH := "CHECKSUM_MISMATCH"
const BYTE_COUNT_MISMATCH := "BYTE_COUNT_MISMATCH"
const LINE_COUNT_MISMATCH := "LINE_COUNT_MISMATCH"
const RUN_ID_MISMATCH := "RUN_ID_MISMATCH"
const RECORD_ORDER_INVALID := "RECORD_ORDER_INVALID"
const RECORD_REFERENCE_MISSING := "RECORD_REFERENCE_MISSING"
const ENVELOPE_HASH_MISMATCH := "ENVELOPE_HASH_MISMATCH"
const TRANSITION_INVALID := "TRANSITION_INVALID"
const APPLICATION_LINK_MISMATCH := "APPLICATION_LINK_MISMATCH"
const APPLICATION_COUNT_MISMATCH := "APPLICATION_COUNT_MISMATCH"
const PARTIAL_RUN_NOT_PROMOTABLE := "PARTIAL_RUN_NOT_PROMOTABLE"
const MANIFEST_NOT_COMPLETE := "MANIFEST_NOT_COMPLETE"
const SUMMARY_COUNT_MISMATCH := "SUMMARY_COUNT_MISMATCH"
const DIRTY_SOURCE_NOT_PROMOTABLE := "DIRTY_SOURCE_NOT_PROMOTABLE"
const EVIDENCE_INVALID := "EVIDENCE_INVALID"
const RUN_RESERVATION_COLLISION := "RUN_RESERVATION_COLLISION"
const TRACE_WRITE_FAILED := "TRACE_WRITE_FAILED"
const TRACE_REPLAY_FAILED := "TRACE_REPLAY_FAILED"

const OBS_CONTACT_DISABLED := "OBS_CONTACT_DISABLED"
const CONTACT_BUFFER_SATURATED := "CONTACT_BUFFER_SATURATED"
const CONTACT_NORMAL_AMBIGUOUS := "CONTACT_NORMAL_AMBIGUOUS"
const STALE_JOINT_AXIS := "STALE_JOINT_AXIS"
const TORQUE_NOT_PAIRED := "TORQUE_NOT_PAIRED"
const ACTIVE_TORQUE_SATURATION := "ACTIVE_TORQUE_SATURATION"
const ACTIVE_POWER_SATURATION := "ACTIVE_POWER_SATURATION"
const STRUCTURAL_TORQUE_EXCEEDED := "STRUCTURAL_TORQUE_EXCEEDED"
const PASSIVE_ENERGY_CREATED := "PASSIVE_ENERGY_CREATED"
const SUPPORT_MAP_RANK_DEFICIENT := "SUPPORT_MAP_RANK_DEFICIENT"
const ALLOCATOR_FRICTION_INFEASIBLE := "ALLOCATOR_FRICTION_INFEASIBLE"
const ALLOCATOR_ACTUATOR_INFEASIBLE := "ALLOCATOR_ACTUATOR_INFEASIBLE"
const HEIGHT_TARGET_UNREACHABLE := "HEIGHT_TARGET_UNREACHABLE"
const STRAIGHT_LEG_SINGULARITY := "STRAIGHT_LEG_SINGULARITY"
const SUPPORT_LOST := "SUPPORT_LOST"
const REACTION_TOO_LATE := "REACTION_TOO_LATE"
const CATCH_UNREACHABLE_BEFORE_IMPACT := "CATCH_UNREACHABLE_BEFORE_IMPACT"
const CATCH_CONTACT_NEVER_BEARING := "CATCH_CONTACT_NEVER_BEARING"
const FALL_ARREST_INSUFFICIENT_IMPULSE := "FALL_ARREST_INSUFFICIENT_IMPULSE"
const POSE_CLASSIFICATION_AMBIGUOUS := "POSE_CLASSIFICATION_AMBIGUOUS"
const RECOVERY_PROFILE_MISSING := "RECOVERY_PROFILE_MISSING"
const RECOVERY_PHASE_INFEASIBLE := "RECOVERY_PHASE_INFEASIBLE"
const RECOVERY_PHASE_TIMEOUT := "RECOVERY_PHASE_TIMEOUT"
const UNAUTHORIZED_ROOT_INTERVENTION := "UNAUTHORIZED_ROOT_INTERVENTION"
const ENERGY_ACCOUNTING_RESIDUAL := "ENERGY_ACCOUNTING_RESIDUAL"
const OBSERVER_PERTURBATION := "OBSERVER_PERTURBATION"
const NONFINITE_STATE := "NONFINITE_STATE"
const PUBLICATION_TRUST_ROOT_INVALID := "PUBLICATION_TRUST_ROOT_INVALID"
const PUBLICATION_KEY_MISSING := "PUBLICATION_KEY_MISSING"
const PUBLICATION_KEY_INVALID := "PUBLICATION_KEY_INVALID"
const PUBLICATION_RECEIPT_MISSING := "PUBLICATION_RECEIPT_MISSING"
const PUBLICATION_RECEIPT_COLLISION := "PUBLICATION_RECEIPT_COLLISION"
const PUBLICATION_RECEIPT_BUSY := "PUBLICATION_RECEIPT_BUSY"
const PUBLICATION_RECEIPT_WRITE_FAILED := "PUBLICATION_RECEIPT_WRITE_FAILED"
const PUBLICATION_RECEIPT_INVALID := "PUBLICATION_RECEIPT_INVALID"
const PUBLICATION_ENVELOPE_MISMATCH := "PUBLICATION_ENVELOPE_MISMATCH"
const PUBLICATION_TAG_MISMATCH := "PUBLICATION_TAG_MISMATCH"
const LEGACY_CERTIFICATION_AUTHORING_DISABLED := \
	"LEGACY_CERTIFICATION_AUTHORING_DISABLED"

const ALL: Array[String] = [
	SCHEMA_INVALID,
	JSON_PARSE_FAILED,
	ARTIFACT_MISSING,
	ARTIFACT_UNDECLARED,
	CHECKSUM_MISMATCH,
	BYTE_COUNT_MISMATCH,
	LINE_COUNT_MISMATCH,
	RUN_ID_MISMATCH,
	RECORD_ORDER_INVALID,
	RECORD_REFERENCE_MISSING,
	ENVELOPE_HASH_MISMATCH,
	TRANSITION_INVALID,
	APPLICATION_LINK_MISMATCH,
	APPLICATION_COUNT_MISMATCH,
	PARTIAL_RUN_NOT_PROMOTABLE,
	MANIFEST_NOT_COMPLETE,
	SUMMARY_COUNT_MISMATCH,
	DIRTY_SOURCE_NOT_PROMOTABLE,
	EVIDENCE_INVALID,
	RUN_RESERVATION_COLLISION,
	TRACE_WRITE_FAILED,
	TRACE_REPLAY_FAILED,
	OBS_CONTACT_DISABLED,
	CONTACT_BUFFER_SATURATED,
	CONTACT_NORMAL_AMBIGUOUS,
	STALE_JOINT_AXIS,
	TORQUE_NOT_PAIRED,
	ACTIVE_TORQUE_SATURATION,
	ACTIVE_POWER_SATURATION,
	STRUCTURAL_TORQUE_EXCEEDED,
	PASSIVE_ENERGY_CREATED,
	SUPPORT_MAP_RANK_DEFICIENT,
	ALLOCATOR_FRICTION_INFEASIBLE,
	ALLOCATOR_ACTUATOR_INFEASIBLE,
	HEIGHT_TARGET_UNREACHABLE,
	STRAIGHT_LEG_SINGULARITY,
	SUPPORT_LOST,
	REACTION_TOO_LATE,
	CATCH_UNREACHABLE_BEFORE_IMPACT,
	CATCH_CONTACT_NEVER_BEARING,
	FALL_ARREST_INSUFFICIENT_IMPULSE,
	POSE_CLASSIFICATION_AMBIGUOUS,
	RECOVERY_PROFILE_MISSING,
	RECOVERY_PHASE_INFEASIBLE,
	RECOVERY_PHASE_TIMEOUT,
	UNAUTHORIZED_ROOT_INTERVENTION,
	ENERGY_ACCOUNTING_RESIDUAL,
	OBSERVER_PERTURBATION,
	NONFINITE_STATE,
	PUBLICATION_TRUST_ROOT_INVALID,
	PUBLICATION_KEY_MISSING,
	PUBLICATION_KEY_INVALID,
	PUBLICATION_RECEIPT_MISSING,
	PUBLICATION_RECEIPT_COLLISION,
	PUBLICATION_RECEIPT_BUSY,
	PUBLICATION_RECEIPT_WRITE_FAILED,
	PUBLICATION_RECEIPT_INVALID,
	PUBLICATION_ENVELOPE_MISMATCH,
	PUBLICATION_TAG_MISMATCH,
	LEGACY_CERTIFICATION_AUTHORING_DISABLED,
]


static func is_registered(code: String) -> bool:
	return code in ALL
