#requires -Version 7.0

[CmdletBinding()]
param(
    [switch]$PreflightOnly,
    [switch]$RunPhysical,
    [string]$FullConformanceAttestation = "",
    [string]$OutputRoot = "",
    [string]$Python = "python",
    [string]$PowerShell = "pwsh",
    [string]$Godot = (
        "C:\Users\Cole\CodeStuff\Misc\Godot\" +
        "Godot_v4.7-stable_mono_win64_console.exe"
    ),
    [ValidateRange(60, 3600)][int]$GateTimeoutSeconds = 1200,
    [ValidateRange(300, 3600)][int]$CellTimeoutSeconds = 900
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $false

$sdkRoot = [IO.Path]::GetFullPath($PSScriptRoot)
$repoRoot = [IO.Path]::GetFullPath((Split-Path -Parent $sdkRoot))
$implementationPath = Join-Path $sdkRoot "turning\r23d3_implementation_contract_v1.json"
$preregistrationPath = Join-Path $sdkRoot "turning\r23d3_phase_balanced_preregistration_v1.json"
$closurePath = Join-Path $sdkRoot "turning\r23d3_physical_closure_v1.json"
$evaluatorPath = Join-Path $sdkRoot "turning\r23d3_physical_evaluator.py"
$artifactStorePath = Join-Path $sdkRoot "content_addressed_artifact_store.ps1"
$operationLockPath = Join-Path $sdkRoot "locomotion_operation_lock.ps1"
$attestationVerifierPath = Join-Path $sdkRoot "locomotion_full_conformance_attestation.ps1"
$runtimeMaterializationPath = Join-Path $sdkRoot "r23d3_reproducible_runtime_materialization.ps1"
$mujocoRoot = Join-Path $sdkRoot "adapters\mujoco"
$mujocoPython = Join-Path $mujocoRoot ".venv\Scripts\python.exe"
$pythonCoreRoot = Join-Path $sdkRoot "python"
$godotWorkerResource = "res://tests/test_sdk_qsdk_r23d3_godot_jolt_worker.gd"
$campaignId = "QSDK-R23D3-PHASE-BALANCED-BILATERAL-TURN-DEVELOPMENT"
$gateId = "QSDK-R23D3"
$stageAId = "mujoco_onset_screen"
$stageBId = "three_engine_confirmation"
$onsetOrder = @("onset_600", "onset_690", "onset_780", "onset_870")
$signedArmOrder = @("positive_heading", "negative_heading")
$stageBArmOrder = @("reference_zero", "positive_heading", "negative_heading")
$stageBEngineOrder = @("godot_jolt", "rapier_parry", "mujoco")
$stageACellIds = @(
    foreach ($onsetId in $onsetOrder) {
        foreach ($armId in $signedArmOrder) {
            "mujoco__$onsetId`__$armId"
        }
    }
)
$attemptEnvironmentNames = @(
    "SPORESPORE_QSDK_R23D3_FREEZE",
    "SPORESPORE_QSDK_R23D3_ATTEMPT",
    "SPORESPORE_QSDK_R23D3_TOKEN",
    "SPORESPORE_QSDK_R23D3_STAGE",
    "SPORESPORE_QSDK_R23D3_CELL",
    "SPORESPORE_QSDK_R23D3_ENGINE",
    "SPORESPORE_QSDK_R23D3_ATTEMPT_ROOT",
    "SPORESPORE_QSDK_R23D3_PYTHON",
    "SPORESPORE_QSDK_R23D3_POWERSHELL"
)

foreach ($path in @(
    $implementationPath, $preregistrationPath, $evaluatorPath,
    $artifactStorePath, $operationLockPath, $attestationVerifierPath,
    $runtimeMaterializationPath, $mujocoPython
)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "QSDK-R23D3 supervisor input is missing: $path"
    }
}

. $artifactStorePath
. $operationLockPath
. $attestationVerifierPath

function Assert-R23D3Exact {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) { throw $Message }
}

function Get-R23D3RawSha256 {
    param([Parameter(Mandatory)][string]$Path)
    return "sha256:" + (
        Get-FileHash -LiteralPath $Path -Algorithm SHA256
    ).Hash.ToLowerInvariant()
}

function Invoke-R23D3Git {
    param([Parameter(Mandatory)][string[]]$Arguments)
    $output = @(& git -C $repoRoot @Arguments 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw (
            "QSDK-R23D3 git failed: git $($Arguments -join ' '): " +
            ($output -join " ")
        )
    }
    return ($output -join "`n").Trim()
}

function Write-R23D3NewJson {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)]$Value
    )
    Assert-R23D3Exact (-not (Test-Path -LiteralPath $Path)) (
        "QSDK-R23D3 refuses to overwrite generated bytes: $Path"
    )
    [IO.File]::WriteAllText(
        $Path,
        ($Value | ConvertTo-Json -Depth 100 -Compress) + "`n",
        [Text.UTF8Encoding]::new($false)
    )
}

function Write-R23D3PhysicalRefusal {
    param([Parameter(Mandatory)][string]$Reason)
    $receipt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d3_physical_refusal_v1"
        campaign_id = $campaignId
        gate_id = $gateId
        refusal_stage = "before_attempt_or_world"
        reason = $Reason
        physical_process_launch_count = 0
        world_attempt_count = 0
        world_build_count = 0
        physical_acceptance_authority = $false
    }
    Write-Host (
        "QSDK_R23D3_PHYSICAL_REFUSAL " +
        ($receipt | ConvertTo-Json -Depth 20 -Compress)
    )
}

function Invoke-R23D3Process {
    param(
        [Parameter(Mandatory)][string]$FileName,
        [Parameter(Mandatory)][string[]]$Arguments,
        [Parameter(Mandatory)][string]$WorkingDirectory,
        [Collections.IDictionary]$Environment = @{},
        [int]$TimeoutSeconds = 900
    )
    $start = [Diagnostics.ProcessStartInfo]::new()
    $start.FileName = $FileName
    $start.WorkingDirectory = $WorkingDirectory
    $start.UseShellExecute = $false
    $start.CreateNoWindow = $true
    $start.RedirectStandardOutput = $true
    $start.RedirectStandardError = $true
    foreach ($name in $attemptEnvironmentNames) {
        [void]$start.Environment.Remove($name)
    }
    foreach ($entry in $Environment.GetEnumerator()) {
        $start.Environment[[string]$entry.Key] = [string]$entry.Value
    }
    foreach ($argument in $Arguments) { [void]$start.ArgumentList.Add($argument) }
    $process = [Diagnostics.Process]::new()
    $process.StartInfo = $start
    $timer = [Diagnostics.Stopwatch]::StartNew()
    Assert-R23D3Exact $process.Start() "QSDK-R23D3 failed to start $FileName"
    $stdoutTask = $process.StandardOutput.ReadToEndAsync()
    $stderrTask = $process.StandardError.ReadToEndAsync()
    $timedOut = $false
    $nextHeartbeat = 30.0
    while (-not $process.WaitForExit(1000)) {
        if ($timer.Elapsed.TotalSeconds -ge $nextHeartbeat) {
            Write-Host (
                "QSDK_R23D3_PROGRESS process=$([IO.Path]::GetFileName($FileName)) " +
                "elapsed_seconds=" + $timer.Elapsed.TotalSeconds.ToString(
                    "F1", [Globalization.CultureInfo]::InvariantCulture
                )
            )
            $nextHeartbeat += 30.0
        }
        if ($timer.Elapsed.TotalSeconds -ge $TimeoutSeconds) {
            $timedOut = $true
            try { $process.Kill($true) } catch { }
            [void]$process.WaitForExit(10000)
            break
        }
    }
    $timer.Stop()
    $result = [ordered]@{
        exit_code = if ($process.HasExited) { $process.ExitCode } else { -1 }
        timed_out = $timedOut
        duration_seconds = $timer.Elapsed.TotalSeconds
        stdout = $stdoutTask.GetAwaiter().GetResult()
        stderr = $stderrTask.GetAwaiter().GetResult()
    }
    $process.Dispose()
    return $result
}

function Get-R23D3JsonMarker {
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Prefix
    )
    $lines = @($Text -split "`r?`n" | Where-Object {
        $_.StartsWith($Prefix, [StringComparison]::Ordinal)
    })
    Assert-R23D3Exact ($lines.Count -eq 1) (
        "QSDK-R23D3 expected one '$Prefix' marker, observed $($lines.Count)"
    )
    return $lines[0].Substring($Prefix.Length) |
        ConvertFrom-Json -AsHashtable -Depth 100
}

function Invoke-R23D3Gate {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$PassPrefix,
        [string[]]$AdditionalArguments = @()
    )
    $result = Invoke-R23D3Process `
        -FileName $PowerShell `
        -Arguments (@("-NoLogo", "-NoProfile", "-File", $Path) + $AdditionalArguments) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds $GateTimeoutSeconds
    if ($result.stdout) { Write-Host ([string]$result.stdout).TrimEnd() }
    if ($result.stderr) { Write-Host ([string]$result.stderr).TrimEnd() }
    $markerCount = @(([string]$result.stdout -split "`r?`n") | Where-Object {
        $_.StartsWith($PassPrefix, [StringComparison]::Ordinal)
    }).Count
    Assert-R23D3Exact (
        -not [bool]$result.timed_out -and
        [int]$result.exit_code -eq 0 -and
        $markerCount -eq 1
    ) "QSDK-R23D3 zero-world gate failed: $Path"
    return $result
}

function Get-R23D3MediaType {
    param([Parameter(Mandatory)][string]$Path)
    switch ([IO.Path]::GetExtension($Path).ToLowerInvariant()) {
        ".json" { return "application/json" }
        ".ps1" { return "text/x-powershell" }
        ".py" { return "text/x-python" }
        ".gd" { return "text/x-gdscript" }
        ".rs" { return "text/x-rust" }
        ".toml" { return "application/toml" }
        default { return "application/octet-stream" }
    }
}

function Get-R23D3StageBCellIds {
    param([Parameter(Mandatory)][string]$OnsetId)
    Assert-R23D3Exact ($OnsetId -cin $onsetOrder) (
        "QSDK-R23D3 selected onset is invalid: $OnsetId"
    )
    return @(
        foreach ($engineId in $stageBEngineOrder) {
            foreach ($armId in $stageBArmOrder) {
                "$engineId`__$OnsetId`__$armId"
            }
        }
    )
}

function Get-R23D3SourceBindingPaths {
    param([Parameter(Mandatory)]$Implementation)
    $paths = [Collections.Generic.List[string]]::new()
    foreach ($path in @($Implementation.source_binding_policy.exact_paths)) {
        $paths.Add(([string]$path).Replace("\", "/"))
    }
    foreach ($prefix in @($Implementation.source_binding_policy.tracked_prefixes)) {
        $expanded = @((Invoke-R23D3Git @("ls-files", "--", [string]$prefix)) -split "`n" |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        Assert-R23D3Exact ($expanded.Count -gt 0) (
            "QSDK-R23D3 source prefix expanded to zero files: $prefix"
        )
        foreach ($path in $expanded) { $paths.Add($path.Replace("\", "/")) }
    }
    $duplicates = @($paths | Group-Object | Where-Object Count -gt 1)
    $duplicateNames = @(
        $duplicates | ForEach-Object { [string]$_.Name }
    )
    Assert-R23D3Exact ($duplicates.Count -eq 0) (
        "QSDK-R23D3 source binding paths contain duplicates: " +
        ($duplicateNames -join ",")
    )
    return @($paths)
}

function Get-R23D3SourceBindings {
    param([Parameter(Mandatory)]$Implementation)
    $paths = @(Get-R23D3SourceBindingPaths $Implementation)
    $bindings = [Collections.Generic.List[object]]::new()
    foreach ($relativePath in $paths) {
        $absolutePath = Join-Path $repoRoot $relativePath
        Assert-R23D3Exact (Test-Path -LiteralPath $absolutePath -PathType Leaf) (
            "QSDK-R23D3 source binding is missing: $relativePath"
        )
        $trackedOid = Invoke-R23D3Git @("rev-parse", "HEAD:$relativePath")
        $rawOid = Invoke-R23D3Git @(
            "hash-object", "--no-filters", "--", $relativePath
        )
        Assert-R23D3Exact ($trackedOid -ceq $rawOid) (
            "QSDK-R23D3 checkout bytes differ from the Git blob: $relativePath"
        )
        $bindings.Add([ordered]@{
            path = $relativePath
            raw_sha256 = Get-R23D3RawSha256 $absolutePath
            git_blob_oid = $trackedOid
            raw_checkout_equals_git_blob = $true
            media_type = Get-R23D3MediaType $relativePath
        })
    }
    return @($bindings)
}

function Assert-R23D3FrozenBindings {
    param([Parameter(Mandatory)]$Freeze)
    foreach ($binding in @($Freeze.source_bindings)) {
        $path = Join-Path $repoRoot ([string]$binding.path)
        Assert-R23D3Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$binding.raw_sha256 -ceq (Get-R23D3RawSha256 $path) -and
            [string]$binding.git_blob_oid -ceq
                (Invoke-R23D3Git @("rev-parse", "HEAD:$([string]$binding.path)")) -and
            [string]$binding.git_blob_oid -ceq
                (Invoke-R23D3Git @(
                    "hash-object", "--no-filters", "--", [string]$binding.path
                ))
        ) "QSDK-R23D3 frozen source binding changed: $([string]$binding.path)"
    }
    foreach ($runtime in @($Freeze.runtime_artifacts)) {
        $path = [IO.Path]::GetFullPath([string]$runtime.path)
        Assert-R23D3Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$runtime.raw_sha256 -ceq (Get-R23D3RawSha256 $path)
        ) "QSDK-R23D3 runtime artifact changed: $path"
    }
    foreach ($runtime in @($Freeze.external_runtime_bindings)) {
        $path = [IO.Path]::GetFullPath([string]$runtime.path)
        Assert-R23D3Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$runtime.raw_sha256 -ceq (Get-R23D3RawSha256 $path)
        ) "QSDK-R23D3 external runtime changed: $path"
    }
}

function Publish-R23D3BoundInputs {
    param(
        [Parameter(Mandatory)]$SourceBindings,
        [Parameter(Mandatory)]$RuntimeArtifacts,
        [Parameter(Mandatory)]$ExternalRuntimeBindings,
        [Parameter(Mandatory)][string]$AttestationPath
    )
    $sourceReceipts = [Collections.Generic.List[object]]::new()
    foreach ($binding in @($SourceBindings)) {
        $sourceReceipts.Add((Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath (Join-Path $repoRoot ([string]$binding.path)) `
            -MediaType ([string]$binding.media_type)))
    }
    $runtimeReceipts = [Collections.Generic.List[object]]::new()
    foreach ($runtime in @($RuntimeArtifacts)) {
        $runtimeReceipts.Add((Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath ([string]$runtime.path) `
            -MediaType ([string]$runtime.media_type)))
    }
    $externalReceipts = [Collections.Generic.List[object]]::new()
    foreach ($runtime in @($ExternalRuntimeBindings)) {
        $externalReceipts.Add((Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath ([string]$runtime.path) `
            -MediaType ([string]$runtime.media_type)))
    }
    $attestationReceipt = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $AttestationPath `
        -MediaType "application/json"
    return [ordered]@{
        source_bindings = @($sourceReceipts)
        runtime_artifacts = @($runtimeReceipts)
        external_runtime_bindings = @($externalReceipts)
        full_godot_attestation = $attestationReceipt
        physical_acceptance_authority = $false
    }
}

function Get-R23D3ExternalRuntimeBindings {
    $powerShellPath = [IO.Path]::GetFullPath(
        [string](Get-Command $PowerShell -CommandType Application).Source
    )
    return @(
        [ordered]@{
            name = "godot_jolt_host"
            path = [IO.Path]::GetFullPath($Godot)
            raw_sha256 = Get-R23D3RawSha256 $Godot
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "mujoco_python_host"
            path = [IO.Path]::GetFullPath($mujocoPython)
            raw_sha256 = Get-R23D3RawSha256 $mujocoPython
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "powershell_trace_retainer_host"
            path = $powerShellPath
            raw_sha256 = Get-R23D3RawSha256 $powerShellPath
            media_type = "application/vnd.microsoft.portable-executable"
        }
    )
}

function Get-R23D3RuntimeArtifacts {
    param([Parameter(Mandatory)]$Materialization)
    $values = @(
        [ordered]@{
            name = "locomotion_core"
            path = [IO.Path]::GetFullPath(
                [string]$Materialization.artifacts.locomotion_core
            )
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "godot_adapter"
            path = [IO.Path]::GetFullPath(
                [string]$Materialization.artifacts.godot_adapter
            )
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "rapier_worker"
            path = [IO.Path]::GetFullPath(
                [string]$Materialization.artifacts.rapier_worker
            )
            media_type = "application/vnd.microsoft.portable-executable"
        }
    )
    foreach ($value in $values) {
        Assert-R23D3Exact (Test-Path -LiteralPath $value.path -PathType Leaf) (
            "QSDK-R23D3 runtime artifact is missing: $($value.path)"
        )
        $value.raw_sha256 = Get-R23D3RawSha256 $value.path
    }
    return $values
}

function Invoke-R23D3Evaluation {
    param(
        [Parameter(Mandatory)][ValidateSet("stage-a", "complete")]
        [string]$Kind,
        [string[]]$EntryPaths = @(),
        [string]$StageAManifest = "",
        [string]$StageBManifest = ""
    )
    if ($Kind -ceq "stage-a") {
        $arguments = @($evaluatorPath, "evaluate-stage-a") + $EntryPaths
        $prefix = "QSDK_R23D3_STAGE_A_EVALUATION "
    } else {
        $arguments = @(
            $evaluatorPath, "evaluate-complete",
            "--stage-a-manifest", $StageAManifest,
            "--stage-b-manifest", $StageBManifest
        )
        $prefix = "QSDK_R23D3_COMPLETE_EVALUATION "
    }
    $result = Invoke-R23D3Process `
        -FileName $Python `
        -Arguments $arguments `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 180
    $evaluation = Get-R23D3JsonMarker -Text $result.stdout -Prefix $prefix
    return [ordered]@{ process = $result; evaluation = $evaluation }
}

function Invoke-R23D3PhysicalCell {
    param(
        [Parameter(Mandatory)][string]$StageId,
        [Parameter(Mandatory)][string]$EngineId,
        [Parameter(Mandatory)][string]$OnsetId,
        [Parameter(Mandatory)][string]$ArmId,
        [Parameter(Mandatory)][string]$SourceCommit,
        [Parameter(Mandatory)][string]$FreezePayloadPath,
        [Parameter(Mandatory)][string]$AttemptPayloadPath,
        [Parameter(Mandatory)][string]$Token,
        [Parameter(Mandatory)][string]$AttemptRoot,
        [Parameter(Mandatory)][string]$CellRoot,
        [Parameter(Mandatory)]$RuntimeArtifacts
    )
    [void][IO.Directory]::CreateDirectory($CellRoot)
    $cellId = "$EngineId`__$OnsetId`__$ArmId"
    $environment = [ordered]@{
        SPORESPORE_QSDK_R23D3_FREEZE = $FreezePayloadPath
        SPORESPORE_QSDK_R23D3_ATTEMPT = $AttemptPayloadPath
        SPORESPORE_QSDK_R23D3_TOKEN = $Token
        SPORESPORE_QSDK_R23D3_STAGE = $StageId
        SPORESPORE_QSDK_R23D3_CELL = $cellId
        SPORESPORE_QSDK_R23D3_ENGINE = $EngineId
        SPORESPORE_QSDK_R23D3_ATTEMPT_ROOT = $AttemptRoot
        SPORESPORE_QSDK_R23D3_PYTHON = $Python
        SPORESPORE_QSDK_R23D3_POWERSHELL = $PowerShell
    }
    $fileName = ""
    $arguments = @()
    $workingDirectory = $repoRoot
    $successPrefix = ""
    $failurePrefix = ""
    if ($EngineId -ceq "godot_jolt") {
        $fileName = $Godot
        $environment.APPDATA = Join-Path $CellRoot "appdata"
        $environment.LOCALAPPDATA = Join-Path $CellRoot "localappdata"
        [void][IO.Directory]::CreateDirectory($environment.APPDATA)
        [void][IO.Directory]::CreateDirectory($environment.LOCALAPPDATA)
        $arguments = @(
            "--headless", "--path", $repoRoot,
            "--log-file", (Join-Path $CellRoot "godot.log"),
            "--script", $godotWorkerResource, "--",
            "--stage", $StageId, "--onset", $OnsetId, "--arm", $ArmId,
            "--source-commit", $SourceCommit
        )
        $successPrefix = "QSDK_R23D3_GODOT_JOLT_CELL "
        $failurePrefix = "QSDK_R23D3_GODOT_JOLT_FAILURE "
    } elseif ($EngineId -ceq "rapier_parry") {
        $fileName = [string]$RuntimeArtifacts.rapier_worker
        $arguments = @(
            "--stage", $StageId, "--onset", $OnsetId, "--arm", $ArmId,
            "--source-commit", $SourceCommit
        )
        $successPrefix = "QSDK_R23D3_RAPIER_CELL "
        $failurePrefix = "QSDK_R23D3_RAPIER_FAILURE "
    } elseif ($EngineId -ceq "mujoco") {
        $fileName = $mujocoPython
        $workingDirectory = $repoRoot
        $environment.SPORESPORE_LOCOMOTION_LIBRARY =
            [string]$RuntimeArtifacts.locomotion_core
        $environment.PYTHONPATH = (
            $mujocoRoot + [IO.Path]::PathSeparator + $pythonCoreRoot
        )
        $arguments = @(
            "-m", "sporespore_mujoco_adapter.qsdk_r23d3_phase_balanced",
            "--stage", $StageId, "--onset", $OnsetId, "--arm", $ArmId,
            "--source-commit", $SourceCommit
        )
        $successPrefix = "QSDK_R23D3_MUJOCO_CELL "
        $failurePrefix = "QSDK_R23D3_MUJOCO_FAILURE "
    } else {
        throw "QSDK-R23D3 unknown physical engine: $EngineId"
    }

    Write-Host "QSDK_R23D3_CELL_BEGIN stage=$StageId cell=$cellId"
    $launchSucceeded = $false
    try {
        $result = Invoke-R23D3Process `
            -FileName $fileName `
            -Arguments $arguments `
            -WorkingDirectory $workingDirectory `
            -Environment $environment `
            -TimeoutSeconds $CellTimeoutSeconds
        $launchSucceeded = $true
    } catch {
        $result = [ordered]@{
            exit_code = -1
            timed_out = $false
            duration_seconds = 0.0
            stdout = ""
            stderr = "SUPERVISOR_PROCESS_START_EXCEPTION:$($_.Exception.Message)"
        }
    }
    $logPath = Join-Path $CellRoot "engine.log"
    [IO.File]::WriteAllText(
        $logPath,
        [string]$result.stdout + [string]$result.stderr,
        [Text.UTF8Encoding]::new($false)
    )
    $logCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $logPath `
        -MediaType "text/plain"

    $successLines = @([string]$result.stdout -split "`r?`n" | Where-Object {
        $_.StartsWith($successPrefix, [StringComparison]::Ordinal)
    })
    $failureLines = @([string]$result.stdout -split "`r?`n" | Where-Object {
        $_.StartsWith($failurePrefix, [StringComparison]::Ordinal)
    })
    $terminal = $null
    $markerKind = "supervisor_process_failure"
    try {
        if (
            $launchSucceeded -and -not [bool]$result.timed_out -and
            [int]$result.exit_code -eq 0 -and
            $successLines.Count -eq 1 -and $failureLines.Count -eq 0
        ) {
            $terminal = $successLines[0].Substring($successPrefix.Length) |
                ConvertFrom-Json -AsHashtable -Depth 100
            $markerKind = "successful_report"
        } elseif (
            $launchSucceeded -and -not [bool]$result.timed_out -and
            [int]$result.exit_code -ne 0 -and
            $failureLines.Count -eq 1 -and $successLines.Count -eq 0
        ) {
            $terminal = $failureLines[0].Substring($failurePrefix.Length) |
                ConvertFrom-Json -AsHashtable -Depth 100
            $markerKind = "worker_failure"
        }
    } catch {
        $terminal = $null
    }
    if ($null -eq $terminal) {
        $terminal = [ordered]@{
            schema_version = "sporespore_qsdk_r23d3_supervisor_process_failure_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            stage_id = $StageId
            cell_id = $cellId
            engine_id = $EngineId
            onset_id = $OnsetId
            arm_id = $ArmId
            source_commit = $SourceCommit
            process_launch_succeeded = $launchSucceeded
            process_exit_code = [int]$result.exit_code
            process_timed_out = [bool]$result.timed_out
            success_marker_count = $successLines.Count
            failure_marker_count = $failureLines.Count
            world_attempt_count_known = $false
            world_build_count_known = $false
            engine_log_sha256 = [string]$logCas.sha256
            physical_acceptance_authority = $false
        }
    }
    $terminalPath = Join-Path $CellRoot "terminal-entry.json"
    Write-R23D3NewJson -Path $terminalPath -Value $terminal
    $terminalCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $terminalPath `
        -MediaType "application/json"
    Write-Host (
        "QSDK_R23D3_CELL_RETAINED stage=$StageId cell=$cellId " +
        "marker=$markerKind terminal_sha256=$([string]$terminalCas.sha256)"
    )
    return [ordered]@{
        stage_id = $StageId
        cell_id = $cellId
        engine_id = $EngineId
        onset_id = $OnsetId
        arm_id = $ArmId
        process_launch_succeeded = $launchSucceeded
        process_exit_code = [int]$result.exit_code
        process_timed_out = [bool]$result.timed_out
        process_duration_seconds = [double]$result.duration_seconds
        terminal_marker_kind = $markerKind
        terminal_entry_cas = $terminalCas
        engine_log_cas = $logCas
        physical_acceptance_authority = $false
    }
}

function New-R23D3StageAuthorization {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$AttemptId,
        [Parameter(Mandatory)][string]$Token,
        [Parameter(Mandatory)][string]$SourceCommit,
        [Parameter(Mandatory)][string]$FreezeSha256,
        [Parameter(Mandatory)][string]$AttemptRoot,
        [Parameter(Mandatory)][string[]]$OrderedStageACellIds,
        [Parameter(Mandatory)][AllowEmptyCollection()][string[]]$OrderedStageBCellIds,
        [Parameter(Mandatory)][string]$SelectedOnsetId,
        [Parameter(Mandatory)][string]$StageAuthorizationId,
        [Parameter(Mandatory)]$InputCas,
        [Parameter(Mandatory)]$ZeroWorldReceipt,
        [Parameter(Mandatory)][string]$AttestationSha256,
        [string]$ParentAuthorizationSha256 = ""
    )
    $attempt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d3_attempt_v1"
        attempt_id = $AttemptId
        stage_authorization_id = $StageAuthorizationId
        parent_stage_authorization_sha256 = $ParentAuthorizationSha256
        campaign_id = $campaignId
        gate_id = $gateId
        implementation_contract_raw_sha256 = Get-R23D3RawSha256 $implementationPath
        freeze_raw_sha256 = $FreezeSha256
        source_commit = $SourceCommit
        authorization_token = $Token
        attempt_root = $AttemptRoot
        selected_onset_id = $SelectedOnsetId
        ordered_stage_a_cell_ids = $OrderedStageACellIds
        ordered_stage_b_cell_ids = $OrderedStageBCellIds
        physical_execution_authorized = $true
        single_use_supervisor_authorization = $true
        source_worktree_clean = $true
        source_matches_live_github_main = $true
        operation_lock_held = $true
        full_godot_attestation_valid = $true
        full_godot_attestation_sha256 = $AttestationSha256
        content_addressed_inputs_retained = $true
        content_addressed_inputs = $InputCas
        complete_zero_world_gate_passed = $true
        zero_world_receipt = $ZeroWorldReceipt
        one_shot_attempt_unconsumed = $true
        replacement_or_selective_rerun_permitted = $false
        stage_a_reports_may_substitute_for_stage_b = $false
        physical_acceptance_authority = $false
    }
    Write-R23D3NewJson -Path $Path -Value $attempt
    return Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $Path `
        -MediaType "application/json"
}

function Invoke-R23D3PhysicalCampaign {
    param(
        [Parameter(Mandatory)]$Source,
        [Parameter(Mandatory)]$Attestation,
        [Parameter(Mandatory)]$ZeroWorldReceipt,
        [Parameter(Mandatory)]$Implementation
    )
    $sourceAfterPreflight = Get-SporeSporeAttestationSourceIdentity `
        -RepoRoot $repoRoot `
        -RequireCleanPushedLive
    Assert-R23D3Exact (
        [string]$sourceAfterPreflight.commit -ceq [string]$Source.commit -and
        [string]$sourceAfterPreflight.tree_git_oid -ceq [string]$Source.tree_git_oid
    ) "QSDK-R23D3 source changed during the zero-world gate"
    Assert-R23D3Exact (
        [string](Invoke-R23D3Git @("status", "--porcelain=v1", "--untracked-files=all")) `
            -ceq ""
    ) "QSDK-R23D3 physical source is not clean after the zero-world gate"

    $evidenceRoot = Get-SporeSporeArtifactEvidenceRoot -RepoRoot $repoRoot
    $prior = @(Get-ChildItem -LiteralPath $evidenceRoot -Directory |
        Where-Object {
            $_.Name -like "qsdk-r23d3-*" -and (
                (Test-Path -LiteralPath (Join-Path $_.FullName "stage-a-authorization.json")) -or
                (Test-Path -LiteralPath (Join-Path $_.FullName "completion.json"))
            )
        })
    Assert-R23D3Exact ($prior.Count -eq 0) (
        "QSDK-R23D3 one-shot identity already exists; rerun is forbidden"
    )
    $resolvedOutput = if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
        Join-Path $evidenceRoot (
            "qsdk-r23d3-" + [DateTime]::UtcNow.ToString("yyyyMMddTHHmmssZ")
        )
    } else { [IO.Path]::GetFullPath($OutputRoot) }
    $evidencePrefix = $evidenceRoot.TrimEnd("\", "/") +
        [IO.Path]::DirectorySeparatorChar
    Assert-R23D3Exact (
        $resolvedOutput.StartsWith(
            $evidencePrefix, [StringComparison]::OrdinalIgnoreCase
        ) -and
        -not (Test-Path -LiteralPath $resolvedOutput)
    ) "QSDK-R23D3 output must be a new directory under $evidenceRoot"
    [void][IO.Directory]::CreateDirectory($resolvedOutput)

    $attemptConsumed = $false
    $completionPath = Join-Path $resolvedOutput "completion.json"
    try {
        . $runtimeMaterializationPath
        Assert-R23D3Exact ($null -ne (Get-Command `
            -Name Initialize-SporeSporeR23D3AttemptRuntimeArtifacts `
            -CommandType Function -ErrorAction SilentlyContinue)) (
            "QSDK-R23D3 reproducible runtime helper surface is missing"
        )
        $materialization = Initialize-SporeSporeR23D3AttemptRuntimeArtifacts `
            -RepoRoot $repoRoot `
            -SourceCommit ([string]$Source.commit) `
            -TargetRoot (Join-Path $sdkRoot "target")
        $runtimeArtifacts = Get-R23D3RuntimeArtifacts $materialization
        $runtimeMap = [ordered]@{
            locomotion_core = [string]$materialization.artifacts.locomotion_core
            godot_adapter = [string]$materialization.artifacts.godot_adapter
            rapier_worker = [string]$materialization.artifacts.rapier_worker
        }
        $sourceBindings = Get-R23D3SourceBindings $Implementation
        $externalRuntimeBindings = Get-R23D3ExternalRuntimeBindings
        $inputCas = Publish-R23D3BoundInputs `
            -SourceBindings $sourceBindings `
            -RuntimeArtifacts $runtimeArtifacts `
            -ExternalRuntimeBindings $externalRuntimeBindings `
            -AttestationPath $FullConformanceAttestation

        $freeze = [ordered]@{
            schema_version = "sporespore_qsdk_r23d3_physical_freeze_v1"
            status = "frozen_supervisor_only_physical_authorized"
            campaign_id = $campaignId
            gate_id = $gateId
            preregistration_raw_sha256 = Get-R23D3RawSha256 $preregistrationPath
            implementation_contract_raw_sha256 = Get-R23D3RawSha256 $implementationPath
            source_commit = [string]$Source.commit
            source_tree_git_oid = [string]$Source.tree_git_oid
            origin_main_commit = [string]$Source.origin_main
            live_github_main_commit = [string]$Source.live_github_main
            source_bindings = $sourceBindings
            runtime_artifacts = $runtimeArtifacts
            external_runtime_bindings = $externalRuntimeBindings
            content_addressed_inputs = $inputCas
            full_godot_attestation_sha256 = [string]$Attestation.sha256
            complete_zero_world_gate_passed = $true
            zero_world_receipt = $ZeroWorldReceipt
            declared_stage_a_world_count = 8
            declared_stage_b_world_count_if_selected = 9
            serial_execution_required = $true
            single_supervisor_attempt_required = $true
            stage_a_reports_may_substitute_for_stage_b = $false
            replacement_or_selective_rerun_permitted = $false
            source_checkout_bytes_equal_git_blobs = $true
            reproducible_runtime_materialization_passed = $true
            physical_execution_authorized = $true
            physical_acceptance_authority = $false
        }
        $freezePath = Join-Path $resolvedOutput "physical-freeze.json"
        Write-R23D3NewJson -Path $freezePath -Value $freeze
        $freezeCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $freezePath `
            -MediaType "application/json"
        Assert-R23D3FrozenBindings $freeze

        $attemptId = [guid]::NewGuid().ToString("N")
        $stageAToken = [guid]::NewGuid().ToString("N")
        $stageAAuthorizationPath = Join-Path $resolvedOutput "stage-a-authorization.json"
        $stageAAuthorizationCas = New-R23D3StageAuthorization `
            -Path $stageAAuthorizationPath `
            -AttemptId $attemptId `
            -Token $stageAToken `
            -SourceCommit ([string]$Source.commit) `
            -FreezeSha256 ([string]$freezeCas.sha256) `
            -AttemptRoot $resolvedOutput `
            -OrderedStageACellIds $stageACellIds `
            -OrderedStageBCellIds @() `
            -SelectedOnsetId "NONE" `
            -StageAuthorizationId "stage_a" `
            -InputCas $inputCas `
            -ZeroWorldReceipt $ZeroWorldReceipt `
            -AttestationSha256 ([string]$Attestation.sha256)
        $attemptConsumed = $true

        $stageACells = [Collections.Generic.List[object]]::new()
        foreach ($cellId in $stageACellIds) {
            $parts = $cellId -split "__", 3
            $stageACells.Add((Invoke-R23D3PhysicalCell `
                -StageId $stageAId `
                -EngineId "mujoco" `
                -OnsetId $parts[1] `
                -ArmId $parts[2] `
                -SourceCommit ([string]$Source.commit) `
                -FreezePayloadPath ([string]$freezeCas.payload_path) `
                -AttemptPayloadPath ([string]$stageAAuthorizationCas.payload_path) `
                -Token $stageAToken `
                -AttemptRoot $resolvedOutput `
                -CellRoot (Join-Path $resolvedOutput ("stage-a\" + $cellId)) `
                -RuntimeArtifacts $runtimeMap))
        }
        $stageAPaths = @($stageACells | ForEach-Object {
            [string]$_.terminal_entry_cas.payload_path
        })
        $stageAManifestPath = Join-Path $resolvedOutput "stage-a-terminal-paths.json"
        Write-R23D3NewJson -Path $stageAManifestPath -Value $stageAPaths
        $stageAManifestCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $stageAManifestPath `
            -MediaType "application/json"
        $stageAEvaluationResult = Invoke-R23D3Evaluation `
            -Kind "stage-a" -EntryPaths $stageAPaths
        $stageAEvaluationPath = Join-Path $resolvedOutput "stage-a-evaluation.json"
        Write-R23D3NewJson `
            -Path $stageAEvaluationPath `
            -Value $stageAEvaluationResult.evaluation
        $stageAEvaluationCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $stageAEvaluationPath `
            -MediaType "application/json"

        $stageBCells = [Collections.Generic.List[object]]::new()
        $stageBAuthorizationCas = $null
        $selectedOnset = [string]$stageAEvaluationResult.evaluation.selected_onset_id
        if ([bool]$stageAEvaluationResult.evaluation.stage_b_launch_authorized) {
            Assert-R23D3Exact (
                [bool]$stageAEvaluationResult.evaluation.valid -and
                $selectedOnset -cin $onsetOrder -and
                [int]$stageAEvaluationResult.process.exit_code -eq 0
            ) "QSDK-R23D3 Stage B authorization state is inconsistent"
            $stageBCellIds = Get-R23D3StageBCellIds $selectedOnset
            $stageBToken = [guid]::NewGuid().ToString("N")
            $stageBAuthorizationPath = Join-Path `
                $resolvedOutput `
                "stage-b-authorization.json"
            $stageBAuthorizationCas = New-R23D3StageAuthorization `
                -Path $stageBAuthorizationPath `
                -AttemptId $attemptId `
                -Token $stageBToken `
                -SourceCommit ([string]$Source.commit) `
                -FreezeSha256 ([string]$freezeCas.sha256) `
                -AttemptRoot $resolvedOutput `
                -OrderedStageACellIds $stageACellIds `
                -OrderedStageBCellIds $stageBCellIds `
                -SelectedOnsetId $selectedOnset `
                -StageAuthorizationId "stage_b" `
                -InputCas $inputCas `
                -ZeroWorldReceipt $ZeroWorldReceipt `
                -AttestationSha256 ([string]$Attestation.sha256) `
                -ParentAuthorizationSha256 ([string]$stageAAuthorizationCas.sha256)
            foreach ($cellId in $stageBCellIds) {
                $parts = $cellId -split "__", 3
                $stageBCells.Add((Invoke-R23D3PhysicalCell `
                    -StageId $stageBId `
                    -EngineId $parts[0] `
                    -OnsetId $parts[1] `
                    -ArmId $parts[2] `
                    -SourceCommit ([string]$Source.commit) `
                    -FreezePayloadPath ([string]$freezeCas.payload_path) `
                    -AttemptPayloadPath ([string]$stageBAuthorizationCas.payload_path) `
                    -Token $stageBToken `
                    -AttemptRoot $resolvedOutput `
                    -CellRoot (Join-Path $resolvedOutput ("stage-b\" + $cellId)) `
                    -RuntimeArtifacts $runtimeMap))
            }
        } else {
            Assert-R23D3Exact (
                -not [bool]$stageAEvaluationResult.evaluation.valid -or
                $selectedOnset -ceq "NONE"
            ) "QSDK-R23D3 Stage B was withheld for an unknown selector state"
        }

        $stageBPaths = @($stageBCells | ForEach-Object {
            [string]$_.terminal_entry_cas.payload_path
        })
        $stageBManifestPath = Join-Path $resolvedOutput "stage-b-terminal-paths.json"
        Write-R23D3NewJson -Path $stageBManifestPath -Value $stageBPaths
        $stageBManifestCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $stageBManifestPath `
            -MediaType "application/json"
        $completeResult = Invoke-R23D3Evaluation `
            -Kind "complete" `
            -StageAManifest ([string]$stageAManifestCas.payload_path) `
            -StageBManifest ([string]$stageBManifestCas.payload_path)
        $completeEvaluationPath = Join-Path $resolvedOutput "complete-evaluation.json"
        Write-R23D3NewJson `
            -Path $completeEvaluationPath `
            -Value $completeResult.evaluation
        $completeEvaluationCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $completeEvaluationPath `
            -MediaType "application/json"

        $classification = [string]$completeResult.evaluation.classification
        $validResult = -not $classification.StartsWith(
            "invalid", [StringComparison]::Ordinal
        )
        $report = [ordered]@{
            schema_version = "sporespore_qsdk_r23d3_campaign_report_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            source = $Source
            attempt_id = $attemptId
            implementation_contract_raw_sha256 = Get-R23D3RawSha256 $implementationPath
            freeze_cas = $freezeCas
            stage_a_authorization_cas = $stageAAuthorizationCas
            stage_b_authorization_cas = $stageBAuthorizationCas
            stage_a_manifest_cas = $stageAManifestCas
            stage_b_manifest_cas = $stageBManifestCas
            stage_a_evaluation_cas = $stageAEvaluationCas
            complete_evaluation_cas = $completeEvaluationCas
            ordered_stage_a_cells = @($stageACells)
            ordered_stage_b_cells = @($stageBCells)
            stage_a_evaluation = $stageAEvaluationResult.evaluation
            complete_evaluation = $completeResult.evaluation
            selected_onset_id = $selectedOnset
            stage_b_launched = $stageBCells.Count -gt 0
            stage_a_world_count = 8
            stage_b_world_count = $stageBCells.Count
            result_classification = $classification
            development_result_valid = $validResult
            claims = [ordered]@{
                development_screen_only = $true
                command_conditioned_turning = $false
                bilateral_signed_turning = $false
                portable_basic_turning = $false
                cross_engine_equivalence = $false
                q_sdk_r23_satisfied = $false
                release_authorized = $false
                physical_acceptance_authority = $false
            }
        }
        $reportPath = Join-Path $resolvedOutput "report.json"
        Write-R23D3NewJson -Path $reportPath -Value $report
        $reportCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $reportPath `
            -MediaType "application/json"
        $completion = [ordered]@{
            schema_version = "sporespore_qsdk_r23d3_completion_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            status = if ($validResult) {
                "$classification`_first_attempt"
            } else { "invalid_or_incomplete_first_attempt" }
            source_commit = [string]$Source.commit
            attempt_id = $attemptId
            selected_onset_id = $selectedOnset
            stage_a_terminal_entry_count = $stageACells.Count
            stage_b_terminal_entry_count = $stageBCells.Count
            result_classification = $classification
            report_cas = $reportCas
            one_shot_identity_consumed = $true
            same_identity_rerun_allowed = $false
            q_sdk_r23_satisfied = $false
            cross_engine_equivalence = $false
            release_authorized = $false
            physical_acceptance_authority = $false
        }
        Write-R23D3NewJson -Path $completionPath -Value $completion
        $completionCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $completionPath `
            -MediaType "application/json"
        Write-Host (
            "QSDK_R23D3_PHYSICAL_COMPLETE classification=$classification " +
            "selected_onset=$selectedOnset stage_a_cells=$($stageACells.Count) " +
            "stage_b_cells=$($stageBCells.Count) " +
            "report_sha256=$([string]$reportCas.sha256) " +
            "completion_sha256=$([string]$completionCas.sha256) " +
            "turning=False equivalence=False release=False"
        )
        if (-not $validResult) {
            throw "QSDK-R23D3 retained an invalid or incomplete first attempt: $resolvedOutput"
        }
    } catch {
        if ($attemptConsumed -and -not (Test-Path -LiteralPath $completionPath)) {
            $emergency = [ordered]@{
                schema_version = "sporespore_qsdk_r23d3_completion_v1"
                campaign_id = $campaignId
                gate_id = $gateId
                status = "invalid_or_incomplete_first_attempt"
                source_commit = [string]$Source.commit
                failure_code = "SUPERVISOR_INFRASTRUCTURE_EXCEPTION"
                failure_detail = $_.Exception.Message
                one_shot_identity_consumed = $true
                same_identity_rerun_allowed = $false
                q_sdk_r23_satisfied = $false
                cross_engine_equivalence = $false
                release_authorized = $false
                physical_acceptance_authority = $false
            }
            Write-R23D3NewJson -Path $completionPath -Value $emergency
            [void](Publish-SporeSporeContentAddressedArtifact `
                -RepoRoot $repoRoot -ArtifactPath $completionPath `
                -MediaType "application/json")
        }
        throw
    }
}

Assert-R23D3Exact ($PreflightOnly.IsPresent -xor $RunPhysical.IsPresent) (
    "Specify exactly one of -PreflightOnly or -RunPhysical"
)
Assert-R23D3Exact (
    $RunPhysical.IsPresent -or (
        [string]::IsNullOrWhiteSpace($FullConformanceAttestation) -and
        [string]::IsNullOrWhiteSpace($OutputRoot)
    )
) "-FullConformanceAttestation and -OutputRoot require -RunPhysical"
if ($RunPhysical -and (Test-Path -LiteralPath $closurePath -PathType Leaf)) {
    Write-R23D3PhysicalRefusal -Reason "r23d3_identity_closed"
    throw "QSDK-R23D3 CLOSED: the one-shot identity is consumed; rerun is forbidden"
}
if ($RunPhysical -and [string]::IsNullOrWhiteSpace($FullConformanceAttestation)) {
    Write-R23D3PhysicalRefusal -Reason "matching_full_godot_v2_attestation_required"
    throw "QSDK-R23D3 physical execution requires a matching full-Godot V2 attestation"
}

Assert-R23D3Exact (
    (Invoke-R23D3Git @("rev-parse", "--show-toplevel")).Replace("/", "\") -ceq
        $repoRoot -and
    (Invoke-R23D3Git @("remote", "get-url", "origin")) -ceq
        "https://github.com/Slagathore/sporespore.git"
) "QSDK-R23D3 supervisor repository identity mismatch"
Assert-R23D3Exact (Test-Path -LiteralPath $Godot -PathType Leaf) (
    "QSDK-R23D3 Godot executable is missing: $Godot"
)

$implementation = Get-Content -Raw -LiteralPath $implementationPath |
    ConvertFrom-Json -AsHashtable -Depth 100
$preregistration = Get-Content -Raw -LiteralPath $preregistrationPath |
    ConvertFrom-Json -AsHashtable -Depth 100
Assert-R23D3Exact (
    [string]$implementation.schema_version -ceq
        "sporespore_qsdk_r23d3_implementation_contract_v1" -and
    [string]$implementation.status -ceq
        "implementation_complete_physical_unauthorized_pending_clean_pushed_freeze" -and
    [string]$implementation.campaign_id -ceq $campaignId -and
    [string]$implementation.gate_id -ceq $gateId -and
    [string]$implementation.supervisor.path -ceq
        "sdk/run_qsdk_r23d3_supervisor.ps1" -and
    [int]$implementation.supervisor.stage_a_world_count -eq 8 -and
    [int]$implementation.supervisor.stage_b_world_count_if_launched -eq 9 -and
    [bool]$implementation.supervisor.stage_a_serial_without_outcome_early_stop -and
    [bool]$implementation.supervisor.stage_b_serial_without_outcome_early_stop -and
    [bool]$implementation.supervisor.stage_a_reports_may_substitute_for_stage_b_mujoco_reports -eq $false -and
    [bool]$implementation.supervisor.replacement_or_selective_rerun_permitted -eq $false -and
    [bool]$implementation.supervisor.single_supervisor_attempt_required -and
    [bool]$implementation.supervisor.stage_a_and_conditional_stage_b_share_one_attempt_id -and
    [bool]$implementation.supervisor.stage_a_authorization_is_immutable_before_first_stage_a_world -and
    [bool]$implementation.supervisor.stage_b_authorization_is_fresh_immutable_and_created_only_after_valid_selection -and
    [bool]$implementation.supervisor.stage_a_authorization_is_never_mutated_to_open_stage_b -and
    [bool]$implementation.supervisor.source_binding_path_composer_exercised_in_preflight -and
    [string]$implementation.runtime_freeze_recipe.materialization_path -ceq
        "sdk/r23d3_reproducible_runtime_materialization.ps1" -and
    [bool]$implementation.runtime_freeze_recipe.source_bindings_must_equal_git_blob_bytes -and
    [bool]$implementation.runtime_freeze_recipe.msvc_brepro_required -and
    -not [bool]$implementation.authorization.physical_execution_authorized -and
    -not [bool]$implementation.authorization.physical_acceptance_authority -and
    [int]$implementation.authorization.world_attempt_count -eq 0 -and
    [int]$implementation.authorization.world_build_count -eq 0
) "QSDK-R23D3 implementation contract identity changed"
Assert-R23D3Exact (
    [string]$preregistration.schema_version -ceq
        "sporespore_qsdk_r23d3_phase_balanced_preregistration_v1" -and
    [string]$preregistration.campaign_id -ceq $campaignId -and
    [string]$preregistration.gate_id -ceq $gateId -and
    [int]$preregistration.command_schedule.controller_semantic_step_count -eq 2992 -and
    [int]$preregistration.stage_a_mujoco_onset_screen.declared_cell_count -eq 8 -and
    [int]$preregistration.stage_b_three_engine_confirmation.declared_cell_count_if_launched -eq 9 -and
    -not [bool]$preregistration.authorization.physical_execution_authorized
) "QSDK-R23D3 preregistration identity changed"

$declaredPaths = @(Get-R23D3SourceBindingPaths $implementation)
Assert-R23D3Exact (
    $declaredPaths.Count -eq 63
) "QSDK-R23D3 declared source binding cardinality changed"

$physicalSource = $null
$physicalAttestation = $null
$operationLock = $null
if ($RunPhysical) {
    $physicalSource = Get-SporeSporeAttestationSourceIdentity `
        -RepoRoot $repoRoot `
        -RequireCleanPushedLive
    $physicalAttestation = Test-SporeSporeFullConformanceAttestationFile `
        -RepoRoot $repoRoot `
        -Godot $Godot `
        -AttestationPath $FullConformanceAttestation
    if (-not [bool]$physicalAttestation.ok) {
        Write-R23D3PhysicalRefusal -Reason (
            "full_godot_v2_attestation_invalid:" +
            (@($physicalAttestation.failure_codes) -join ",")
        )
        throw "QSDK-R23D3 full-conformance attestation is invalid"
    }
    $operationLock = Enter-SporeSporeLocomotionOperationLock -Role physical
} else {
    $operationLock = Enter-SporeSporeLocomotionOperationLock -Role conformance
}
if (-not [bool]$operationLock.acquired) {
    if ($RunPhysical) {
        Write-R23D3PhysicalRefusal -Reason "global_locomotion_operation_lock_held"
    }
    throw "QSDK-R23D3 global locomotion operation lock is held"
}

$scratchRoot = Join-Path $sdkRoot (
    "target\qsdk-r23d3-supervisor-preflight\" + [guid]::NewGuid().ToString("N")
)
[void][IO.Directory]::CreateDirectory($scratchRoot)
try {
    # Materialize all three local runtime entrypoints before the worker gates.
    # This is zero-world; the physical path repeats the build from its verified
    # clean commit and hashes those exact outputs into the runtime freeze.
    . $runtimeMaterializationPath
    $developmentCommit = Invoke-R23D3Git @("rev-parse", "HEAD")
    $developmentRuntime = Initialize-SporeSporeR23D3AttemptRuntimeArtifacts `
        -RepoRoot $repoRoot `
        -SourceCommit $developmentCommit `
        -TargetRoot (Join-Path $sdkRoot "target")
    Assert-R23D3Exact (
        [string]$developmentRuntime.source_commit -ceq $developmentCommit -and
        -not [bool]$developmentRuntime.physical_acceptance_authority
    ) "QSDK-R23D3 zero-world runtime materialization failed"

    $gateSpecs = @(
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d3_phase_balanced_preflight.ps1"
            prefix = "QSDK_R23D3_STAGE_ZERO_PASS "
            arguments = @("-Python", $Python)
        },
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d3_mujoco_worker_preflight.ps1"
            prefix = "QSDK_R23D3_MUJOCO_WORKER_PASS "
            arguments = @()
        },
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d3_rapier_worker_preflight.ps1"
            prefix = "QSDK_R23D3_RAPIER_WORKER_PASS "
            arguments = @()
        },
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d3_godot_jolt_worker_preflight.ps1"
            prefix = "QSDK_R23D3_GODOT_JOLT_WORKER_PASS "
            arguments = @("-Godot", $Godot)
        }
    )
    $gateResults = [Collections.Generic.List[object]]::new()
    foreach ($spec in $gateSpecs) {
        $gateResults.Add((Invoke-R23D3Gate `
            -Path ([string]$spec.path) `
            -PassPrefix ([string]$spec.prefix) `
            -AdditionalArguments @($spec.arguments)))
    }

    $evaluatorTests = Invoke-R23D3Process `
        -FileName $Python `
        -Arguments @(
            "-m", "unittest", "-v",
            "test_r23d3_physical_evaluator"
        ) `
        -WorkingDirectory (Join-Path $sdkRoot "turning") `
        -TimeoutSeconds 180
    if ($evaluatorTests.stdout) { Write-Host ([string]$evaluatorTests.stdout).TrimEnd() }
    if ($evaluatorTests.stderr) { Write-Host ([string]$evaluatorTests.stderr).TrimEnd() }
    Assert-R23D3Exact (
        -not [bool]$evaluatorTests.timed_out -and
        [int]$evaluatorTests.exit_code -eq 0
    ) "QSDK-R23D3 production evaluator tests failed"

    $physicalBypass = Invoke-R23D3Process `
        -FileName $PowerShell `
        -Arguments @(
            "-NoLogo", "-NoProfile", "-File", $PSCommandPath, "-RunPhysical"
        ) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60
    Assert-R23D3Exact (
        -not [bool]$physicalBypass.timed_out -and
        [int]$physicalBypass.exit_code -ne 0
    ) "QSDK-R23D3 direct physical bypass did not refuse"
    $refusal = Get-R23D3JsonMarker `
        -Text $physicalBypass.stdout `
        -Prefix "QSDK_R23D3_PHYSICAL_REFUSAL "
    Assert-R23D3Exact (
        [string]$refusal.refusal_stage -ceq "before_attempt_or_world" -and
        [int]$refusal.physical_process_launch_count -eq 0 -and
        [int]$refusal.world_attempt_count -eq 0 -and
        [int]$refusal.world_build_count -eq 0 -and
        -not [bool]$refusal.physical_acceptance_authority
    ) "QSDK-R23D3 physical refusal receipt changed"

    $receipt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d3_supervisor_preflight_v1"
        campaign_id = $campaignId
        gate_id = $gateId
        implementation_contract_raw_sha256 = Get-R23D3RawSha256 $implementationPath
        declared_source_binding_count = $declaredPaths.Count
        stage_zero_gate_pass_count = 1
        worker_gate_pass_count = 3
        production_evaluator_test_count = 10
        physical_authorization_refusal_count = 1
        stage_a_declared_cell_count = 8
        stage_b_declared_cell_count_if_selected = 9
        possible_worker_identity_count = 44
        exact_controller_horizon_step_count = 2992
        actual_physical_process_launch_count = 0
        actual_world_attempt_count = 0
        actual_world_build_count = 0
        physical_execution_authorized = $RunPhysical.IsPresent
        command_conditioned_turning = $false
        bilateral_signed_turning = $false
        portable_basic_turning = $false
        cross_engine_equivalence = $false
        q_sdk_r23_satisfied = $false
        release_authorized = $false
        physical_acceptance_authority = $false
    }
    Write-Host (
        "QSDK_R23D3_SUPERVISOR_PREFLIGHT " +
        ($receipt | ConvertTo-Json -Depth 100 -Compress)
    )
    Write-Host (
        "QSDK_R23D3_SUPERVISOR_PASS stage_zero=1 workers=3 " +
        "evaluator_tests=10 physical_refusal=1 stage_a_cells=8 " +
        "stage_b_cells=9 possible_identities=44 horizon=2992 " +
        "actual_worlds=0 physical_authority=False"
    )
    if ($RunPhysical) {
        Invoke-R23D3PhysicalCampaign `
            -Source $physicalSource `
            -Attestation $physicalAttestation `
            -ZeroWorldReceipt $receipt `
            -Implementation $implementation
    }
} finally {
    if (Test-Path -LiteralPath $scratchRoot -PathType Container) {
        Remove-Item -LiteralPath $scratchRoot -Recurse -Force
    }
    if ($null -ne $operationLock) {
        Exit-SporeSporeLocomotionOperationLock $operationLock
    }
}
