#requires -Version 7.0

[CmdletBinding()]
param(
    [switch]$PreflightOnly,
    [switch]$RunPhysical,
    [string]$FullConformanceAttestation = "",
    [string]$OutputRoot = "",
    [string]$Python = "python",
    [string]$Godot = (
        "C:\Users\Cole\CodeStuff\Misc\Godot\" +
        "Godot_v4.7-stable_mono_win64_console.exe"
    ),
    [ValidateRange(60, 1800)][int]$GateTimeoutSeconds = 900,
    [ValidateRange(300, 1800)][int]$CellTimeoutSeconds = 600
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $false

$sdkRoot = [IO.Path]::GetFullPath($PSScriptRoot)
$repoRoot = [IO.Path]::GetFullPath((Split-Path -Parent $sdkRoot))
$contractPath = Join-Path $sdkRoot "turning\r23d2_development_contract_v1.json"
$freezePath = Join-Path $sdkRoot "turning\r23d2_physical_freeze_v1.json"
$evaluatorPath = Join-Path $sdkRoot "turning\r23d2_development.py"
$evaluatorGatePath = Join-Path $sdkRoot "run_qsdk_r23d2_development_preflight.ps1"
$oracleGatePath = Join-Path $sdkRoot "run_qsdk_r23d2_oracle_preflight.ps1"
$artifactStorePath = Join-Path $sdkRoot "content_addressed_artifact_store.ps1"
$operationLockPath = Join-Path $sdkRoot "locomotion_operation_lock.ps1"
$attestationVerifierPath = Join-Path $sdkRoot "locomotion_full_conformance_attestation.ps1"
$reproducibleRuntimePath = Join-Path $sdkRoot "r23d2_reproducible_runtime_materialization.ps1"
$godotWorkerResource = "res://tests/test_sdk_qsdk_r23d2_godot_jolt_worker.gd"
$rapierBinaryPath = Join-Path $sdkRoot "target\debug\qsdk_r23d2_heading_response.exe"
$mujocoRoot = Join-Path $sdkRoot "adapters\mujoco"
$mujocoPython = Join-Path $mujocoRoot ".venv\Scripts\python.exe"
$pythonCoreRoot = Join-Path $sdkRoot "python"
$coreLibraryPath = Join-Path $sdkRoot "target\release\sporespore_locomotion_core.dll"
$campaignId = "QSDK-R23D2-THREE-ENGINE-HEADING-RESPONSE-DEVELOPMENT"
$gateId = "QSDK-R23D2"
# The physical attempt is immutable. This guard precedes attestation, source,
# runtime, output-root, and worker handling so no R23D2 world can reopen.
$physicalIdentityClosed = $true
$engineOrder = @("godot_jolt", "rapier_parry", "mujoco")
$armOrder = @("reference_zero", "positive_heading", "negative_heading")
$orderedCellIds = @(
    foreach ($engineId in $engineOrder) {
        foreach ($armId in $armOrder) { "$engineId`__$armId" }
    }
)
$attemptEnvironmentNames = @(
    "SPORESPORE_QSDK_R23D2_ATTEMPT",
    "SPORESPORE_QSDK_R23D2_TOKEN",
    "SPORESPORE_QSDK_R23D2_CELL",
    "SPORESPORE_QSDK_R23D2_ENGINE"
)

. $artifactStorePath
. $operationLockPath
. $attestationVerifierPath

function Assert-R23D2Exact {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) { throw $Message }
}

function Get-R23D2RawSha256 {
    param([Parameter(Mandatory)][string]$Path)
    return "sha256:" + (
        Get-FileHash -LiteralPath $Path -Algorithm SHA256
    ).Hash.ToLowerInvariant()
}

function Invoke-R23D2Git {
    param([Parameter(Mandatory)][string[]]$Arguments)
    $output = @(& git -C $repoRoot @Arguments 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw "QSDK-R23D2 git failed: git $($Arguments -join ' '): $($output -join ' ')"
    }
    return ($output -join "`n").Trim()
}

function Write-R23D2PhysicalRefusal {
    param([Parameter(Mandatory)][string]$Reason)
    $refusal = [ordered]@{
        schema_version = "sporespore_qsdk_r23d2_physical_refusal_v1"
        campaign_id = $campaignId
        gate_id = $gateId
        refusal_stage = "before_attestation_or_world"
        reason = $Reason
        physical_process_launch_count = 0
        world_attempt_count = 0
        world_build_count = 0
        physical_acceptance_authority = $false
    }
    Write-Host (
        "QSDK_R23D2_PHYSICAL_REFUSAL " +
        ($refusal | ConvertTo-Json -Depth 10 -Compress)
    )
}

function Write-R23D2NewJson {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)]$Value
    )
    Assert-R23D2Exact (-not (Test-Path -LiteralPath $Path)) (
        "QSDK-R23D2 refuses to overwrite generated bytes: $Path"
    )
    [IO.File]::WriteAllText(
        $Path,
        ($Value | ConvertTo-Json -Depth 100 -Compress) + "`n",
        [Text.UTF8Encoding]::new($false)
    )
}

function Invoke-R23D2Process {
    param(
        [Parameter(Mandatory)][string]$FileName,
        [Parameter(Mandatory)][string[]]$Arguments,
        [Parameter(Mandatory)][string]$WorkingDirectory,
        [Collections.IDictionary]$Environment = @{},
        [int]$TimeoutSeconds = 900
    )
    $start = [Diagnostics.ProcessStartInfo]::new()
    $start.FileName = $FileName
    $start.WorkingDirectory = $WorkingDirectory
    $start.UseShellExecute = $false
    $start.CreateNoWindow = $true
    $start.RedirectStandardOutput = $true
    $start.RedirectStandardError = $true
    foreach ($name in $attemptEnvironmentNames) {
        [void]$start.Environment.Remove($name)
    }
    foreach ($entry in $Environment.GetEnumerator()) {
        $start.Environment[[string]$entry.Key] = [string]$entry.Value
    }
    foreach ($argument in $Arguments) { [void]$start.ArgumentList.Add($argument) }
    $process = [Diagnostics.Process]::new()
    $process.StartInfo = $start
    $timer = [Diagnostics.Stopwatch]::StartNew()
    Assert-R23D2Exact $process.Start() "QSDK-R23D2 failed to start $FileName"
    $stdoutTask = $process.StandardOutput.ReadToEndAsync()
    $stderrTask = $process.StandardError.ReadToEndAsync()
    $timedOut = $false
    $nextHeartbeat = 30.0
    while (-not $process.WaitForExit(1000)) {
        if ($timer.Elapsed.TotalSeconds -ge $nextHeartbeat) {
            Write-Host (
                "QSDK_R23D2_PROGRESS process=$([IO.Path]::GetFileName($FileName)) " +
                "elapsed_seconds=" +
                $timer.Elapsed.TotalSeconds.ToString(
                    "F1", [Globalization.CultureInfo]::InvariantCulture
                )
            )
            $nextHeartbeat += 30.0
        }
        if ($timer.Elapsed.TotalSeconds -ge $TimeoutSeconds) {
            $timedOut = $true
            try { $process.Kill($true) } catch { }
            [void]$process.WaitForExit(10000)
            break
        }
    }
    $timer.Stop()
    $result = [ordered]@{
        exit_code = if ($process.HasExited) { $process.ExitCode } else { -1 }
        timed_out = $timedOut
        duration_seconds = $timer.Elapsed.TotalSeconds
        stdout = $stdoutTask.GetAwaiter().GetResult()
        stderr = $stderrTask.GetAwaiter().GetResult()
    }
    $process.Dispose()
    return $result
}

function Get-R23D2JsonMarker {
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Prefix
    )
    $lines = @($Text -split "`r?`n" | Where-Object {
        $_.StartsWith($Prefix, [StringComparison]::Ordinal)
    })
    Assert-R23D2Exact ($lines.Count -eq 1) (
        "QSDK-R23D2 expected one '$Prefix' marker, observed $($lines.Count)"
    )
    return $lines[0].Substring($Prefix.Length) |
        ConvertFrom-Json -AsHashtable -Depth 100
}

function Assert-R23D2PassMarker {
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Prefix
    )
    $lines = @($Text -split "`r?`n" | Where-Object {
        $_.StartsWith($Prefix, [StringComparison]::Ordinal)
    })
    Assert-R23D2Exact ($lines.Count -eq 1) (
        "QSDK-R23D2 expected one '$Prefix' pass marker, observed $($lines.Count)"
    )
}

function Invoke-R23D2Gate {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$PassPrefix,
        [string[]]$AdditionalArguments = @()
    )
    $arguments = @("-NoLogo", "-NoProfile", "-File", $Path) + $AdditionalArguments
    $result = Invoke-R23D2Process `
        -FileName "pwsh" `
        -Arguments $arguments `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds $GateTimeoutSeconds
    if ($result.stdout) { Write-Host $result.stdout.TrimEnd() }
    if ($result.stderr) { Write-Host $result.stderr.TrimEnd() }
    Assert-R23D2Exact (
        -not [bool]$result.timed_out -and [int]$result.exit_code -eq 0
    ) "QSDK-R23D2 gate failed: $Path"
    Assert-R23D2PassMarker -Text $result.stdout -Prefix $PassPrefix
    return $result
}

function Invoke-R23D2Aggregate {
    param([Parameter(Mandatory)][string[]]$EntryPaths)
    $result = Invoke-R23D2Process `
        -FileName $Python `
        -Arguments (@($evaluatorPath, "evaluate-aggregate") + $EntryPaths) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60
    $evaluation = Get-R23D2JsonMarker `
        -Text $result.stdout `
        -Prefix "QSDK_R23D2_AGGREGATE_EVALUATION "
    return [ordered]@{ process = $result; evaluation = $evaluation }
}

function Publish-R23D2InputArtifacts {
    param([Parameter(Mandatory)][string]$AttestationPath)
    $receipts = [ordered]@{}
    foreach ($binding in @($freeze.source_bindings)) {
        $path = Join-Path $repoRoot ([string]$binding.path)
        $receipts[[string]$binding.name] =
            Publish-SporeSporeContentAddressedArtifact `
                -RepoRoot $repoRoot `
                -ArtifactPath $path `
                -MediaType ([string]$binding.media_type)
    }
    $receipts.physical_freeze = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $freezePath `
        -MediaType "application/json"
    foreach ($runtime in @($freeze.attempt_runtime_artifacts)) {
        $path = if ([bool]$runtime.repo_relative) {
            Join-Path $repoRoot ([string]$runtime.path)
        } else { [string]$runtime.path }
        $receipts[[string]$runtime.name] =
            Publish-SporeSporeContentAddressedArtifact `
                -RepoRoot $repoRoot `
                -ArtifactPath $path `
                -MediaType ([string]$runtime.media_type)
    }
    $receipts.full_godot_attestation =
        Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $AttestationPath `
            -MediaType "application/json"
    return $receipts
}

function Assert-R23D2FrozenBindings {
    foreach ($binding in @($freeze.source_bindings)) {
        $path = Join-Path $repoRoot ([string]$binding.path)
        Assert-R23D2Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$binding.raw_sha256 -ceq (Get-R23D2RawSha256 $path)
        ) "QSDK-R23D2 source binding changed: $([string]$binding.path)"
    }
    foreach ($runtime in @($freeze.external_runtime_bindings)) {
        $path = [IO.Path]::GetFullPath([string]$runtime.path)
        Assert-R23D2Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$runtime.raw_sha256 -ceq (Get-R23D2RawSha256 $path)
        ) "QSDK-R23D2 external runtime binding changed: $path"
    }
    foreach ($runtime in @($freeze.attempt_runtime_artifacts)) {
        $path = if ([bool]$runtime.repo_relative) {
            Join-Path $repoRoot ([string]$runtime.path)
        } else { [IO.Path]::GetFullPath([string]$runtime.path) }
        Assert-R23D2Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$runtime.raw_sha256 -ceq (Get-R23D2RawSha256 $path)
        ) "QSDK-R23D2 attempt runtime binding changed: $path"
    }
}

function Invoke-R23D2EntryEvaluator {
    param([Parameter(Mandatory)][string]$EntryPath)
    $result = Invoke-R23D2Process `
        -FileName $Python `
        -Arguments @($evaluatorPath, "evaluate-entry", $EntryPath) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60
    $evaluation = Get-R23D2JsonMarker `
        -Text $result.stdout `
        -Prefix "QSDK_R23D2_ENTRY_EVALUATION "
    return [ordered]@{ process = $result; evaluation = $evaluation }
}

function Invoke-R23D2PhysicalCell {
    param(
        [Parameter(Mandatory)][string]$EngineId,
        [Parameter(Mandatory)][string]$ArmId,
        [Parameter(Mandatory)][string]$SourceCommit,
        [Parameter(Mandatory)][string]$AttemptPayloadPath,
        [Parameter(Mandatory)][string]$Token,
        [Parameter(Mandatory)][string]$CellRoot
    )
    [void][IO.Directory]::CreateDirectory($CellRoot)
    $cellId = "$EngineId`__$ArmId"
    $environment = [ordered]@{
        SPORESPORE_QSDK_R23D2_ATTEMPT = $AttemptPayloadPath
        SPORESPORE_QSDK_R23D2_TOKEN = $Token
        SPORESPORE_QSDK_R23D2_CELL = $cellId
        SPORESPORE_QSDK_R23D2_ENGINE = $EngineId
    }
    $fileName = ""
    $arguments = @()
    $workingDirectory = $repoRoot
    $successPrefix = ""
    $failurePrefix = ""
    if ($EngineId -ceq "godot_jolt") {
        $fileName = $Godot
        $environment.APPDATA = Join-Path $CellRoot "appdata"
        $environment.LOCALAPPDATA = Join-Path $CellRoot "localappdata"
        [void][IO.Directory]::CreateDirectory($environment.APPDATA)
        [void][IO.Directory]::CreateDirectory($environment.LOCALAPPDATA)
        $arguments = @(
            "--headless", "--path", $repoRoot, "--script",
            $godotWorkerResource, "--", "physical", $ArmId, $SourceCommit
        )
        $successPrefix = "QSDK_R23D2_GODOT_JOLT_CELL "
        $failurePrefix = "QSDK_R23D2_GODOT_JOLT_FAILURE "
    } elseif ($EngineId -ceq "rapier_parry") {
        $fileName = $rapierBinaryPath
        $arguments = @("--arm", $ArmId, "--source-commit", $SourceCommit)
        $successPrefix = "QSDK_R23D2_RAPIER_CELL "
        $failurePrefix = "QSDK_R23D2_RAPIER_FAILURE "
    } elseif ($EngineId -ceq "mujoco") {
        $fileName = $mujocoPython
        $workingDirectory = $mujocoRoot
        $environment.SPORESPORE_LOCOMOTION_LIBRARY = $coreLibraryPath
        $environment.PYTHONPATH = $pythonCoreRoot
        $arguments = @(
            "-m", "sporespore_mujoco_adapter.qsdk_r23d2_heading_response",
            "--arm", $ArmId, "--source-commit", $SourceCommit
        )
        $successPrefix = "QSDK_R23D2_MUJOCO_CELL "
        $failurePrefix = "QSDK_R23D2_MUJOCO_FAILURE "
    } else { throw "QSDK-R23D2 unknown physical engine: $EngineId" }

    $launchSucceeded = $false
    try {
        $result = Invoke-R23D2Process `
            -FileName $fileName `
            -Arguments $arguments `
            -WorkingDirectory $workingDirectory `
            -Environment $environment `
            -TimeoutSeconds $CellTimeoutSeconds
        $launchSucceeded = $true
    } catch {
        $result = [ordered]@{
            exit_code = -1
            timed_out = $false
            duration_seconds = 0.0
            stdout = ""
            stderr = "SUPERVISOR_PROCESS_START_EXCEPTION:$($_.Exception.Message)"
        }
    }
    $logPath = Join-Path $CellRoot "engine.log"
    [IO.File]::WriteAllText(
        $logPath,
        [string]$result.stdout + [string]$result.stderr,
        [Text.UTF8Encoding]::new($false)
    )
    $logCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $logPath `
        -MediaType "text/plain"

    $successLines = @([string]$result.stdout -split "`r?`n" | Where-Object {
        $_.StartsWith($successPrefix, [StringComparison]::Ordinal)
    })
    $failureLines = @([string]$result.stdout -split "`r?`n" | Where-Object {
        $_.StartsWith($failurePrefix, [StringComparison]::Ordinal)
    })
    $terminal = $null
    $markerKind = "supervisor_process_failure"
    try {
        if (
            $launchSucceeded -and -not [bool]$result.timed_out -and
            [int]$result.exit_code -eq 0 -and
            $successLines.Count -eq 1 -and $failureLines.Count -eq 0
        ) {
            $terminal = $successLines[0].Substring($successPrefix.Length) |
                ConvertFrom-Json -AsHashtable -Depth 100
            $markerKind = "successful_report"
        } elseif (
            $launchSucceeded -and -not [bool]$result.timed_out -and
            [int]$result.exit_code -ne 0 -and
            $failureLines.Count -eq 1 -and $successLines.Count -eq 0
        ) {
            $terminal = $failureLines[0].Substring($failurePrefix.Length) |
                ConvertFrom-Json -AsHashtable -Depth 100
            $markerKind = "worker_failure"
        }
    } catch {
        $terminal = $null
    }
    if ($null -eq $terminal) {
        $terminal = [ordered]@{
            schema_version = "sporespore_qsdk_r23d2_supervisor_process_failure_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            cell_id = $cellId
            engine_id = $EngineId
            arm_id = $ArmId
            source_commit = $SourceCommit
            process_launch_succeeded = $launchSucceeded
            process_exit_code = [int]$result.exit_code
            process_timed_out = [bool]$result.timed_out
            success_marker_count = $successLines.Count
            failure_marker_count = $failureLines.Count
            world_attempt_count_known = $false
            world_build_count_known = $false
            engine_log_sha256 = [string]$logCas.sha256
            physical_acceptance_authority = $false
        }
    }
    $terminalPath = Join-Path $CellRoot "terminal-entry.json"
    Write-R23D2NewJson -Path $terminalPath -Value $terminal
    $terminalCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $terminalPath `
        -MediaType "application/json"
    $entryEvaluation = Invoke-R23D2EntryEvaluator `
        -EntryPath ([string]$terminalCas.payload_path)
    $evaluationPath = Join-Path $CellRoot "entry-evaluation.json"
    Write-R23D2NewJson -Path $evaluationPath -Value $entryEvaluation.evaluation
    $evaluationCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $evaluationPath `
        -MediaType "application/json"
    return [ordered]@{
        cell_id = $cellId
        engine_id = $EngineId
        arm_id = $ArmId
        process_launch_succeeded = $launchSucceeded
        process_exit_code = [int]$result.exit_code
        process_timed_out = [bool]$result.timed_out
        process_duration_seconds = [double]$result.duration_seconds
        terminal_marker_kind = $markerKind
        terminal_entry_cas = $terminalCas
        entry_evaluation = $entryEvaluation.evaluation
        entry_evaluation_cas = $evaluationCas
        engine_log_cas = $logCas
        physical_acceptance_authority = $false
    }
}

function Invoke-R23D2PhysicalCampaign {
    param(
        [Parameter(Mandatory)]$Source,
        [Parameter(Mandatory)]$Attestation,
        [Parameter(Mandatory)]$ZeroWorldReceipt
    )
    $sourceAfterPreflight = Get-SporeSporeAttestationSourceIdentity `
        -RepoRoot $repoRoot `
        -RequireCleanPushedLive
    Assert-R23D2Exact (
        [string]$sourceAfterPreflight.commit -ceq [string]$Source.commit -and
        [string]$sourceAfterPreflight.tree_git_oid -ceq [string]$Source.tree_git_oid
    ) "QSDK-R23D2 source changed during zero-world preflight"
    # The gates are allowed to compile, but they may not change any runtime
    # bytes that the one-shot campaign would consume. This second full check is
    # deliberately after every zero-world gate and before CAS publication or
    # attempt creation.
    Assert-R23D2FrozenBindings
    $evidenceRoot = Get-SporeSporeArtifactEvidenceRoot -RepoRoot $repoRoot
    $prior = @(Get-ChildItem -LiteralPath $evidenceRoot -Directory |
        Where-Object { $_.Name -like "qsdk-r23d2-*" })
    Assert-R23D2Exact ($prior.Count -eq 0) (
        "QSDK-R23D2 one-shot identity already exists; rerun forbidden"
    )
    $resolvedOutput = if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
        Join-Path $evidenceRoot (
            "qsdk-r23d2-" + [DateTime]::UtcNow.ToString("yyyyMMddTHHmmssZ")
        )
    } else { [IO.Path]::GetFullPath($OutputRoot) }
    $prefix = $evidenceRoot.TrimEnd("\", "/") + [IO.Path]::DirectorySeparatorChar
    Assert-R23D2Exact (
        $resolvedOutput.StartsWith($prefix, [StringComparison]::OrdinalIgnoreCase) -and
        -not (Test-Path -LiteralPath $resolvedOutput)
    ) "QSDK-R23D2 output must be a new directory under $evidenceRoot"

    $inputCas = Publish-R23D2InputArtifacts `
        -AttestationPath $FullConformanceAttestation
    [void][IO.Directory]::CreateDirectory($resolvedOutput)
    $completionPath = Join-Path $resolvedOutput "completion.json"
    $attemptConsumed = $false
    try {
        $token = [guid]::NewGuid().ToString("N")
        $attempt = [ordered]@{
            schema_version = "sporespore_qsdk_r23d2_attempt_v1"
            attempt_id = [guid]::NewGuid().ToString("N")
            campaign_id = $campaignId
            gate_id = $gateId
            contract_sha256 = Get-R23D2RawSha256 $contractPath
            freeze_sha256 = Get-R23D2RawSha256 $freezePath
            source_commit = [string]$Source.commit
            origin_main_commit = [string]$Source.origin_main
            live_main_commit = [string]$Source.live_github_main
            authorization_token = $token
            physical_execution_authorized = $true
            single_use_supervisor_authorization = $true
            source_worktree_clean = $true
            source_matches_live_github_main = $true
            operation_lock_held = $true
            full_godot_attestation_valid = $true
            full_godot_attestation_sha256 = [string]$Attestation.sha256
            content_addressed_inputs_retained = $true
            content_addressed_inputs = $inputCas
            complete_zero_world_gate_passed = $true
            zero_world_receipt = $ZeroWorldReceipt
            one_shot_attempt_unconsumed = $true
            ordered_cell_ids = $orderedCellIds
            replacement_or_selective_rerun_permitted = $false
            physical_acceptance_authority = $false
        }
        $attemptPath = Join-Path $resolvedOutput "attempt.json"
        Write-R23D2NewJson -Path $attemptPath -Value $attempt
        $attemptCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $attemptPath `
            -MediaType "application/json"
        $attemptConsumed = $true

        $cells = [Collections.Generic.List[object]]::new()
        foreach ($cellId in $orderedCellIds) {
            $parts = $cellId -split "__", 2
            $cells.Add((Invoke-R23D2PhysicalCell `
                -EngineId $parts[0] `
                -ArmId $parts[1] `
                -SourceCommit ([string]$Source.commit) `
                -AttemptPayloadPath ([string]$attemptCas.payload_path) `
                -Token $token `
                -CellRoot (Join-Path $resolvedOutput $cellId)))
        }
        $terminalPaths = @($cells | ForEach-Object {
            [string]$_.terminal_entry_cas.payload_path
        })
        $aggregateInput = [ordered]@{
            schema_version = "sporespore_qsdk_r23d2_aggregate_input_v1"
            ordered_cell_ids = $orderedCellIds
            retained_terminal_entry_count = $terminalPaths.Count
            ordered_terminal_entry_cas = @($cells | ForEach-Object {
                $_.terminal_entry_cas
            })
            physical_acceptance_authority = $false
        }
        $aggregateInputPath = Join-Path $resolvedOutput "aggregate-input.json"
        Write-R23D2NewJson -Path $aggregateInputPath -Value $aggregateInput
        $aggregateInputCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $aggregateInputPath `
            -MediaType "application/json"
        $aggregate = Invoke-R23D2Aggregate -EntryPaths $terminalPaths
        $aggregateEvaluationPath = Join-Path $resolvedOutput "aggregate-evaluation.json"
        Write-R23D2NewJson `
            -Path $aggregateEvaluationPath `
            -Value $aggregate.evaluation
        $aggregateEvaluationCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $aggregateEvaluationPath `
            -MediaType "application/json"
        $classification = [string]$aggregate.evaluation.result_classification
        $valid = (
            $cells.Count -eq 9 -and
            $terminalPaths.Count -eq 9 -and
            [bool]$aggregate.evaluation.aggregate_valid -and
            $classification -in @("valid_positive", "valid_negative")
        )
        $report = [ordered]@{
            schema_version = "sporespore_qsdk_r23d2_campaign_report_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            source = $Source
            contract_sha256 = Get-R23D2RawSha256 $contractPath
            freeze_sha256 = Get-R23D2RawSha256 $freezePath
            attempt_cas = $attemptCas
            aggregate_input_cas = $aggregateInputCas
            aggregate_evaluation_cas = $aggregateEvaluationCas
            ordered_cells = @($cells)
            aggregate_evaluation = $aggregate.evaluation
            retained_terminal_entry_count = $terminalPaths.Count
            result_classification = $classification
            development_screen_valid = [bool]$aggregate.evaluation.development_screen_valid
            development_screen_passed = [bool]$aggregate.evaluation.development_screen_passed
            claims = [ordered]@{
                development_screen_only = $true
                q_sdk_r23_satisfied = $false
                command_conditioned_turning = $false
                cross_engine_equivalence = $false
                release_authorized = $false
                physical_acceptance_authority = $false
            }
        }
        $reportPath = Join-Path $resolvedOutput "report.json"
        Write-R23D2NewJson -Path $reportPath -Value $report
        $reportCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $reportPath `
            -MediaType "application/json"
        $completion = [ordered]@{
            schema_version = "sporespore_qsdk_r23d2_completion_v1"
            campaign_id = $campaignId
            status = if ($valid) { "$classification`_first_attempt" } else {
                "invalid_or_incomplete_first_attempt"
            }
            source_commit = [string]$Source.commit
            ordered_cell_count = 9
            retained_terminal_entry_count = $terminalPaths.Count
            result_classification = $classification
            report_cas = $reportCas
            one_shot_identity_consumed = $true
            same_identity_rerun_allowed = $false
            q_sdk_r23_satisfied = $false
            cross_engine_equivalence = $false
            release_authorized = $false
            physical_acceptance_authority = $false
        }
        Write-R23D2NewJson -Path $completionPath -Value $completion
        $completionCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $completionPath `
            -MediaType "application/json"
        if (-not $valid) {
            throw "QSDK-R23D2 retained an invalid or incomplete first attempt: $resolvedOutput"
        }
        Write-Host (
            "QSDK_R23D2_PHYSICAL_COMPLETE terminals=9 " +
            "classification=$classification " +
            "development_screen_passed=$([bool]$aggregate.evaluation.development_screen_passed) " +
            "q_sdk_r23=False equivalence=False release=False " +
            "report_sha256=$([string]$reportCas.sha256) " +
            "completion_sha256=$([string]$completionCas.sha256)"
        )
    } catch {
        if ($attemptConsumed -and -not (Test-Path -LiteralPath $completionPath)) {
            $emergency = [ordered]@{
                schema_version = "sporespore_qsdk_r23d2_completion_v1"
                campaign_id = $campaignId
                status = "invalid_or_incomplete_first_attempt"
                source_commit = [string]$Source.commit
                failure_code = "SUPERVISOR_INFRASTRUCTURE_EXCEPTION"
                failure_detail = $_.Exception.Message
                one_shot_identity_consumed = $true
                same_identity_rerun_allowed = $false
                q_sdk_r23_satisfied = $false
                cross_engine_equivalence = $false
                release_authorized = $false
                physical_acceptance_authority = $false
            }
            Write-R23D2NewJson -Path $completionPath -Value $emergency
            [void](Publish-SporeSporeContentAddressedArtifact `
                -RepoRoot $repoRoot `
                -ArtifactPath $completionPath `
                -MediaType "application/json")
        }
        throw
    }
}

Assert-R23D2Exact ($PreflightOnly.IsPresent -xor $RunPhysical.IsPresent) (
    "Specify exactly one of -PreflightOnly or -RunPhysical"
)
Assert-R23D2Exact (
    $RunPhysical.IsPresent -or (
        [string]::IsNullOrWhiteSpace($FullConformanceAttestation) -and
        [string]::IsNullOrWhiteSpace($OutputRoot)
    )
) "-FullConformanceAttestation and -OutputRoot require -RunPhysical"
if ($RunPhysical -and $physicalIdentityClosed) {
    Write-R23D2PhysicalRefusal -Reason "consumed_identity_closed"
    throw "QSDK-R23D2 is closed and may not open another world"
}
if ($RunPhysical -and [string]::IsNullOrWhiteSpace($FullConformanceAttestation)) {
    Write-R23D2PhysicalRefusal -Reason "matching_full_godot_v2_attestation_required"
    throw "QSDK-R23D2 physical execution requires a matching full-Godot V2 attestation"
}

foreach ($path in @(
    $contractPath, $freezePath, $evaluatorPath, $evaluatorGatePath, $oracleGatePath,
    $artifactStorePath, $operationLockPath, $attestationVerifierPath,
    $reproducibleRuntimePath
)) {
    Assert-R23D2Exact (Test-Path -LiteralPath $path -PathType Leaf) (
        "QSDK-R23D2 supervisor input is missing: $path"
    )
}

$contract = Get-Content -Raw -LiteralPath $contractPath |
    ConvertFrom-Json -AsHashtable -Depth 100
$freeze = Get-Content -Raw -LiteralPath $freezePath |
    ConvertFrom-Json -AsHashtable -Depth 100
Assert-R23D2Exact (
    [string]$contract.schema_version -ceq
        "sporespore_qsdk_r23d2_development_contract_v1" -and
    [string]$contract.status -ceq
        "frozen_supervisor_only_physical_authorized_pending_exact_source_attestation" -and
    [string]$contract.campaign_id -ceq $campaignId -and
    [string]$contract.gate_id -ceq $gateId -and
    [string]$contract.production_evaluator.implementation_path -ceq
        "sdk/turning/r23d2_development.py" -and
    [string]$contract.aggregate_supervisor.supervisor_path -ceq
        "sdk/run_qsdk_r23d2_supervisor.ps1" -and
    [string]$contract.aggregate_supervisor.freeze_path -ceq
        "sdk/turning/r23d2_physical_freeze_v1.json" -and
    [string]$contract.aggregate_supervisor.reproducible_runtime_materialization_path -ceq
        "sdk/r23d2_reproducible_runtime_materialization.ps1" -and
    [bool]$contract.aggregate_supervisor.pinned_reproducible_runtime_materialization_before_freeze_validation_required -and
    [bool]$contract.aggregate_supervisor.cargo_target_root_remapped_to_constant_virtual_prefix_required -and
    [bool]$contract.aggregate_supervisor.serial_one_shot_required -and
    [bool]$contract.aggregate_supervisor.content_addressed_retention_before_consumption_required -and
    [bool]$contract.aggregate_supervisor.serial_worker_gate_execution_required -and
    [bool]$contract.aggregate_supervisor.synthetic_cell_entries_content_addressed_before_aggregation -and
    [bool]$contract.authorization.physical_execution_authorized -and
    [int]$contract.authorization.physical_process_launch_count -eq 0 -and
    [int]$contract.authorization.world_attempt_count -eq 0 -and
    [int]$contract.authorization.world_build_count -eq 0 -and
    [int]$contract.claim_boundary.physical_worker_implementation_count -eq 3 -and
    [bool]$contract.claim_boundary.physical_workers_complete -and
    -not [bool]$contract.claim_boundary.command_conditioned_turning -and
    -not [bool]$contract.claim_boundary.q_sdk_r23_satisfied -and
    -not [bool]$contract.claim_boundary.cross_engine_equivalence -and
    -not [bool]$contract.claim_boundary.physical_acceptance_authority
) "QSDK-R23D2 supervisor contract identity changed"

Assert-R23D2Exact (
    [string]$freeze.schema_version -ceq
        "sporespore_qsdk_r23d2_physical_freeze_v1" -and
    [string]$freeze.status -ceq "frozen_supervisor_only_physical_authorized" -and
    [string]$freeze.campaign_id -ceq $campaignId -and
    [string]$freeze.gate_id -ceq $gateId -and
    [string]$freeze.contract_raw_sha256 -ceq (Get-R23D2RawSha256 $contractPath) -and
    [int]$freeze.declared_cell_count -eq 9 -and
    (@($freeze.ordered_cell_ids) -join "|") -ceq ($orderedCellIds -join "|") -and
    [int]$freeze.declared_source_binding_count -eq @($freeze.source_bindings).Count -and
    @($freeze.source_bindings).Count -ge 24 -and
    [bool]$freeze.serial_one_shot_required -and
    [bool]$freeze.content_addressed_terminal_retention_required -and
    [bool]$freeze.attempt_runtime_artifacts_materialized_by_pinned_reproducible_recipe_before_validation_required -and
    [bool]$freeze.cargo_target_root_remapped_to_constant_virtual_prefix_required -and
    [bool]$freeze.exact_full_godot_v2_attestation_required -and
    [bool]$freeze.physical_execution_authorized -and
    -not [bool]$freeze.replacement_or_selective_rerun_permitted -and
    -not [bool]$freeze.physical_acceptance_authority
) "QSDK-R23D2 physical freeze identity changed"
$runtimeMaterializationBindings = @(
    $freeze.source_bindings | Where-Object {
        [string]$_.path -ceq
            "sdk/r23d2_reproducible_runtime_materialization.ps1"
    }
)
Assert-R23D2Exact (
    $runtimeMaterializationBindings.Count -eq 1 -and
    [string]$runtimeMaterializationBindings[0].raw_sha256 -ceq
        (Get-R23D2RawSha256 $reproducibleRuntimePath)
) "QSDK-R23D2 reproducible runtime helper changed before import"
. $reproducibleRuntimePath
Assert-R23D2Exact (
    $null -ne (Get-Command `
        -Name Initialize-SporeSporeR23D2AttemptRuntimeArtifacts `
        -CommandType Function `
        -ErrorAction SilentlyContinue)
) "QSDK-R23D2 reproducible runtime helper surface is missing"
$runtimeMaterialization = Initialize-SporeSporeR23D2AttemptRuntimeArtifacts `
    -RepoRoot $repoRoot
Assert-R23D2FrozenBindings

$workerSpecs = @(
    [ordered]@{
        engine_id = "godot_jolt"
        path = Join-Path $sdkRoot "run_qsdk_r23d2_godot_jolt_worker_preflight.ps1"
        pass_prefix = "QSDK_R23D2_GODOT_JOLT_WORKER_PASS"
        arguments = @("-Godot", $Godot)
    },
    [ordered]@{
        engine_id = "rapier_parry"
        path = Join-Path $sdkRoot "run_qsdk_r23d2_rapier_worker_preflight.ps1"
        pass_prefix = "QSDK_R23D2_RAPIER_WORKER_PASS"
        arguments = @()
    },
    [ordered]@{
        engine_id = "mujoco"
        path = Join-Path $sdkRoot "run_qsdk_r23d2_mujoco_worker_preflight.ps1"
        pass_prefix = "QSDK_R23D2_MUJOCO_WORKER_PASS"
        arguments = @()
    }
)
$contractEngineIds = @($contract.engines | ForEach-Object { [string]$_.engine_id })
Assert-R23D2Exact (
    ($contractEngineIds -join "|") -ceq ($engineOrder -join "|")
) "QSDK-R23D2 contract engine order changed"
$expectedPhysicalImplementations = [ordered]@{
    godot_jolt = $true
    rapier_parry = $true
    mujoco = $true
}
foreach ($engine in @($contract.engines)) {
    $workerContractPath = Join-Path $repoRoot ([string]$engine.worker_contract_path)
    Assert-R23D2Exact (
        (Get-R23D2RawSha256 $workerContractPath) -ceq
            [string]$engine.worker_contract_sha256 -and
        [bool]$engine.zero_world_commissioned -and
        [bool]$engine.physical_implementation_present -eq
            [bool]$expectedPhysicalImplementations[[string]$engine.engine_id]
    ) "QSDK-R23D2 worker declaration changed: $($engine.engine_id)"
}

Assert-R23D2Exact (
    (Invoke-R23D2Git @("rev-parse", "--show-toplevel")).Replace("/", "\") -ceq
        $repoRoot -and
    (Invoke-R23D2Git @("remote", "get-url", "origin")) -ceq
        "https://github.com/Slagathore/sporespore.git"
) "QSDK-R23D2 supervisor repository identity mismatch"
$preauthorizationPath = [IO.Path]::GetFullPath(
    [string]$freeze.preauthorization_attestation_path
)
Assert-R23D2Exact (
    (Test-Path -LiteralPath $preauthorizationPath -PathType Leaf) -and
    (Get-R23D2RawSha256 $preauthorizationPath) -ceq
        [string]$freeze.preauthorization_attestation_raw_sha256
) "QSDK-R23D2 preauthorization attestation bytes changed"
$preauthorization = Get-Content -Raw -LiteralPath $preauthorizationPath |
    ConvertFrom-Json -AsHashtable -Depth 100
Assert-R23D2Exact (
    [string]$preauthorization.source.commit -ceq
        [string]$freeze.preauthorization_attestation_source_commit -and
    [bool]$preauthorization.conformance.passed -and
    -not [bool]$preauthorization.conformance.skip_godot -and
    -not [bool]$preauthorization.conformance.one_shot_physical_campaign_executed -and
    -not [bool]$preauthorization.claims.physical_acceptance_authority
) "QSDK-R23D2 preauthorization attestation identity changed"

$physicalSource = $null
$physicalAttestation = $null
$physicalLock = $null
if ($RunPhysical) {
    $physicalSource = Get-SporeSporeAttestationSourceIdentity `
        -RepoRoot $repoRoot `
        -RequireCleanPushedLive
    $physicalAttestation = Test-SporeSporeFullConformanceAttestationFile `
        -RepoRoot $repoRoot `
        -Godot $Godot `
        -AttestationPath $FullConformanceAttestation
    if (-not [bool]$physicalAttestation.ok) {
        Write-R23D2PhysicalRefusal -Reason (
            "full_godot_v2_attestation_invalid:" +
            (@($physicalAttestation.failure_codes) -join ",")
        )
        throw "QSDK-R23D2 full-conformance attestation is invalid"
    }
    $physicalLock = Enter-SporeSporeLocomotionOperationLock -Role physical
    if (-not [bool]$physicalLock.acquired) {
        Write-R23D2PhysicalRefusal -Reason "global_locomotion_operation_lock_held"
        throw "QSDK-R23D2 global locomotion operation lock is held"
    }
}

$preflightRoot = Join-Path $sdkRoot "target\qsdk-r23d2-supervisor-preflight"
$runRoot = Join-Path $preflightRoot ([guid]::NewGuid().ToString("N"))
$casRoot = Join-Path $runRoot "cas"
[void][IO.Directory]::CreateDirectory($runRoot)
$runRootFull = [IO.Path]::GetFullPath($runRoot)
$preflightRootFull = [IO.Path]::GetFullPath($preflightRoot) + [IO.Path]::DirectorySeparatorChar
Assert-R23D2Exact (
    $runRootFull.StartsWith($preflightRootFull, [StringComparison]::OrdinalIgnoreCase)
) "QSDK-R23D2 scratch root escaped its target boundary"

try {
    $oracleGate = Invoke-R23D2Gate `
        -Path $oracleGatePath `
        -PassPrefix "QSDK_R23D2_ORACLE_GATE_PASS"
    $evaluatorGate = Invoke-R23D2Gate `
        -Path $evaluatorGatePath `
        -PassPrefix "QSDK_R23D2_DEVELOPMENT_GATE_PASS" `
        -AdditionalArguments @("-Python", $Python)
    $workerGateResults = [Collections.Generic.List[object]]::new()
    foreach ($spec in $workerSpecs) {
        $workerGateResults.Add((Invoke-R23D2Gate `
            -Path $spec.path `
            -PassPrefix $spec.pass_prefix `
            -AdditionalArguments $spec.arguments))
    }

    $matrixRoot = Join-Path $runRoot "matrix"
    $emit = Invoke-R23D2Process `
        -FileName $Python `
        -Arguments @($evaluatorPath, "emit-synthetic-matrix", $matrixRoot) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60
    Assert-R23D2Exact (
        -not [bool]$emit.timed_out -and [int]$emit.exit_code -eq 0
    ) "QSDK-R23D2 synthetic matrix emission failed"
    $manifest = Get-R23D2JsonMarker `
        -Text $emit.stdout `
        -Prefix "QSDK_R23D2_SYNTHETIC_MATRIX "
    Assert-R23D2Exact (
        [string]$manifest.schema_version -ceq
            "sporespore_qsdk_r23d2_synthetic_matrix_manifest_v1" -and
        [int]$manifest.report_count -eq 9 -and
        [int]$manifest.synthetic_projected_world_count -eq 9 -and
        [int]$manifest.actual_world_build_count -eq 0 -and
        -not [bool]$manifest.physical_acceptance_authority
    ) "QSDK-R23D2 synthetic matrix manifest changed"

    $reportCas = [Collections.Generic.List[object]]::new()
    foreach ($reportPath in @($manifest.ordered_report_paths)) {
        $stored = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath ([string]$reportPath) `
            -MediaType "application/json" `
            -EvidenceRootOverride $casRoot `
            -TestOnly
        Assert-R23D2Exact (
            Test-SporeSporeStoredArtifact `
                -Directory (Split-Path -Parent $stored.payload_path) `
                -ExpectedSha256 ([string]$stored.sha256).Replace("sha256:", "") `
                -ExpectedByteLength ([long]$stored.byte_length)
        ) "QSDK-R23D2 synthetic report CAS verification failed"
        $reportCas.Add($stored)
    }
    $retainedPaths = @($reportCas | ForEach-Object { [string]$_.payload_path })
    $retainedIds = @($retainedPaths | ForEach-Object {
        $entry = Get-Content -Raw -LiteralPath $_ |
            ConvertFrom-Json -AsHashtable -Depth 100
        [string]$entry.cell_id
    })
    Assert-R23D2Exact (
        $reportCas.Count -eq 9 -and
        ($retainedIds -join "|") -ceq ($orderedCellIds -join "|")
    ) "QSDK-R23D2 CAS matrix order or completeness changed"

    $positive = Invoke-R23D2Aggregate -EntryPaths $retainedPaths
    Assert-R23D2Exact (
        -not [bool]$positive.process.timed_out -and
        [int]$positive.process.exit_code -eq 0 -and
        [bool]$positive.evaluation.aggregate_valid -and
        [bool]$positive.evaluation.development_screen_valid -and
        [bool]$positive.evaluation.development_screen_passed -and
        [string]$positive.evaluation.result_classification -ceq "valid_positive" -and
        [int]$positive.evaluation.report_count -eq 9 -and
        [int]$positive.evaluation.worker_failure_count -eq 0 -and
        [int]$positive.evaluation.valid_positive_cell_count -eq 9 -and
        [int]$positive.evaluation.world_attempt_count -eq 9 -and
        [int]$positive.evaluation.world_build_count -eq 9 -and
        -not [bool]$positive.evaluation.q_sdk_r23_satisfied -and
        -not [bool]$positive.evaluation.command_conditioned_turning -and
        -not [bool]$positive.evaluation.cross_engine_equivalence -and
        -not [bool]$positive.evaluation.physical_acceptance_authority
    ) "QSDK-R23D2 retained synthetic positive aggregate failed"

    $negativeEntry = Get-Content -Raw -LiteralPath $retainedPaths[1] |
        ConvertFrom-Json -AsHashtable -Depth 100
    $negativeEntry.physics.final_forward_displacement_m = 0.0
    $negativePath = Join-Path $runRoot "valid-negative.json"
    Write-R23D2NewJson -Path $negativePath -Value $negativeEntry
    $negativeCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $negativePath `
        -MediaType "application/json" -EvidenceRootOverride $casRoot -TestOnly
    $negativePaths = @($retainedPaths)
    $negativePaths[1] = [string]$negativeCas.payload_path
    $negative = Invoke-R23D2Aggregate -EntryPaths $negativePaths
    Assert-R23D2Exact (
        [int]$negative.process.exit_code -eq 0 -and
        [bool]$negative.evaluation.aggregate_valid -and
        [bool]$negative.evaluation.development_screen_valid -and
        -not [bool]$negative.evaluation.development_screen_passed -and
        [string]$negative.evaluation.result_classification -ceq "valid_negative" -and
        [int]$negative.evaluation.valid_negative_cell_count -eq 1
    ) "QSDK-R23D2 cross-process valid-negative classification failed"

    $missing = Invoke-R23D2Aggregate -EntryPaths $retainedPaths[0..7]
    $swappedPaths = @($retainedPaths)
    ($swappedPaths[0], $swappedPaths[1]) = ($swappedPaths[1], $swappedPaths[0])
    $swapped = Invoke-R23D2Aggregate -EntryPaths $swappedPaths
    $duplicatePaths = @($retainedPaths[0..7]) + @($retainedPaths[0])
    $duplicate = Invoke-R23D2Aggregate -EntryPaths $duplicatePaths
    $tamperedEntry = Get-Content -Raw -LiteralPath $retainedPaths[0] |
        ConvertFrom-Json -AsHashtable -Depth 100
    $tamperedEntry.command_validation.raw_heading_offset_equality_used = $true
    $tamperedPath = Join-Path $runRoot "legacy-oracle-tamper.json"
    Write-R23D2NewJson -Path $tamperedPath -Value $tamperedEntry
    $tamperedCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $tamperedPath `
        -MediaType "application/json" -EvidenceRootOverride $casRoot -TestOnly
    $tamperedPaths = @($retainedPaths)
    $tamperedPaths[0] = [string]$tamperedCas.payload_path
    $tampered = Invoke-R23D2Aggregate -EntryPaths $tamperedPaths
    $aggregateNegativeControls = @($missing, $swapped, $duplicate, $tampered)
    Assert-R23D2Exact (
        @($aggregateNegativeControls | Where-Object {
            [int]$_.process.exit_code -ne 0 -and
            -not [bool]$_.evaluation.aggregate_valid -and
            [string]$_.evaluation.result_classification -ceq "invalid_or_incomplete"
        }).Count -eq 4
    ) "QSDK-R23D2 cross-process aggregate negative controls did not fail closed"

    $stageExpectations = [ordered]@{
        before_world = @(8, 8)
        world_construction_failed = @(9, 8)
        controller_validation_failed = @(9, 9)
    }
    $failureCas = [Collections.Generic.List[object]]::new()
    $stageControlPassCount = 0
    foreach ($entry in $stageExpectations.GetEnumerator()) {
        $failurePath = Join-Path $runRoot "$($entry.Key)-failure.json"
        $failureEmit = Invoke-R23D2Process `
            -FileName $Python `
            -Arguments @(
                $evaluatorPath, "emit-synthetic-failure", $orderedCellIds[0],
                [string]$entry.Key, $failurePath
            ) `
            -WorkingDirectory $repoRoot `
            -TimeoutSeconds 60
        Assert-R23D2Exact ([int]$failureEmit.exit_code -eq 0) (
            "QSDK-R23D2 synthetic failure emission failed: $($entry.Key)"
        )
        $failureManifest = Get-R23D2JsonMarker `
            -Text $failureEmit.stdout `
            -Prefix "QSDK_R23D2_SYNTHETIC_FAILURE "
        $storedFailure = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $failurePath `
            -MediaType "application/json" -EvidenceRootOverride $casRoot -TestOnly
        $failureCas.Add($storedFailure)
        $failurePaths = @($retainedPaths)
        $failurePaths[0] = [string]$storedFailure.payload_path
        $aggregate = Invoke-R23D2Aggregate -EntryPaths $failurePaths
        $expectedCounts = @($entry.Value)
        if (
            [int]$aggregate.process.exit_code -ne 0 -and
            -not [bool]$aggregate.evaluation.aggregate_valid -and
            [int]$aggregate.evaluation.worker_failure_count -eq 1 -and
            [int]$aggregate.evaluation.world_attempt_count -eq $expectedCounts[0] -and
            [int]$aggregate.evaluation.world_build_count -eq $expectedCounts[1] -and
            [string]$failureManifest.stage_id -ceq [string]$entry.Key
        ) { $stageControlPassCount += 1 }
    }
    Assert-R23D2Exact ($stageControlPassCount -eq 3) (
        "QSDK-R23D2 cross-process stage-count controls failed"
    )
    $controllerFailure = Get-Content -Raw -LiteralPath (
        [string]$failureCas[2].payload_path
    ) | ConvertFrom-Json -AsHashtable -Depth 100
    Assert-R23D2Exact (
        [string]$controllerFailure.stage_id -ceq "controller_validation_failed" -and
        [bool]$controllerFailure.rejected_projection_retention.embedded_before_exit -and
        [string]$controllerFailure.rejected_projection_retention.payload_sha256 -match
            '^sha256:[0-9a-f]{64}$' -and
        @($controllerFailure.oracle_evaluation.failed_predicates).Count -eq 1
    ) "QSDK-R23D2 rejected controller projection was not retained"

    $physicalRefusal = Invoke-R23D2Process `
        -FileName "pwsh" `
        -Arguments @(
            "-NoLogo", "-NoProfile", "-File", $PSCommandPath, "-RunPhysical"
        ) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60
    Assert-R23D2Exact (
        [int]$physicalRefusal.exit_code -ne 0 -and
        -not [bool]$physicalRefusal.timed_out
    ) "QSDK-R23D2 direct physical invocation did not refuse"
    $refusal = Get-R23D2JsonMarker `
        -Text $physicalRefusal.stdout `
        -Prefix "QSDK_R23D2_PHYSICAL_REFUSAL "
    Assert-R23D2Exact (
        [string]$refusal.refusal_stage -ceq "before_attestation_or_world" -and
        [int]$refusal.physical_process_launch_count -eq 0 -and
        [int]$refusal.world_attempt_count -eq 0 -and
        [int]$refusal.world_build_count -eq 0 -and
        -not [bool]$refusal.physical_acceptance_authority
    ) "QSDK-R23D2 physical refusal receipt changed"

    $receipt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d2_supervisor_preflight_v1"
        campaign_id = $campaignId
        gate_id = $gateId
        contract_sha256 = Get-R23D2RawSha256 $contractPath
        stage_zero_oracle_gate_pass_count = 1
        shared_evaluator_gate_pass_count = 1
        worker_gate_count = $workerGateResults.Count
        worker_entrypoint_count = 9
        physical_worker_implementation_count = 3
        retained_test_cas_report_count = $reportCas.Count
        retained_test_cas_failure_count = $failureCas.Count
        synthetic_positive_aggregate_pass_count = 1
        synthetic_valid_negative_aggregate_count = 1
        aggregate_negative_control_rejection_count = 4
        stage_aggregate_control_pass_count = $stageControlPassCount
        physical_authorization_refusal_count = 1
        synthetic_projected_world_attempt_count = 9
        synthetic_projected_world_build_count = 9
        actual_physical_process_launch_count = 0
        actual_world_attempt_count = 0
        actual_world_build_count = 0
        locomotion_outcome_exposed = $false
        physical_execution_authorized = $true
        q_sdk_r23_satisfied = $false
        command_conditioned_turning = $false
        cross_engine_equivalence = $false
        release_authorized = $false
        physical_acceptance_authority = $false
    }
    Write-Host (
        "QSDK_R23D2_SUPERVISOR_PREFLIGHT " +
        ($receipt | ConvertTo-Json -Depth 100 -Compress)
    )
    Write-Host (
        "QSDK_R23D2_SUPERVISOR_PASS workers=3 entrypoints=9 reports=9 " +
        "failure_receipts=3 positive=1/1 valid_negative=1/1 " +
        "aggregate_rejections=4/4 stage_counts=3/3 physical_refusal=1 " +
        "physical_workers=3/3 actual_worlds=0 physical_authority=False"
    )
    if ($RunPhysical) {
        Invoke-R23D2PhysicalCampaign `
            -Source $physicalSource `
            -Attestation $physicalAttestation `
            -ZeroWorldReceipt $receipt
    }
} finally {
    if (Test-Path -LiteralPath $runRootFull -PathType Container) {
        Remove-Item -LiteralPath $runRootFull -Recurse -Force
    }
    if ($null -ne $physicalLock) {
        Exit-SporeSporeLocomotionOperationLock $physicalLock
    }
}
