#requires -Version 7.0

[CmdletBinding()]
param(
    [switch]$PreflightOnly,
    [switch]$RunPhysical,
    [string]$FullConformanceAttestation = "",
    [string]$OutputRoot = "",
    [string]$Python = "python",
    [string]$PowerShell = "pwsh",
    [string]$Godot = (
        "C:\Users\Cole\CodeStuff\Misc\Godot\" +
        "Godot_v4.7-stable_mono_win64_console.exe"
    ),
    [ValidateRange(60, 3600)][int]$GateTimeoutSeconds = 1200,
    [ValidateRange(300, 3600)][int]$CellTimeoutSeconds = 900
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
$PSNativeCommandUseErrorActionPreference = $false

$sdkRoot = [IO.Path]::GetFullPath($PSScriptRoot)
$repoRoot = [IO.Path]::GetFullPath((Split-Path -Parent $sdkRoot))
$implementationPath = Join-Path $sdkRoot "turning\r23d5_implementation_contract_v1.json"
$preregistrationPath = Join-Path $sdkRoot (
    "turning\r23d5_dependency_closed_preregistration_v1.json"
)
$closurePath = Join-Path $sdkRoot "turning\r23d5_physical_closure_v1.json"
$evaluatorPath = Join-Path $sdkRoot "turning\r23d5_physical_evaluator.py"
$artifactStorePath = Join-Path $sdkRoot "content_addressed_artifact_store.ps1"
$operationLockPath = Join-Path $sdkRoot "locomotion_operation_lock.ps1"
$attestationVerifierPath = Join-Path $sdkRoot "locomotion_full_conformance_attestation.ps1"
$runtimeMaterializationPath = Join-Path $sdkRoot "r23d3_reproducible_runtime_materialization.ps1"
$dependencyComposerPath = Join-Path $sdkRoot "turning\r23d5_dependency_closure.ps1"
$terminalClassifierPath = Join-Path $sdkRoot "turning\r23d5_terminal_marker_classifier.ps1"
$mujocoRoot = Join-Path $sdkRoot "adapters\mujoco"
$mujocoPython = Join-Path $mujocoRoot ".venv\Scripts\python.exe"
$pythonCoreRoot = Join-Path $sdkRoot "python"
$godotWorkerResource = "res://tests/test_sdk_qsdk_r23d5_godot_jolt_worker.gd"
$campaignId = "QSDK-R23D5-DEPENDENCY-CLOSED-TERMINAL-STABILIZED-BILATERAL-TURN-DEVELOPMENT"
$gateId = "QSDK-R23D5"
$stageAId = "mujoco_terminal_restoration_screen"
$stageBId = "three_engine_confirmation"
$stageAArmOrder = @("positive_heading", "negative_heading")
$stageBArmOrder = @("reference_zero", "positive_heading", "negative_heading")
$stageBEngineOrder = @("godot_jolt", "rapier_parry", "mujoco")
$stageACellIds = @(
    foreach ($armId in $stageAArmOrder) {
        "mujoco__terminal_restoration__$armId"
    }
)
$stageBCellIds = @(
    foreach ($engineId in $stageBEngineOrder) {
        foreach ($armId in $stageBArmOrder) {
            "$engineId`__onset_600__$armId"
        }
    }
)
$attemptEnvironmentNames = @(
    "SPORESPORE_QSDK_R23D5_FREEZE",
    "SPORESPORE_QSDK_R23D5_ATTEMPT",
    "SPORESPORE_QSDK_R23D5_TOKEN",
    "SPORESPORE_QSDK_R23D5_STAGE",
    "SPORESPORE_QSDK_R23D5_CELL",
    "SPORESPORE_QSDK_R23D5_ENGINE",
    "SPORESPORE_QSDK_R23D5_ATTEMPT_ROOT",
    "SPORESPORE_QSDK_R23D5_PYTHON",
    "SPORESPORE_QSDK_R23D5_POWERSHELL"
)

foreach ($path in @(
    $implementationPath, $preregistrationPath, $evaluatorPath,
    $artifactStorePath, $operationLockPath, $attestationVerifierPath,
    $runtimeMaterializationPath, $mujocoPython
)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "QSDK-R23D5 supervisor input is missing: $path"
    }
}

. $artifactStorePath
. $operationLockPath
. $attestationVerifierPath
. $dependencyComposerPath
. $terminalClassifierPath

function Assert-R23D5Exact {
    param([bool]$Condition, [string]$Message)
    if (-not $Condition) { throw $Message }
}

function Get-R23D5RawSha256 {
    param([Parameter(Mandatory)][string]$Path)
    return "sha256:" + (
        Get-FileHash -LiteralPath $Path -Algorithm SHA256
    ).Hash.ToLowerInvariant()
}

function Invoke-R23D5Git {
    param([Parameter(Mandatory)][string[]]$Arguments)
    $output = @(& git -C $repoRoot @Arguments 2>&1)
    if ($LASTEXITCODE -ne 0) {
        throw (
            "QSDK-R23D5 git failed: git $($Arguments -join ' '): " +
            ($output -join " ")
        )
    }
    return ($output -join "`n").Trim()
}

function Write-R23D5NewJson {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)]$Value
    )
    Assert-R23D5Exact (-not (Test-Path -LiteralPath $Path)) (
        "QSDK-R23D5 refuses to overwrite generated bytes: $Path"
    )
    [IO.File]::WriteAllText(
        $Path,
        (ConvertTo-Json -InputObject $Value -Depth 100 -Compress) + "`n",
        [Text.UTF8Encoding]::new($false)
    )
}

function Write-R23D5Manifest {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][AllowEmptyCollection()][string[]]$Paths
    )
    $values = [object[]]@($Paths)
    Assert-R23D5Exact (-not (Test-Path -LiteralPath $Path)) (
        "QSDK-R23D5 refuses to overwrite generated bytes: $Path"
    )
    [IO.File]::WriteAllText(
        $Path,
        (ConvertTo-Json -InputObject $values -Depth 10 -Compress) + "`n",
        [Text.UTF8Encoding]::new($false)
    )
    if ($values.Count -eq 0) {
        Assert-R23D5Exact (
            [Convert]::ToHexString([IO.File]::ReadAllBytes($Path)).ToLowerInvariant() `
                -ceq "5b5d0a"
        ) "QSDK-R23D5 empty manifest is not exact UTF-8 [] plus LF"
    }
}

function Write-R23D5PhysicalRefusal {
    param([Parameter(Mandatory)][string]$Reason)
    $receipt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d5_physical_refusal_v1"
        campaign_id = $campaignId
        gate_id = $gateId
        refusal_stage = "before_attempt_or_world"
        reason = $Reason
        physical_process_launch_count = 0
        world_attempt_count = 0
        world_build_count = 0
        physical_acceptance_authority = $false
    }
    Write-Host (
        "QSDK_R23D5_PHYSICAL_REFUSAL " +
        ($receipt | ConvertTo-Json -Depth 20 -Compress)
    )
}

function Invoke-R23D5Process {
    param(
        [Parameter(Mandatory)][string]$FileName,
        [Parameter(Mandatory)][string[]]$Arguments,
        [Parameter(Mandatory)][string]$WorkingDirectory,
        [Collections.IDictionary]$Environment = @{},
        [int]$TimeoutSeconds = 900
    )
    $start = [Diagnostics.ProcessStartInfo]::new()
    $start.FileName = $FileName
    $start.WorkingDirectory = $WorkingDirectory
    $start.UseShellExecute = $false
    $start.CreateNoWindow = $true
    $start.RedirectStandardOutput = $true
    $start.RedirectStandardError = $true
    foreach ($name in $attemptEnvironmentNames) {
        [void]$start.Environment.Remove($name)
    }
    foreach ($entry in $Environment.GetEnumerator()) {
        $start.Environment[[string]$entry.Key] = [string]$entry.Value
    }
    foreach ($argument in $Arguments) { [void]$start.ArgumentList.Add($argument) }
    $process = [Diagnostics.Process]::new()
    $process.StartInfo = $start
    $timer = [Diagnostics.Stopwatch]::StartNew()
    Assert-R23D5Exact $process.Start() "QSDK-R23D5 failed to start $FileName"
    $stdoutTask = $process.StandardOutput.ReadToEndAsync()
    $stderrTask = $process.StandardError.ReadToEndAsync()
    $timedOut = $false
    $nextHeartbeat = 30.0
    while (-not $process.WaitForExit(1000)) {
        if ($timer.Elapsed.TotalSeconds -ge $nextHeartbeat) {
            Write-Host (
                "QSDK_R23D5_PROGRESS process=$([IO.Path]::GetFileName($FileName)) " +
                "elapsed_seconds=" + $timer.Elapsed.TotalSeconds.ToString(
                    "F1", [Globalization.CultureInfo]::InvariantCulture
                )
            )
            $nextHeartbeat += 30.0
        }
        if ($timer.Elapsed.TotalSeconds -ge $TimeoutSeconds) {
            $timedOut = $true
            try { $process.Kill($true) } catch { }
            [void]$process.WaitForExit(10000)
            break
        }
    }
    $timer.Stop()
    $result = [ordered]@{
        exit_code = if ($process.HasExited) { $process.ExitCode } else { -1 }
        timed_out = $timedOut
        duration_seconds = $timer.Elapsed.TotalSeconds
        stdout = $stdoutTask.GetAwaiter().GetResult()
        stderr = $stderrTask.GetAwaiter().GetResult()
    }
    $process.Dispose()
    return $result
}

function Get-R23D5JsonMarker {
    param(
        [Parameter(Mandatory)][string]$Text,
        [Parameter(Mandatory)][string]$Prefix
    )
    $lines = @($Text -split "`r?`n" | Where-Object {
        $_.StartsWith($Prefix, [StringComparison]::Ordinal)
    })
    Assert-R23D5Exact ($lines.Count -eq 1) (
        "QSDK-R23D5 expected one '$Prefix' marker, observed $($lines.Count)"
    )
    return $lines[0].Substring($Prefix.Length) |
        ConvertFrom-Json -AsHashtable -Depth 100
}

function Resolve-R23D5ApplicationPath {
    param(
        [Parameter(Mandatory)][string]$Command,
        [Parameter(Mandatory)][string]$Label
    )
    Assert-R23D5Exact (-not [string]::IsNullOrWhiteSpace($Command)) (
        "QSDK-R23D5 $Label command is empty"
    )
    $resolved = if ([IO.Path]::IsPathFullyQualified($Command)) {
        [IO.Path]::GetFullPath($Command)
    } else {
        $matches = @(Get-Command `
            -Name $Command `
            -CommandType Application `
            -All `
            -ErrorAction Stop)
        Assert-R23D5Exact ($matches.Count -gt 0) (
            "QSDK-R23D5 $Label command did not resolve: $Command"
        )
        $source = [string]$matches[0].Source
        Assert-R23D5Exact (
            -not [string]::IsNullOrWhiteSpace($source) -and
            -not $source.Contains("`r") -and
            -not $source.Contains("`n")
        ) "QSDK-R23D5 $Label first application path is invalid: $source"
        [IO.Path]::GetFullPath($source)
    }
    Assert-R23D5Exact (
        -not $resolved.Contains("`r") -and
        -not $resolved.Contains("`n") -and
        (Test-Path -LiteralPath $resolved -PathType Leaf)
    ) "QSDK-R23D5 $Label application is missing or invalid: $resolved"
    return $resolved
}

function Invoke-R23D5Gate {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$PassPrefix,
        [string[]]$AdditionalArguments = @()
    )
    $result = Invoke-R23D5Process `
        -FileName $resolvedPowerShellPath `
        -Arguments (@("-NoLogo", "-NoProfile", "-File", $Path) + $AdditionalArguments) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds $GateTimeoutSeconds
    if ($result.stdout) { Write-Host ([string]$result.stdout).TrimEnd() }
    if ($result.stderr) { Write-Host ([string]$result.stderr).TrimEnd() }
    $markerCount = @(([string]$result.stdout -split "`r?`n") | Where-Object {
        $_.StartsWith($PassPrefix, [StringComparison]::Ordinal)
    }).Count
    Assert-R23D5Exact (
        -not [bool]$result.timed_out -and
        [int]$result.exit_code -eq 0 -and
        $markerCount -eq 1
    ) "QSDK-R23D5 zero-world gate failed: $Path"
    return $result
}

function Get-R23D5MediaType {
    param([Parameter(Mandatory)][string]$Path)
    switch ([IO.Path]::GetExtension($Path).ToLowerInvariant()) {
        ".json" { return "application/json" }
        ".ps1" { return "text/x-powershell" }
        ".py" { return "text/x-python" }
        ".gd" { return "text/x-gdscript" }
        ".rs" { return "text/x-rust" }
        ".toml" { return "application/toml" }
        default { return "application/octet-stream" }
    }
}

function Get-R23D5StageBCellIds {
    return @($stageBCellIds)
}

function Get-R23D5SourceBindingPaths {
    param([Parameter(Mandatory)]$Implementation)
    $paths = [Collections.Generic.List[string]]::new()
    foreach ($path in @($Implementation.source_binding_policy.exact_paths)) {
        $paths.Add(([string]$path).Replace("\", "/"))
    }
    foreach ($prefix in @($Implementation.source_binding_policy.tracked_prefixes)) {
        $expanded = @((Invoke-R23D5Git @("ls-files", "--", [string]$prefix)) -split "`n" |
            Where-Object { -not [string]::IsNullOrWhiteSpace($_) })
        Assert-R23D5Exact ($expanded.Count -gt 0) (
            "QSDK-R23D5 source prefix expanded to zero files: $prefix"
        )
        foreach ($path in $expanded) { $paths.Add($path.Replace("\", "/")) }
    }
    $duplicates = @($paths | Group-Object | Where-Object Count -gt 1)
    $duplicateNames = @(
        $duplicates | ForEach-Object { [string]$_.Name }
    )
    Assert-R23D5Exact ($duplicates.Count -eq 0) (
        "QSDK-R23D5 source binding paths contain duplicates: " +
        ($duplicateNames -join ",")
    )
    $manifest = Get-R23D5DependencyManifest -RepoRoot $repoRoot
    $pathSet = [Collections.Generic.HashSet[string]]::new(
        [StringComparer]::Ordinal
    )
    foreach ($path in $paths) { [void]$pathSet.Add([string]$path) }
    $missingDependencies = @(
        @($manifest.union_paths) | Where-Object {
            -not $pathSet.Contains([string]$_)
        }
    )
    Assert-R23D5Exact ($missingDependencies.Count -eq 0) (
        "QSDK-R23D5 source binding policy does not cover dependency union: " +
        ($missingDependencies -join ",")
    )
    return @($paths)
}

function Get-R23D5SourceBindings {
    param([Parameter(Mandatory)]$Implementation)
    $paths = @(Get-R23D5SourceBindingPaths $Implementation)
    $bindings = [Collections.Generic.List[object]]::new()
    foreach ($relativePath in $paths) {
        $absolutePath = Join-Path $repoRoot $relativePath
        Assert-R23D5Exact (Test-Path -LiteralPath $absolutePath -PathType Leaf) (
            "QSDK-R23D5 source binding is missing: $relativePath"
        )
        $trackedOid = Invoke-R23D5Git @("rev-parse", "HEAD:$relativePath")
        $rawOid = Invoke-R23D5Git @(
            "hash-object", "--no-filters", "--", $relativePath
        )
        Assert-R23D5Exact ($trackedOid -ceq $rawOid) (
            "QSDK-R23D5 checkout bytes differ from the Git blob: $relativePath"
        )
        $bindings.Add([ordered]@{
            path = $relativePath
            raw_sha256 = Get-R23D5RawSha256 $absolutePath
            git_blob_oid = $trackedOid
            raw_checkout_equals_git_blob = $true
            media_type = Get-R23D5MediaType $relativePath
        })
    }
    $manifest = Get-R23D5DependencyManifest -RepoRoot $repoRoot
    $requiredReceipts = @(
        New-R23D5DependencyReceipts -RepoRoot $repoRoot -Manifest $manifest
    )
    $closure = Test-R23D5DependencyReceiptClosure `
        -Manifest $manifest `
        -RequiredReceipts $requiredReceipts `
        -SourceBindings @($bindings)
    Assert-R23D5Exact ([bool]$closure.ok) (
        "QSDK-R23D5 source bindings do not close the worker dependency union: " +
        ([string]$closure.failure_code)
    )
    return @($bindings)
}

function Assert-R23D5FrozenBindings {
    param([Parameter(Mandatory)]$Freeze)
    foreach ($binding in @($Freeze.source_bindings)) {
        $path = Join-Path $repoRoot ([string]$binding.path)
        Assert-R23D5Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$binding.raw_sha256 -ceq (Get-R23D5RawSha256 $path) -and
            [string]$binding.git_blob_oid -ceq
                (Invoke-R23D5Git @("rev-parse", "HEAD:$([string]$binding.path)")) -and
            [string]$binding.git_blob_oid -ceq
                (Invoke-R23D5Git @(
                    "hash-object", "--no-filters", "--", [string]$binding.path
                ))
        ) "QSDK-R23D5 frozen source binding changed: $([string]$binding.path)"
    }
    foreach ($runtime in @($Freeze.runtime_artifacts)) {
        $path = [IO.Path]::GetFullPath([string]$runtime.path)
        Assert-R23D5Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$runtime.raw_sha256 -ceq (Get-R23D5RawSha256 $path)
        ) "QSDK-R23D5 runtime artifact changed: $path"
    }
    foreach ($runtime in @($Freeze.external_runtime_bindings)) {
        $path = [IO.Path]::GetFullPath([string]$runtime.path)
        Assert-R23D5Exact (
            (Test-Path -LiteralPath $path -PathType Leaf) -and
            [string]$runtime.raw_sha256 -ceq (Get-R23D5RawSha256 $path)
        ) "QSDK-R23D5 external runtime changed: $path"
    }
}

function Publish-R23D5BoundInputs {
    param(
        [Parameter(Mandatory)]$SourceBindings,
        [Parameter(Mandatory)]$RuntimeArtifacts,
        [Parameter(Mandatory)]$ExternalRuntimeBindings,
        [Parameter(Mandatory)][string]$AttestationPath
    )
    $sourceReceipts = [Collections.Generic.List[object]]::new()
    foreach ($binding in @($SourceBindings)) {
        $sourceReceipts.Add((Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath (Join-Path $repoRoot ([string]$binding.path)) `
            -MediaType ([string]$binding.media_type)))
    }
    $runtimeReceipts = [Collections.Generic.List[object]]::new()
    foreach ($runtime in @($RuntimeArtifacts)) {
        $runtimeReceipts.Add((Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath ([string]$runtime.path) `
            -MediaType ([string]$runtime.media_type)))
    }
    $externalReceipts = [Collections.Generic.List[object]]::new()
    foreach ($runtime in @($ExternalRuntimeBindings)) {
        $externalReceipts.Add((Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath ([string]$runtime.path) `
            -MediaType ([string]$runtime.media_type)))
    }
    $attestationReceipt = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $AttestationPath `
        -MediaType "application/json"
    return [ordered]@{
        source_bindings = @($sourceReceipts)
        runtime_artifacts = @($runtimeReceipts)
        external_runtime_bindings = @($externalReceipts)
        full_godot_attestation = $attestationReceipt
        physical_acceptance_authority = $false
    }
}

function Get-R23D5ExternalRuntimeBindings {
    return @(
        [ordered]@{
            name = "godot_jolt_host"
            path = [IO.Path]::GetFullPath($Godot)
            raw_sha256 = Get-R23D5RawSha256 $Godot
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "mujoco_python_host"
            path = [IO.Path]::GetFullPath($mujocoPython)
            raw_sha256 = Get-R23D5RawSha256 $mujocoPython
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "evaluator_python_host"
            path = $resolvedPythonPath
            raw_sha256 = Get-R23D5RawSha256 $resolvedPythonPath
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "powershell_trace_retainer_host"
            path = $resolvedPowerShellPath
            raw_sha256 = Get-R23D5RawSha256 $resolvedPowerShellPath
            media_type = "application/vnd.microsoft.portable-executable"
        }
    )
}

function Initialize-R23D5RuntimeArtifacts {
    param([Parameter(Mandatory)][string]$SourceCommit)
    . $runtimeMaterializationPath
    $targetRoot = Join-Path $sdkRoot "target"
    $sdkManifest = Join-Path $sdkRoot "Cargo.toml"
    $rapierManifest = Join-Path $sdkRoot "adapters\rapier\Cargo.toml"
    $builds = [ordered]@{}
    $builds.locomotion_core = Invoke-SporeSporeR23D3PinnedCargo `
        -RepoRoot $repoRoot `
        -SourceCommit $SourceCommit `
        -TargetRoot $targetRoot `
        -CargoArguments @(
            "build", "--quiet", "--release", "--locked", "--offline",
            "--manifest-path", $sdkManifest,
            "--package", "sporespore-locomotion-core"
        )
    $builds.godot_adapter = Invoke-SporeSporeR23D3PinnedCargo `
        -RepoRoot $repoRoot `
        -SourceCommit $SourceCommit `
        -TargetRoot $targetRoot `
        -CargoArguments @(
            "build", "--quiet", "--locked", "--offline",
            "--manifest-path", $sdkManifest,
            "--package", "sporespore-godot-adapter"
        )
    $builds.rapier_worker = Invoke-SporeSporeR23D3PinnedCargo `
        -RepoRoot $repoRoot `
        -SourceCommit $SourceCommit `
        -TargetRoot $targetRoot `
        -CargoArguments @(
            "build", "--quiet", "--release", "--locked", "--offline",
            "--manifest-path", $rapierManifest,
            "--bin", "qsdk_r23d5_dependency_closed"
        )
    $artifacts = [ordered]@{
        locomotion_core = Join-Path $targetRoot (
            "release\sporespore_locomotion_core.dll"
        )
        godot_adapter = Join-Path $targetRoot (
            "debug\sporespore_godot_adapter.dll"
        )
        rapier_worker = Join-Path $targetRoot (
            "release\qsdk_r23d5_dependency_closed.exe"
        )
    }
    foreach ($artifact in $artifacts.Values) {
        Assert-R23D5Exact (Test-Path -LiteralPath $artifact -PathType Leaf) (
            "QSDK-R23D5 materialized runtime artifact is missing: $artifact"
        )
    }
    return [ordered]@{
        source_commit = $SourceCommit
        target_root = $targetRoot
        builds = $builds
        artifacts = $artifacts
        physical_acceptance_authority = $false
    }
}

function Get-R23D5RuntimeArtifacts {
    param([Parameter(Mandatory)]$Materialization)
    $values = @(
        [ordered]@{
            name = "locomotion_core"
            path = [IO.Path]::GetFullPath(
                [string]$Materialization.artifacts.locomotion_core
            )
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "godot_adapter"
            path = [IO.Path]::GetFullPath(
                [string]$Materialization.artifacts.godot_adapter
            )
            media_type = "application/vnd.microsoft.portable-executable"
        },
        [ordered]@{
            name = "rapier_worker"
            path = [IO.Path]::GetFullPath(
                [string]$Materialization.artifacts.rapier_worker
            )
            media_type = "application/vnd.microsoft.portable-executable"
        }
    )
    foreach ($value in $values) {
        Assert-R23D5Exact (Test-Path -LiteralPath $value.path -PathType Leaf) (
            "QSDK-R23D5 runtime artifact is missing: $($value.path)"
        )
        $value.raw_sha256 = Get-R23D5RawSha256 $value.path
    }
    return $values
}

function Invoke-R23D5Evaluation {
    param(
        [Parameter(Mandatory)][ValidateSet("stage-a", "complete")]
        [string]$Kind,
        [Parameter(Mandatory)][string]$EvaluationRoot,
        [Parameter(Mandatory)][string]$StageAManifest,
        [string]$StageBManifest = ""
    )
    if ($Kind -ceq "stage-a") {
        $arguments = @(
            $evaluatorPath, "evaluate-stage-a", "--manifest", $StageAManifest
        )
        $prefix = "QSDK_R23D5_STAGE_A_EVALUATION "
    } else {
        $arguments = @(
            $evaluatorPath, "evaluate-complete",
            "--stage-a-manifest", $StageAManifest,
            "--stage-b-manifest", $StageBManifest
        )
        $prefix = "QSDK_R23D5_COMPLETE_EVALUATION "
    }
    $result = Invoke-R23D5Process `
        -FileName $resolvedPythonPath `
        -Arguments $arguments `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 300
    [void][IO.Directory]::CreateDirectory($EvaluationRoot)
    $stdoutPath = Join-Path $EvaluationRoot "stdout.txt"
    $stderrPath = Join-Path $EvaluationRoot "stderr.txt"
    $processPath = Join-Path $EvaluationRoot "process.json"
    [IO.File]::WriteAllText(
        $stdoutPath, [string]$result.stdout, [Text.UTF8Encoding]::new($false)
    )
    [IO.File]::WriteAllText(
        $stderrPath, [string]$result.stderr, [Text.UTF8Encoding]::new($false)
    )
    Write-R23D5NewJson -Path $processPath -Value ([ordered]@{
        schema_version = "sporespore_qsdk_r23d5_evaluator_process_v1"
        kind = $Kind
        exit_code = [int]$result.exit_code
        timed_out = [bool]$result.timed_out
        duration_seconds = [double]$result.duration_seconds
        stage_a_manifest = $StageAManifest
        stage_b_manifest = $StageBManifest
        physical_acceptance_authority = $false
    })
    $stdoutCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $stdoutPath -MediaType "text/plain"
    $stderrCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $stderrPath -MediaType "text/plain"
    $processCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $processPath -MediaType "application/json"
    Assert-R23D5Exact (-not [bool]$result.timed_out) (
        "QSDK-R23D5 evaluator timed out: $Kind"
    )
    $evaluation = Get-R23D5JsonMarker -Text $result.stdout -Prefix $prefix
    $evaluationPath = Join-Path $EvaluationRoot "evaluation.json"
    Write-R23D5NewJson -Path $evaluationPath -Value $evaluation
    $evaluationCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $evaluationPath -MediaType "application/json"
    return [ordered]@{
        process = $result
        evaluation = $evaluation
        retention = [ordered]@{
            stdout = $stdoutCas
            stderr = $stderrCas
            process = $processCas
            output = $evaluationCas
        }
    }
}

function Invoke-R23D5PhysicalCell {
    param(
        [Parameter(Mandatory)][string]$StageId,
        [Parameter(Mandatory)][string]$EngineId,
        [Parameter(Mandatory)][string]$ArmId,
        [Parameter(Mandatory)][string]$SourceCommit,
        [Parameter(Mandatory)][string]$FreezePayloadPath,
        [Parameter(Mandatory)][string]$AttemptPayloadPath,
        [Parameter(Mandatory)][string]$Token,
        [Parameter(Mandatory)][string]$AttemptRoot,
        [Parameter(Mandatory)][string]$CellRoot,
        [Parameter(Mandatory)]$RuntimeArtifacts,
        [Parameter(Mandatory)]$Freeze
    )
    Assert-R23D5FrozenBindings $Freeze
    [void][IO.Directory]::CreateDirectory($CellRoot)
    $cellId = if ($StageId -ceq $stageAId) {
        "mujoco__terminal_restoration__$ArmId"
    } else {
        "$EngineId`__onset_600__$ArmId"
    }
    $environment = [ordered]@{
        SPORESPORE_QSDK_R23D5_FREEZE = $FreezePayloadPath
        SPORESPORE_QSDK_R23D5_ATTEMPT = $AttemptPayloadPath
        SPORESPORE_QSDK_R23D5_TOKEN = $Token
        SPORESPORE_QSDK_R23D5_STAGE = $StageId
        SPORESPORE_QSDK_R23D5_CELL = $cellId
        SPORESPORE_QSDK_R23D5_ENGINE = $EngineId
        SPORESPORE_QSDK_R23D5_ATTEMPT_ROOT = $AttemptRoot
        SPORESPORE_QSDK_R23D5_PYTHON = $resolvedPythonPath
        SPORESPORE_QSDK_R23D5_POWERSHELL = $resolvedPowerShellPath
    }
    $fileName = ""
    $arguments = @()
    $workingDirectory = $repoRoot
    $successPrefix = ""
    $failurePrefix = ""
    $singleTerminalPrefix = ""
    if ($EngineId -ceq "godot_jolt") {
        $fileName = $Godot
        $environment.APPDATA = Join-Path $CellRoot "appdata"
        $environment.LOCALAPPDATA = Join-Path $CellRoot "localappdata"
        [void][IO.Directory]::CreateDirectory($environment.APPDATA)
        [void][IO.Directory]::CreateDirectory($environment.LOCALAPPDATA)
        $arguments = @(
            "--headless", "--path", $repoRoot,
            "--log-file", (Join-Path $CellRoot "godot.log"),
            "--script", $godotWorkerResource, "--",
            "--stage", $StageId, "--arm", $ArmId,
            "--source-commit", $SourceCommit
        )
        $successPrefix = "QSDK_R23D5_GODOT_JOLT_CELL "
        $failurePrefix = "QSDK_R23D5_GODOT_JOLT_FAILURE "
    } elseif ($EngineId -ceq "rapier_parry") {
        $fileName = [string]$RuntimeArtifacts.rapier_worker
        $arguments = @(
            "--stage", $StageId, "--arm", $ArmId,
            "--source-commit", $SourceCommit
        )
        $successPrefix = "QSDK_R23D5_RAPIER_CELL "
        $failurePrefix = "QSDK_R23D5_RAPIER_FAILURE "
    } elseif ($EngineId -ceq "mujoco") {
        $fileName = $mujocoPython
        $workingDirectory = $repoRoot
        $environment.SPORESPORE_LOCOMOTION_LIBRARY =
            [string]$RuntimeArtifacts.locomotion_core
        $environment.PYTHONPATH = (
            $mujocoRoot + [IO.Path]::PathSeparator + $pythonCoreRoot
        )
        $arguments = @(
            "-m", "sporespore_mujoco_adapter.qsdk_r23d5_dependency_closed",
            "physical", "--stage-id", $StageId, "--arm-id", $ArmId,
            "--source-commit", $SourceCommit
        )
        $singleTerminalPrefix = "QSDK_R23D5_TERMINAL "
    } else {
        throw "QSDK-R23D5 unknown physical engine: $EngineId"
    }

    Write-Host "QSDK_R23D5_CELL_BEGIN stage=$StageId cell=$cellId"
    $launchSucceeded = $false
    try {
        $result = Invoke-R23D5Process `
            -FileName $fileName `
            -Arguments $arguments `
            -WorkingDirectory $workingDirectory `
            -Environment $environment `
            -TimeoutSeconds $CellTimeoutSeconds
        $launchSucceeded = $true
    } catch {
        $result = [ordered]@{
            exit_code = -1
            timed_out = $false
            duration_seconds = 0.0
            stdout = ""
            stderr = "SUPERVISOR_PROCESS_START_EXCEPTION:$($_.Exception.Message)"
        }
    }
    $stdoutPath = Join-Path $CellRoot "stdout.txt"
    $stderrPath = Join-Path $CellRoot "stderr.txt"
    $processPath = Join-Path $CellRoot "process.json"
    [IO.File]::WriteAllText(
        $stdoutPath, [string]$result.stdout,
        [Text.UTF8Encoding]::new($false)
    )
    [IO.File]::WriteAllText(
        $stderrPath, [string]$result.stderr,
        [Text.UTF8Encoding]::new($false)
    )
    Write-R23D5NewJson -Path $processPath -Value ([ordered]@{
        schema_version = "sporespore_qsdk_r23d5_worker_process_v1"
        stage_id = $StageId
        cell_id = $cellId
        engine_id = $EngineId
        process_launch_succeeded = $launchSucceeded
        exit_code = [int]$result.exit_code
        timed_out = [bool]$result.timed_out
        duration_seconds = [double]$result.duration_seconds
        physical_acceptance_authority = $false
    })
    $stdoutCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $stdoutPath -MediaType "text/plain"
    $stderrCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $stderrPath -MediaType "text/plain"
    $processCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot -ArtifactPath $processPath -MediaType "application/json"
    $godotLogCas = $null
    $godotLogPath = Join-Path $CellRoot "godot.log"
    if (Test-Path -LiteralPath $godotLogPath -PathType Leaf) {
        $godotLogCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $godotLogPath -MediaType "text/plain"
    }

    $familyId = switch -CaseSensitive ($EngineId) {
        "mujoco" { "mujoco_single_terminal_prefix" }
        "rapier_parry" { "rapier_separate_success_failure_prefixes" }
        "godot_jolt" { "godot_jolt_separate_success_failure_prefixes" }
        default { throw "QSDK-R23D5 unknown terminal marker family: $EngineId" }
    }
    $engineLogRequired = $EngineId -ceq "godot_jolt"
    $retentionComplete = (
        $null -ne $processCas -and
        $null -ne $stdoutCas -and
        $null -ne $stderrCas -and
        (-not $engineLogRequired -or $null -ne $godotLogCas)
    )
    $retentionReceipt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d5_process_retention_receipt_v1"
        retained_before_marker_interpretation = $true
        process_raw_sha256 = [string]$processCas.sha256
        stdout_raw_sha256 = [string]$stdoutCas.sha256
        stderr_raw_sha256 = [string]$stderrCas.sha256
        engine_log_required = $engineLogRequired
        engine_log_raw_sha256 = if ($null -ne $godotLogCas) {
            [string]$godotLogCas.sha256
        } else { "" }
        all_retained_bytes_content_addressed = $retentionComplete
    }
    $classification = $null
    $terminal = $null
    $markerKind = "supervisor_process_failure"
    try {
        $classification = Get-R23D5TerminalMarkerClassification `
            -FamilyId $familyId `
            -Stdout ([string]$result.stdout) `
            -ExitCode ([int]$result.exit_code) `
            -RetentionReceipt $retentionReceipt
        if ($null -ne $classification.terminal_entry) {
            $terminal = $classification.terminal_entry
        }
        $markerKind = switch -CaseSensitive (
            [string]$classification.classification
        ) {
            "success" { "successful_report" }
            "worker_failure" { "worker_failure" }
            default { "supervisor_process_failure" }
        }
    } catch {
        $classification = [ordered]@{
            schema_version = "sporespore_qsdk_r23d5_terminal_marker_classifier_v1"
            family_id = $familyId
            classification = "supervisor_process_failure"
            failure_code = "R23D5_TERMINAL_CLASSIFIER_EXCEPTION"
            failure_detail = $_.Exception.Message
            recognized_marker_count = 0
            success_marker_count = 0
            failure_marker_count = 0
            malformed_marker_count = 0
            terminal_entry = $null
            physical_acceptance_authority = $false
        }
    }
    if ($null -eq $terminal -or $markerKind -ceq "supervisor_process_failure") {
        $terminal = [ordered]@{
            schema_version = "sporespore_qsdk_r23d5_supervisor_process_failure_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            stage_id = $StageId
            cell_id = $cellId
            engine_id = $EngineId
            arm_id = $ArmId
            source_commit = $SourceCommit
            process_launch_succeeded = $launchSucceeded
            process_exit_code = [int]$result.exit_code
            process_timed_out = [bool]$result.timed_out
            terminal_marker_classification = $classification
            retention_receipt = $retentionReceipt
            world_attempt_count_known = $false
            world_build_count_known = $false
            physical_acceptance_authority = $false
        }
        $markerKind = "supervisor_process_failure"
    }
    $terminalPath = Join-Path $CellRoot "terminal-entry.json"
    Write-R23D5NewJson -Path $terminalPath -Value $terminal
    $terminalCas = Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $terminalPath `
        -MediaType "application/json"
    Write-Host (
        "QSDK_R23D5_CELL_RETAINED stage=$StageId cell=$cellId " +
        "marker=$markerKind terminal_sha256=$([string]$terminalCas.sha256)"
    )
    return [ordered]@{
        stage_id = $StageId
        cell_id = $cellId
        engine_id = $EngineId
        arm_id = $ArmId
        process_launch_succeeded = $launchSucceeded
        process_exit_code = [int]$result.exit_code
        process_timed_out = [bool]$result.timed_out
        process_duration_seconds = [double]$result.duration_seconds
        terminal_marker_kind = $markerKind
        terminal_marker_classification = $classification
        terminal_entry_cas = $terminalCas
        stdout_cas = $stdoutCas
        stderr_cas = $stderrCas
        process_cas = $processCas
        godot_log_cas = $godotLogCas
        physical_acceptance_authority = $false
    }
}

function New-R23D5StageAuthorization {
    param(
        [Parameter(Mandatory)][string]$Path,
        [Parameter(Mandatory)][string]$AttemptId,
        [Parameter(Mandatory)][string]$Token,
        [Parameter(Mandatory)][string]$SourceCommit,
        [Parameter(Mandatory)][string]$FreezeSha256,
        [Parameter(Mandatory)][string]$AttemptRoot,
        [Parameter(Mandatory)][string[]]$OrderedStageACellIds,
        [Parameter(Mandatory)][AllowEmptyCollection()][string[]]$OrderedStageBCellIds,
        [Parameter(Mandatory)][string]$SelectedRestorationPolicyId,
        [Parameter(Mandatory)][string]$StageAuthorizationId,
        [Parameter(Mandatory)]$InputCas,
        [Parameter(Mandatory)]$ZeroWorldReceipt,
        [Parameter(Mandatory)][string]$AttestationSha256,
        [string]$ParentAuthorizationSha256 = ""
    )
    $attempt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d5_attempt_v1"
        attempt_id = $AttemptId
        stage_authorization_id = $StageAuthorizationId
        parent_stage_authorization_sha256 = $ParentAuthorizationSha256
        campaign_id = $campaignId
        gate_id = $gateId
        implementation_contract_raw_sha256 = Get-R23D5RawSha256 $implementationPath
        freeze_raw_sha256 = $FreezeSha256
        source_commit = $SourceCommit
        authorization_token = $Token
        attempt_root = $AttemptRoot
        selected_terminal_restoration_policy_id = $SelectedRestorationPolicyId
        selected_onset_id = if ($StageAuthorizationId -ceq "stage_b") {
            "onset_600"
        } else { "NONE" }
        ordered_stage_a_cell_ids = $OrderedStageACellIds
        ordered_stage_b_cell_ids = $OrderedStageBCellIds
        physical_execution_authorized = $true
        single_use_supervisor_authorization = $true
        source_worktree_clean = $true
        source_matches_live_github_main = $true
        operation_lock_held = $true
        full_godot_attestation_valid = $true
        full_godot_attestation_sha256 = $AttestationSha256
        content_addressed_inputs_retained = $true
        content_addressed_inputs = $InputCas
        complete_zero_world_gate_passed = $true
        zero_world_receipt = $ZeroWorldReceipt
        one_shot_attempt_unconsumed = $true
        replacement_or_selective_rerun_permitted = $false
        stage_a_reports_may_substitute_for_stage_b = $false
        physical_acceptance_authority = $false
    }
    Write-R23D5NewJson -Path $Path -Value $attempt
    return Publish-SporeSporeContentAddressedArtifact `
        -RepoRoot $repoRoot `
        -ArtifactPath $Path `
        -MediaType "application/json"
}

function Invoke-R23D5PhysicalCampaign {
    param(
        [Parameter(Mandatory)]$Source,
        [Parameter(Mandatory)]$Attestation,
        [Parameter(Mandatory)]$ZeroWorldReceipt,
        [Parameter(Mandatory)]$Implementation
    )
    $sourceAfterPreflight = Get-SporeSporeAttestationSourceIdentity `
        -RepoRoot $repoRoot `
        -RequireCleanPushedLive
    Assert-R23D5Exact (
        [string]$sourceAfterPreflight.commit -ceq [string]$Source.commit -and
        [string]$sourceAfterPreflight.tree_git_oid -ceq [string]$Source.tree_git_oid
    ) "QSDK-R23D5 source changed during the zero-world gate"
    Assert-R23D5Exact (
        [string](Invoke-R23D5Git @("status", "--porcelain=v1", "--untracked-files=all")) `
            -ceq ""
    ) "QSDK-R23D5 physical source is not clean after the zero-world gate"

    $evidenceRoot = Get-SporeSporeArtifactEvidenceRoot -RepoRoot $repoRoot
    $prior = @()
    if (Test-Path -LiteralPath $evidenceRoot -PathType Container) {
        $prior = @(Get-ChildItem -LiteralPath $evidenceRoot -Directory |
            Where-Object {
                $_.Name -like "qsdk-r23d5-*" -and (
                    (Test-Path -LiteralPath (Join-Path $_.FullName "stage-a-authorization.json")) -or
                    (Test-Path -LiteralPath (Join-Path $_.FullName "completion.json"))
                )
            })
    }
    Assert-R23D5Exact ($prior.Count -eq 0) (
        "QSDK-R23D5 one-shot identity already exists; rerun is forbidden"
    )
    $resolvedOutput = if ([string]::IsNullOrWhiteSpace($OutputRoot)) {
        Join-Path $evidenceRoot (
            "qsdk-r23d5-" + [DateTime]::UtcNow.ToString("yyyyMMddTHHmmssZ")
        )
    } else { [IO.Path]::GetFullPath($OutputRoot) }
    $evidencePrefix = $evidenceRoot.TrimEnd("\", "/") +
        [IO.Path]::DirectorySeparatorChar
    Assert-R23D5Exact (
        $resolvedOutput.StartsWith(
            $evidencePrefix, [StringComparison]::OrdinalIgnoreCase
        ) -and
        -not (Test-Path -LiteralPath $resolvedOutput)
    ) "QSDK-R23D5 output must be a new directory under $evidenceRoot"
    [void][IO.Directory]::CreateDirectory($resolvedOutput)

    $attemptConsumed = $false
    $completionPath = Join-Path $resolvedOutput "completion.json"
    try {
        $materialization = Initialize-R23D5RuntimeArtifacts `
            -SourceCommit ([string]$Source.commit)
        $runtimeArtifacts = Get-R23D5RuntimeArtifacts $materialization
        $runtimeMap = [ordered]@{
            locomotion_core = [string]$materialization.artifacts.locomotion_core
            godot_adapter = [string]$materialization.artifacts.godot_adapter
            rapier_worker = [string]$materialization.artifacts.rapier_worker
        }
        $sourceBindings = Get-R23D5SourceBindings $Implementation
        $externalRuntimeBindings = Get-R23D5ExternalRuntimeBindings
        $inputCas = Publish-R23D5BoundInputs `
            -SourceBindings $sourceBindings `
            -RuntimeArtifacts $runtimeArtifacts `
            -ExternalRuntimeBindings $externalRuntimeBindings `
            -AttestationPath $FullConformanceAttestation

        $freeze = [ordered]@{
            schema_version = "sporespore_qsdk_r23d5_physical_freeze_v1"
            status = "frozen_supervisor_only_physical_authorized"
            campaign_id = $campaignId
            gate_id = $gateId
            preregistration_raw_sha256 = Get-R23D5RawSha256 $preregistrationPath
            implementation_contract_raw_sha256 = Get-R23D5RawSha256 $implementationPath
            source_commit = [string]$Source.commit
            source_tree_git_oid = [string]$Source.tree_git_oid
            origin_main_commit = [string]$Source.origin_main
            live_github_main_commit = [string]$Source.live_github_main
            source_bindings = $sourceBindings
            runtime_artifacts = $runtimeArtifacts
            external_runtime_bindings = $externalRuntimeBindings
            runtime_materialization = $materialization
            content_addressed_inputs = $inputCas
            full_godot_attestation_sha256 = [string]$Attestation.sha256
            complete_zero_world_gate_passed = $true
            zero_world_receipt = $ZeroWorldReceipt
            declared_stage_a_world_count = 2
            declared_stage_b_world_count_if_selected = 9
            serial_execution_required = $true
            single_supervisor_attempt_required = $true
            stage_a_reports_may_substitute_for_stage_b = $false
            replacement_or_selective_rerun_permitted = $false
            source_checkout_bytes_equal_git_blobs = $true
            reproducible_runtime_materialization_passed = $true
            physical_execution_authorized = $true
            physical_acceptance_authority = $false
        }
        $freezePath = Join-Path $resolvedOutput "physical-freeze.json"
        Write-R23D5NewJson -Path $freezePath -Value $freeze
        $freezeCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot `
            -ArtifactPath $freezePath `
            -MediaType "application/json"
        Assert-R23D5FrozenBindings $freeze

        $attemptId = [guid]::NewGuid().ToString("N")
        $stageAToken = [guid]::NewGuid().ToString("N")
        $stageAAuthorizationPath = Join-Path $resolvedOutput "stage-a-authorization.json"
        $stageAAuthorizationCas = New-R23D5StageAuthorization `
            -Path $stageAAuthorizationPath `
            -AttemptId $attemptId `
            -Token $stageAToken `
            -SourceCommit ([string]$Source.commit) `
            -FreezeSha256 ([string]$freezeCas.sha256) `
            -AttemptRoot $resolvedOutput `
            -OrderedStageACellIds $stageACellIds `
            -OrderedStageBCellIds @() `
            -SelectedRestorationPolicyId "UNSELECTED" `
            -StageAuthorizationId "stage_a" `
            -InputCas $inputCas `
            -ZeroWorldReceipt $ZeroWorldReceipt `
            -AttestationSha256 ([string]$Attestation.sha256)
        $attemptConsumed = $true

        $stageACells = [Collections.Generic.List[object]]::new()
        foreach ($cellId in $stageACellIds) {
            $parts = $cellId -split "__", 3
            $stageACells.Add((Invoke-R23D5PhysicalCell `
                -StageId $stageAId `
                -EngineId "mujoco" `
                -ArmId $parts[2] `
                -SourceCommit ([string]$Source.commit) `
                -FreezePayloadPath ([string]$freezeCas.payload_path) `
                -AttemptPayloadPath ([string]$stageAAuthorizationCas.payload_path) `
                -Token $stageAToken `
                -AttemptRoot $resolvedOutput `
                -CellRoot (Join-Path $resolvedOutput ("stage-a\" + $cellId)) `
                -RuntimeArtifacts $runtimeMap `
                -Freeze $freeze))
        }
        $stageAPaths = @($stageACells | ForEach-Object {
            [string]$_.terminal_entry_cas.payload_path
        })
        $stageAManifestPath = Join-Path $resolvedOutput "stage-a-terminal-paths.json"
        Write-R23D5Manifest -Path $stageAManifestPath -Paths $stageAPaths
        $stageAManifestCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $stageAManifestPath `
            -MediaType "application/json"
        $stageAEvaluationResult = Invoke-R23D5Evaluation `
            -Kind "stage-a" `
            -EvaluationRoot (Join-Path $resolvedOutput "stage-a-evaluator") `
            -StageAManifest ([string]$stageAManifestCas.payload_path)

        $stageBCells = [Collections.Generic.List[object]]::new()
        $stageBAuthorizationCas = $null
        $selectedPolicy = [string](
            $stageAEvaluationResult.evaluation.selected_terminal_restoration_policy_id
        )
        if ([bool]$stageAEvaluationResult.evaluation.stage_b_launch_authorized) {
            Assert-R23D5Exact (
                [bool]$stageAEvaluationResult.evaluation.valid -and
                $selectedPolicy -ceq "contact_acquisition_pose_hold_v1" -and
                [int]$stageAEvaluationResult.process.exit_code -eq 0
            ) "QSDK-R23D5 Stage B authorization state is inconsistent"
            $stageBCellIds = Get-R23D5StageBCellIds
            $stageBToken = [guid]::NewGuid().ToString("N")
            $stageBAuthorizationPath = Join-Path `
                $resolvedOutput `
                "stage-b-authorization.json"
            $stageBAuthorizationCas = New-R23D5StageAuthorization `
                -Path $stageBAuthorizationPath `
                -AttemptId $attemptId `
                -Token $stageBToken `
                -SourceCommit ([string]$Source.commit) `
                -FreezeSha256 ([string]$freezeCas.sha256) `
                -AttemptRoot $resolvedOutput `
                -OrderedStageACellIds $stageACellIds `
                -OrderedStageBCellIds $stageBCellIds `
                -SelectedRestorationPolicyId $selectedPolicy `
                -StageAuthorizationId "stage_b" `
                -InputCas $inputCas `
                -ZeroWorldReceipt $ZeroWorldReceipt `
                -AttestationSha256 ([string]$Attestation.sha256) `
                -ParentAuthorizationSha256 ([string]$stageAAuthorizationCas.sha256)
            foreach ($cellId in $stageBCellIds) {
                $parts = $cellId -split "__", 3
                $stageBCells.Add((Invoke-R23D5PhysicalCell `
                    -StageId $stageBId `
                    -EngineId $parts[0] `
                    -ArmId $parts[2] `
                    -SourceCommit ([string]$Source.commit) `
                    -FreezePayloadPath ([string]$freezeCas.payload_path) `
                    -AttemptPayloadPath ([string]$stageBAuthorizationCas.payload_path) `
                    -Token $stageBToken `
                    -AttemptRoot $resolvedOutput `
                    -CellRoot (Join-Path $resolvedOutput ("stage-b\" + $cellId)) `
                    -RuntimeArtifacts $runtimeMap `
                    -Freeze $freeze))
            }
        } else {
            Assert-R23D5Exact (
                -not [bool]$stageAEvaluationResult.evaluation.valid -or
                $selectedPolicy -ceq "NONE"
            ) "QSDK-R23D5 Stage B was withheld for an unknown selector state"
        }

        $stageBPaths = @($stageBCells | ForEach-Object {
            [string]$_.terminal_entry_cas.payload_path
        })
        $stageBManifestPath = Join-Path $resolvedOutput "stage-b-terminal-paths.json"
        Write-R23D5Manifest -Path $stageBManifestPath -Paths $stageBPaths
        $stageBManifestCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $stageBManifestPath `
            -MediaType "application/json"
        $completeResult = Invoke-R23D5Evaluation `
            -Kind "complete" `
            -EvaluationRoot (Join-Path $resolvedOutput "complete-evaluator") `
            -StageAManifest ([string]$stageAManifestCas.payload_path) `
            -StageBManifest ([string]$stageBManifestCas.payload_path)

        $classification = [string]$completeResult.evaluation.classification
        $validResult = -not $classification.StartsWith(
            "invalid", [StringComparison]::Ordinal
        )
        $report = [ordered]@{
            schema_version = "sporespore_qsdk_r23d5_campaign_report_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            source = $Source
            attempt_id = $attemptId
            implementation_contract_raw_sha256 = Get-R23D5RawSha256 $implementationPath
            freeze_cas = $freezeCas
            stage_a_authorization_cas = $stageAAuthorizationCas
            stage_b_authorization_cas = $stageBAuthorizationCas
            stage_a_manifest_cas = $stageAManifestCas
            stage_b_manifest_cas = $stageBManifestCas
            stage_a_evaluator_retention = $stageAEvaluationResult.retention
            complete_evaluator_retention = $completeResult.retention
            ordered_stage_a_cells = @($stageACells)
            ordered_stage_b_cells = @($stageBCells)
            stage_a_evaluation = $stageAEvaluationResult.evaluation
            complete_evaluation = $completeResult.evaluation
            selected_terminal_restoration_policy_id = $selectedPolicy
            stage_b_launched = $stageBCells.Count -gt 0
            stage_a_world_count = 2
            stage_b_world_count = $stageBCells.Count
            result_classification = $classification
            development_result_valid = $validResult
            claims = [ordered]@{
                development_screen_only = $true
                command_conditioned_turning = $false
                bilateral_signed_turning = $false
                portable_basic_turning = $false
                cross_engine_equivalence = $false
                q_sdk_r23_satisfied = $false
                prone_to_standing = $false
                release_authorized = $false
                physical_acceptance_authority = $false
            }
        }
        $reportPath = Join-Path $resolvedOutput "report.json"
        Write-R23D5NewJson -Path $reportPath -Value $report
        $reportCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $reportPath `
            -MediaType "application/json"
        $completion = [ordered]@{
            schema_version = "sporespore_qsdk_r23d5_completion_v1"
            campaign_id = $campaignId
            gate_id = $gateId
            status = if ($validResult) {
                "$classification`_first_attempt"
            } else { "invalid_or_incomplete_first_attempt" }
            source_commit = [string]$Source.commit
            attempt_id = $attemptId
            selected_terminal_restoration_policy_id = $selectedPolicy
            stage_a_terminal_entry_count = $stageACells.Count
            stage_b_terminal_entry_count = $stageBCells.Count
            result_classification = $classification
            report_cas = $reportCas
            one_shot_identity_consumed = $true
            same_identity_rerun_allowed = $false
            command_conditioned_turning = $false
            q_sdk_r23_satisfied = $false
            cross_engine_equivalence = $false
            release_authorized = $false
            physical_acceptance_authority = $false
        }
        Write-R23D5NewJson -Path $completionPath -Value $completion
        $completionCas = Publish-SporeSporeContentAddressedArtifact `
            -RepoRoot $repoRoot -ArtifactPath $completionPath `
            -MediaType "application/json"
        Write-Host (
            "QSDK_R23D5_PHYSICAL_COMPLETE classification=$classification " +
            "selected_policy=$selectedPolicy stage_a_cells=$($stageACells.Count) " +
            "stage_b_cells=$($stageBCells.Count) " +
            "report_sha256=$([string]$reportCas.sha256) " +
            "completion_sha256=$([string]$completionCas.sha256) " +
            "turning=False equivalence=False release=False"
        )
        if (-not $validResult) {
            throw "QSDK-R23D5 retained an invalid or incomplete first attempt: $resolvedOutput"
        }
    } catch {
        if ($attemptConsumed -and -not (Test-Path -LiteralPath $completionPath)) {
            $emergency = [ordered]@{
                schema_version = "sporespore_qsdk_r23d5_completion_v1"
                campaign_id = $campaignId
                gate_id = $gateId
                status = "invalid_or_incomplete_first_attempt"
                source_commit = [string]$Source.commit
                failure_code = "SUPERVISOR_INFRASTRUCTURE_EXCEPTION"
                failure_detail = $_.Exception.Message
                one_shot_identity_consumed = $true
                same_identity_rerun_allowed = $false
                command_conditioned_turning = $false
                q_sdk_r23_satisfied = $false
                cross_engine_equivalence = $false
                release_authorized = $false
                physical_acceptance_authority = $false
            }
            Write-R23D5NewJson -Path $completionPath -Value $emergency
            [void](Publish-SporeSporeContentAddressedArtifact `
                -RepoRoot $repoRoot -ArtifactPath $completionPath `
                -MediaType "application/json")
        }
        throw
    }
}

Assert-R23D5Exact ($PreflightOnly.IsPresent -xor $RunPhysical.IsPresent) (
    "Specify exactly one of -PreflightOnly or -RunPhysical"
)
Assert-R23D5Exact (
    $RunPhysical.IsPresent -or (
        [string]::IsNullOrWhiteSpace($FullConformanceAttestation) -and
        [string]::IsNullOrWhiteSpace($OutputRoot)
    )
) "-FullConformanceAttestation and -OutputRoot require -RunPhysical"
if ($RunPhysical -and (Test-Path -LiteralPath $closurePath -PathType Leaf)) {
    Write-R23D5PhysicalRefusal -Reason "r23d5_identity_closed"
    throw "QSDK-R23D5 CLOSED: the one-shot identity is consumed; rerun is forbidden"
}
if ($RunPhysical -and [string]::IsNullOrWhiteSpace($FullConformanceAttestation)) {
    Write-R23D5PhysicalRefusal -Reason "matching_full_godot_v2_attestation_required"
    throw "QSDK-R23D5 physical execution requires a matching full-Godot V2 attestation"
}

Assert-R23D5Exact (
    (Invoke-R23D5Git @("rev-parse", "--show-toplevel")).Replace("/", "\") -ceq
        $repoRoot -and
    (Invoke-R23D5Git @("remote", "get-url", "origin")) -ceq
        "https://github.com/Slagathore/sporespore.git"
) "QSDK-R23D5 supervisor repository identity mismatch"
Assert-R23D5Exact (Test-Path -LiteralPath $Godot -PathType Leaf) (
    "QSDK-R23D5 Godot executable is missing: $Godot"
)
$resolvedPythonPath = Resolve-R23D5ApplicationPath `
    -Command $Python `
    -Label "evaluator Python"
$resolvedPowerShellPath = Resolve-R23D5ApplicationPath `
    -Command $PowerShell `
    -Label "PowerShell trace retainer"

$implementation = Get-Content -Raw -LiteralPath $implementationPath |
    ConvertFrom-Json -AsHashtable -Depth 100
$preregistration = Get-Content -Raw -LiteralPath $preregistrationPath |
    ConvertFrom-Json -AsHashtable -Depth 100
Assert-R23D5Exact (
    [string]$implementation.schema_version -ceq
        "sporespore_qsdk_r23d5_implementation_contract_v1" -and
    [string]$implementation.campaign_id -ceq $campaignId -and
    [string]$implementation.gate_id -ceq $gateId -and
    [string]$implementation.supervisor.path -ceq
        "sdk/run_qsdk_r23d5_supervisor.ps1" -and
    [int]$implementation.supervisor.stage_a_world_count -eq 2 -and
    [int]$implementation.supervisor.stage_b_world_count_if_launched -eq 9 -and
    [bool]$implementation.supervisor.stage_a_serial_without_outcome_early_stop -and
    [bool]$implementation.supervisor.stage_b_serial_without_outcome_early_stop -and
    [bool]$implementation.supervisor.stage_a_reports_may_substitute_for_stage_b_mujoco_reports -eq $false -and
    [bool]$implementation.supervisor.replacement_or_selective_rerun_permitted -eq $false -and
    [bool]$implementation.supervisor.single_supervisor_attempt_required -and
    [bool]$implementation.supervisor.stage_a_and_conditional_stage_b_share_one_attempt_id -and
    [bool]$implementation.supervisor.stage_a_authorization_is_immutable_before_first_stage_a_world -and
    [bool]$implementation.supervisor.stage_b_authorization_is_fresh_immutable_and_created_only_after_valid_selection -and
    [bool]$implementation.supervisor.stage_a_authorization_is_never_mutated_to_open_stage_b -and
    [bool]$implementation.supervisor.source_binding_path_composer_exercised_in_preflight -and
    [bool]$implementation.supervisor.dependency_manifest_composer_exercised_before_input_cas_and_attempt_authorization -and
    [bool]$implementation.supervisor.worker_required_sets_are_verified_as_source_binding_subsets -and
    [bool]$implementation.supervisor.process_stdout_stderr_and_required_engine_log_retained_before_marker_interpretation -and
    [bool]$implementation.supervisor.shared_terminal_marker_classifier_required -and
    [bool]$implementation.supervisor.every_launched_process_gets_a_content_addressed_terminal_entry -and
    [int]$implementation.dependency_closure.declared_unique_dependency_count -eq 21 -and
    [int]$implementation.dependency_closure.declared_worker_count -eq 3 -and
    [bool]$implementation.terminal_marker_contract.retained_before_marker_interpretation_required -and
    [bool]$implementation.terminal_marker_contract.process_start_exceptions_and_classifier_failures_still_require_terminal_entry_cas -and
    [string]$implementation.runtime_freeze.materialization_path -ceq
        "sdk/r23d3_reproducible_runtime_materialization.ps1" -and
    [bool]$implementation.runtime_freeze.source_bindings_must_equal_git_blob_bytes -and
    [bool]$implementation.runtime_freeze.msvc_brepro_required -and
    -not [bool]$implementation.authorization.physical_execution_authorized -and
    -not [bool]$implementation.authorization.physical_acceptance_authority -and
    [int]$implementation.authorization.world_attempt_count -eq 0 -and
    [int]$implementation.authorization.world_build_count -eq 0
) "QSDK-R23D5 implementation contract identity changed"
Assert-R23D5Exact (
    [string]$preregistration.schema_version -ceq
        "sporespore_qsdk_r23d5_dependency_closed_preregistration_v1" -and
    [string]$preregistration.campaign_id -ceq $campaignId -and
    [string]$preregistration.gate_id -ceq $gateId -and
    [int]$preregistration.frozen_schedule_and_gate_snapshot.turning_controller_semantic_step_count -eq 2992 -and
    [int]$preregistration.frozen_schedule_and_gate_snapshot.terminal_restoration_step_count -eq 540 -and
    [int]$preregistration.frozen_schedule_and_gate_snapshot.passive_settle_step_count -eq 240 -and
    [int]$preregistration.frozen_schedule_and_gate_snapshot.total_traced_step_count -eq 3772 -and
    [int]$preregistration.stage_a_mujoco_terminal_restoration_screen.declared_cell_count -eq 2 -and
    [int]$preregistration.stage_b_three_engine_confirmation.declared_cell_count_if_launched -eq 9 -and
    -not [bool]$preregistration.authorization.physical_execution_authorized
) "QSDK-R23D5 preregistration identity changed"

$declaredPaths = @(Get-R23D5SourceBindingPaths $implementation)
foreach ($relativePath in $declaredPaths) {
    Assert-R23D5Exact (
        Test-Path -LiteralPath (Join-Path $repoRoot $relativePath) -PathType Leaf
    ) "QSDK-R23D5 declared source binding is missing: $relativePath"
}

$physicalSource = $null
$physicalAttestation = $null
$operationLock = $null
if ($RunPhysical) {
    $physicalSource = Get-SporeSporeAttestationSourceIdentity `
        -RepoRoot $repoRoot `
        -RequireCleanPushedLive
    $physicalAttestation = Test-SporeSporeFullConformanceAttestationFile `
        -RepoRoot $repoRoot `
        -Godot $Godot `
        -AttestationPath $FullConformanceAttestation
    if (-not [bool]$physicalAttestation.ok) {
        Write-R23D5PhysicalRefusal -Reason (
            "full_godot_v2_attestation_invalid:" +
            (@($physicalAttestation.failure_codes) -join ",")
        )
        throw "QSDK-R23D5 full-conformance attestation is invalid"
    }
    $operationLock = Enter-SporeSporeLocomotionOperationLock -Role physical
} else {
    $operationLock = Enter-SporeSporeLocomotionOperationLock -Role conformance
}
if (-not [bool]$operationLock.acquired) {
    if ($RunPhysical) {
        Write-R23D5PhysicalRefusal -Reason "global_locomotion_operation_lock_held"
    }
    throw "QSDK-R23D5 global locomotion operation lock is held"
}

$scratchRoot = Join-Path $sdkRoot (
    "target\qsdk-r23d5-supervisor-preflight\" + [guid]::NewGuid().ToString("N")
)
[void][IO.Directory]::CreateDirectory($scratchRoot)
try {
    # Exercise the exact future physical-build helper while worlds remain
    # impossible. The engine worker gates below independently exercise their
    # own entrypoints; this additionally proves the supervisor's aggregate
    # reproducible-runtime recipe and exact R23D5 Rapier binary selection.
    $developmentCommit = Invoke-R23D5Git @("rev-parse", "HEAD")
    $developmentRuntime = Initialize-R23D5RuntimeArtifacts `
        -SourceCommit $developmentCommit
    Assert-R23D5Exact (
        [string]$developmentRuntime.source_commit -ceq $developmentCommit -and
        -not [bool]$developmentRuntime.physical_acceptance_authority -and
        [string]$developmentRuntime.artifacts.rapier_worker -like
            "*qsdk_r23d5_dependency_closed.exe"
    ) "QSDK-R23D5 zero-world runtime materialization failed"
    $developmentExternalRuntimeBindings = @(Get-R23D5ExternalRuntimeBindings)
    Assert-R23D5Exact (
        $developmentExternalRuntimeBindings.Count -eq 4 -and
        @($developmentExternalRuntimeBindings.name) -join "," -ceq
            "godot_jolt_host,mujoco_python_host,evaluator_python_host,powershell_trace_retainer_host" -and
        [string]$developmentExternalRuntimeBindings[2].path -ceq $resolvedPythonPath -and
        [string]$developmentExternalRuntimeBindings[3].path -ceq $resolvedPowerShellPath -and
        @($developmentExternalRuntimeBindings | Where-Object {
            -not (Test-Path -LiteralPath ([string]$_.path) -PathType Leaf) -or
            [string]::IsNullOrWhiteSpace([string]$_.raw_sha256)
        }).Count -eq 0
    ) "QSDK-R23D5 zero-world external-runtime binding failed"

    $gateSpecs = @(
        [ordered]@{
            path = Join-Path $repoRoot "tests\test_qsdk_r23d5_declaration.ps1"
            prefix = "QSDK_R23D5_DECLARATION_PASS "
            arguments = @()
        },
        [ordered]@{
            path = Join-Path $repoRoot (
                "tests\test_qsdk_r23d5_dependency_and_marker_contract.ps1"
            )
            prefix = "QSDK_R23D5_DEPENDENCY_MARKER_PASS "
            arguments = @()
        },
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d5_mujoco_worker_preflight.ps1"
            prefix = "QSDK_R23D5_MUJOCO_WORKER_PASS "
            arguments = @()
        },
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d5_rapier_worker_preflight.ps1"
            prefix = "QSDK_R23D5_RAPIER_WORKER_PASS "
            arguments = @()
        },
        [ordered]@{
            path = Join-Path $sdkRoot "run_qsdk_r23d5_godot_jolt_worker_preflight.ps1"
            prefix = "QSDK_R23D5_GODOT_JOLT_WORKER_PASS "
            arguments = @("-Godot", $Godot)
        }
    )
    $gateResults = [Collections.Generic.List[object]]::new()
    foreach ($spec in $gateSpecs) {
        $gateResults.Add((Invoke-R23D5Gate `
            -Path ([string]$spec.path) `
            -PassPrefix ([string]$spec.prefix) `
            -AdditionalArguments @($spec.arguments)))
    }

    $evaluatorTests = Invoke-R23D5Process `
        -FileName $resolvedPythonPath `
        -Arguments @(
            "-m", "unittest", "-v",
            "sdk.turning.test_r23d5_physical_evaluator"
        ) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 180
    if ($evaluatorTests.stdout) { Write-Host ([string]$evaluatorTests.stdout).TrimEnd() }
    if ($evaluatorTests.stderr) { Write-Host ([string]$evaluatorTests.stderr).TrimEnd() }
    Assert-R23D5Exact (
        -not [bool]$evaluatorTests.timed_out -and
        [int]$evaluatorTests.exit_code -eq 0
    ) "QSDK-R23D5 production evaluator tests failed"

    $physicalBypass = Invoke-R23D5Process `
        -FileName $resolvedPowerShellPath `
        -Arguments @(
            "-NoLogo", "-NoProfile", "-File", $PSCommandPath, "-RunPhysical"
        ) `
        -WorkingDirectory $repoRoot `
        -TimeoutSeconds 60
    Assert-R23D5Exact (
        -not [bool]$physicalBypass.timed_out -and
        [int]$physicalBypass.exit_code -ne 0
    ) "QSDK-R23D5 direct physical bypass did not refuse"
    $refusal = Get-R23D5JsonMarker `
        -Text $physicalBypass.stdout `
        -Prefix "QSDK_R23D5_PHYSICAL_REFUSAL "
    Assert-R23D5Exact (
        [string]$refusal.refusal_stage -ceq "before_attempt_or_world" -and
        [int]$refusal.physical_process_launch_count -eq 0 -and
        [int]$refusal.world_attempt_count -eq 0 -and
        [int]$refusal.world_build_count -eq 0 -and
        -not [bool]$refusal.physical_acceptance_authority
    ) "QSDK-R23D5 physical refusal receipt changed"

    $receipt = [ordered]@{
        schema_version = "sporespore_qsdk_r23d5_supervisor_preflight_v1"
        campaign_id = $campaignId
        gate_id = $gateId
        implementation_contract_raw_sha256 = Get-R23D5RawSha256 $implementationPath
        declared_source_binding_count = $declaredPaths.Count
        runtime_materialization_pass_count = 1
        external_runtime_binding_pass_count = 4
        stage_zero_gate_pass_count = 2
        declared_worker_dependency_count = 21
        terminal_marker_family_count = 3
        terminal_marker_case_count = 15
        worker_gate_pass_count = 3
        production_evaluator_test_count = 8
        physical_authorization_refusal_count = 1
        stage_a_declared_cell_count = 2
        stage_b_declared_cell_count_if_selected = 9
        possible_worker_identity_count = 11
        exact_controller_horizon_step_count = 2992
        exact_restoration_horizon_step_count = 540
        exact_passive_horizon_step_count = 240
        exact_trace_row_count_per_cell = 3772
        actual_physical_process_launch_count = 0
        actual_world_attempt_count = 0
        actual_world_build_count = 0
        physical_execution_authorized = $false
        command_conditioned_turning = $false
        bilateral_signed_turning = $false
        portable_basic_turning = $false
        cross_engine_equivalence = $false
        q_sdk_r23_satisfied = $false
        release_authorized = $false
        physical_acceptance_authority = $false
    }
    Write-Host (
        "QSDK_R23D5_SUPERVISOR_PREFLIGHT " +
        ($receipt | ConvertTo-Json -Depth 100 -Compress)
    )
    Write-Host (
        "QSDK_R23D5_SUPERVISOR_PASS runtime_materialization=1 external_runtimes=4 " +
        "stage_zero=2 dependencies=21 marker_families=3 marker_cases=15 workers=3 " +
        "evaluator_tests=8 physical_refusal=1 stage_a_cells=2 " +
        "stage_b_cells=9 possible_identities=11 controller_steps=2992 " +
        "restoration_steps=540 passive_steps=240 trace_rows=3772 " +
        "actual_worlds=0 physical_authority=False"
    )
    if ($RunPhysical) {
        Invoke-R23D5PhysicalCampaign `
            -Source $physicalSource `
            -Attestation $physicalAttestation `
            -ZeroWorldReceipt $receipt `
            -Implementation $implementation
    }
} finally {
    if (Test-Path -LiteralPath $scratchRoot -PathType Container) {
        Remove-Item -LiteralPath $scratchRoot -Recurse -Force
    }
    if ($null -ne $operationLock) {
        Exit-SporeSporeLocomotionOperationLock $operationLock
    }
}
